module UploadWorkflow::Simulation
  include UploadWorkflow::Data

  # Properties used to drive simulated behavior.
  #
  # @type [Hash{Symbol=>Boolean,Integer}]
  #
  PROPERTY: Hash[Symbol,bool|Integer]

  class ReviewerTask < Workflow::Base::Simulation::SimulatedTask
    def initialize: (?started: bool started) -> void
  end

  class RetrievalTask < Workflow::Base::Simulation::SimulatedTask
    def initialize: (?started: bool started) -> void
  end

  class IndexTask < Workflow::Base::Simulation::SimulatedTask
    def initialize: (?started: bool started) -> void
  end
end

module UploadWorkflow::Events
  # The user initiates submission of a new entry.
  def create: () -> untyped

  # The user initiates modification of an existing entry.
  def edit: () -> untyped

  # The user initiates removal of an existing entry.
  def remove: () -> untyped

  # The user chooses to cancel the submission process.
  def cancel: () -> untyped

  # The reviewer (or the system) indicates that the submission requires
  # change(s).
  def reject: () -> untyped

  # The reviewer initiates review of the submission.
  def review: () -> untyped

  # The system is resetting the workflow state.
  def reset: () -> untyped

  # The system is returning to the previous workflow state.
  def resume: () -> untyped
end

class Object
  public

  public
end
