# Physical dimensions of this volume (in centimeters).
#
# @attr [String] height
# @attr [String] width
# @attr [String] thickness
#
# @see https://developers.google.com/books/docs/v1/reference/volumes
#
class Lookup::GoogleBooks::Record::Dimensions < Lookup::GoogleBooks::Api::Record
  include Lookup::GoogleBooks::Shared::CommonMethods
end
