# Industry standard identifiers for this volume.
#
# @attr [String] type                 %w(ISBN_10 ISBN_13 ISSN OTHER)
# @attr [String] identifier
#
# @see https://developers.google.com/books/docs/v1/reference/volumes
#
class Lookup::GoogleBooks::Record::Identifier < Lookup::GoogleBooks::Api::Record
  include Lookup::GoogleBooks::Shared::CommonMethods

  def to_s:   () -> String
  def blank?: () -> bool
  def value:  () -> String
end
