# Metadata record schema for Google Search API results.
#
# @attr [String]     kind
# @attr [String]     id
# @attr [String]     etag
# @attr [String]     selfLink
# @attr [VolumeInfo] volumeInfo
# @attr [UserInfo]   userInfo
# @attr [SaleInfo]   saleInfo
# @attr [AccessInfo] accessInfo
# @attr [SearchInfo] searchInfo
#
# @see https://developers.google.com/books/docs/v1/reference/volumes
#
class Lookup::GoogleBooks::Record::Item < Lookup::GoogleBooks::Api::Record
  include Lookup::GoogleBooks::Shared::CreatorMethods

  include Lookup::GoogleBooks::Shared::DateMethods

  include Lookup::GoogleBooks::Shared::IdentifierMethods

  include Lookup::GoogleBooks::Shared::TitleMethods
end
