# Any information about a volume related to the eBookstore and/or
# purchase-ability. This information can depend on the country where the
# request originates from (i.e., books may not be for sale in certain
# countries).
#
# @attr [String]   country
# @attr [String]   saleability        %w(... FREE FOR_SALE NOT_FOR_SALE)
# @attr [Boolean]  isEbook
# @attr [Price]    listPrice
# @attr [Price]    retailPrice
# @attr [String]   buyLink
# @attr [DateTime] onSaleDate
#
# == Observed but not documented
#
# @attr [Hash]     offers
#
# @see https://developers.google.com/books/docs/v1/reference/volumes
#
class Lookup::GoogleBooks::Record::SaleInfo < Lookup::GoogleBooks::Api::Record
  include Lookup::GoogleBooks::Shared::DateMethods
end
