# IaDownloadService::Request::Records
#
module IaDownloadService::Request::Records
  include IaDownloadService::Common

  # Get a download from Internet Archive, possibly generated on-the-fly.
  #
  # @param [String] url
  # @param [Hash]   opt
  #
  # @raise [ExecError]                If the download failed.
  #
  # @return [Array<(String,String,String)>]
  # @return [Array<(String,String,nil)>]
  #
  def download: (String url, **untyped opt) -> [String, String, (String|nil)]
end
