# Base class for object-specific serializers that process JSON data.
#
class BvDownload::Api::Serializer::Json < Api::Serializer::Json
  include BvDownload::Api::Serializer::Json::Schema

  include BvDownload::Api::Serializer::Json::Associations
end
