# Methods supporting manipulation of Model instance fields.
#
module BaseDecorator::Fields
  include BaseDecorator::Common

  include BaseDecorator::Configuration

  # Database columns with hierarchical data.
  #
  # @return [Array<Symbol>]
  #
  def compound_fields: () -> symArray

  # emma_data_fields
  #
  # @param [Symbol] field
  #
  # @return [Hash{Symbol=>Hash}]
  #
  def emma_data_fields: (?Symbol field) -> Hash[Symbol,symHash]

  # Render the contents of the :emma_data field in the same order of EMMA data
  # fields as defined for search results.
  #
  # @param [String, Hash, nil] value
  # @param [Symbol]            field
  # @param [Hash]              opt
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see #render_json_data
  #
  def render_emma_data: (?(String|anyHash|nil) value, ?field: Symbol, **untyped opt) -> ActiveSupport::SafeBuffer

  # Render the contents of the :file_data field.
  #
  # @param [String, Hash, nil] value
  # @param [Symbol]            field
  # @param [Hash]              opt
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see #render_json_data
  #
  def render_file_data: (?(String|anyHash|nil) value, ?field: Symbol, **untyped opt) -> ActiveSupport::SafeBuffer

  # Render hierarchical data.
  #
  # @param [String, Hash, nil] value
  # @param [Hash, nil]         outer  Options for outer div.
  # @param [String]            css    Characteristic CSS class/selector.
  # @param [Hash]              opt    Passed to #render_field_values
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def render_json_data: ((String|anyHash|nil) value, ?outer: symHash|nil, ?css: String, **untyped opt) -> ActiveSupport::SafeBuffer

  # Field/value pairs.
  #
  # @param [Model, Hash, nil]  item     Default: *pairs*.
  # @param [Model, Hash, nil]  pairs    Default: `#object`.
  # @param [Hash, nil]         before   Additional leading label/value pairs.
  # @param [Hash, nil]         after    Additional trailing label/value pairs.
  # @param [ActionConfig, nil] config
  #
  # @return [Hash]
  #
  def value_pairs: (?(Model|anyHash|nil) item, ?pairs: Model|anyHash|nil, ?before: anyHash|nil, ?after: anyHash|nil, ?config: ActionConfig|nil, **untyped _ignored) -> anyHash

  # A table of fields with their property objects.
  #
  # @param [String, Symbol, nil]        action
  # @param [Array<Symbol>, nil]         only        Only matching fields.
  # @param [Array<Symbol>, nil]         except      Not matching fields.
  # @param [Symbol, Array<Symbol>, nil] field_root  Limits field configuration.
  # @param [Hash]                       opt         To #value_pairs.
  #
  # @return [Hash{Symbol=>FieldConfig}]
  #
  # === Usage Notes
  # If *field_root* is given it is used to transform the field into a path
  # into the configuration.  The only current use is to allow specification of
  # :file_data so that configuration lookup is limited to the hierarchy within
  # the configuration for :file_data.  (This allows [:file_data][:id] to be
  # associated with the proper field configuration.)
  #
  def property_pairs: (?action: String|Symbol|nil, ?only: symArray|nil, ?except: symArray|nil, ?field_root: Symbol|symArray|nil, **untyped opt) -> Hash[Symbol,FieldConfig]

  # Local options for #value_pairs.
  #
  # @type [Array<Symbol>]
  #
  VALUE_PAIRS_OPT: symArray

  # Local options for #property_pairs.
  #
  # @type [Array<Symbol>]
  #
  PROPERTY_PAIRS_OPT: symArray

  # Field type indicators mapped on to related class(es).
  #
  # @type [Hash{Symbol=>Array<Class>}]
  #
  RENDER_FIELD_TYPE_TABLE:  Hash[Symbol,Array[Class]]

  # Mapping of actual type to the appropriate field type indicator.
  #
  # @type [Hash{Class=>Symbol}]
  #
  RENDER_FIELD_TYPE: Hash[Class,Symbol]

  # Convert certain field types.
  #
  # @type [Hash{Symbol=>Symbol}]
  #
  REPLACE_FIELD_TYPE: Hash[Symbol,Symbol]

  # Render a value for use on an input form.
  #
  # @param [String]   name
  # @param [any, nil] value
  # @param [Hash]     opt             Passed to render method except for:
  #
  # @option opt [String] :base
  # @option opt [String] :name
  # @option opt [Symbol] :type
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def render_form_field_item: (String name, untyped value, **untyped opt) -> ActiveSupport::SafeBuffer

  # Local options for #render_check_box.
  #
  # @type [Array<Symbol>]
  #
  CHECK_OPT: symArray

  # render_check_box
  #
  # @param [String]      name
  # @param [any, nil]    value
  # @param [Symbol, nil] tag
  # @param [String]      css          Characteristic CSS class/selector.
  # @param [Hash]        opt
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def render_check_box: (String name, untyped value, ?tag: Symbol|nil, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Indicate whether the value is a valid range type.
  #
  # @param [any, nil] range
  # @param [Boolean]  fatal           If *true*, raise an exception if invalid.
  #
  # @raise [RuntimeError]             If not valid and *fatal* is *true*.
  #
  def valid_range?: (untyped range, ?fatal: bool) -> bool

  # Translate attributes.
  #
  # @param [Hash] opt
  #
  # @return [Hash]                    The potentially-modified *opt* hash.
  #
  # === Implementation Notes
  # Disabled input fields are given the :readonly attribute because setting the
  # :disabled attribute would prevent those fields from being included in the
  # data sent with the form submission.
  #
  def normalize_attributes!: (symHash opt) -> symHash

  # The defined levels for rendering an item hierarchically.
  #
  # @param [Hash] opt
  #
  # @return [Hash{Symbol=>Array<Symbol,Integer>}]
  #
  def field_levels: (**untyped opt) -> Hash[Symbol, Array[Symbol|Integer]]

  # Return with the CSS classes associated with the items field scope(s).
  #
  # @param [Array, Symbol, String, nil] value
  #
  # @return [Array<String>]
  #
  # -
  # === Variations
  # +
  #
  # @overload field_scopes(single)
  #   Interpret the argument as a field name used to lookup the scope values.
  #   @param [Symbol, String, nil] single
  #   @return [Array<String>]
  #
  # @overload field_scopes(array)
  #   Extract the scopes from *array*.
  #   @param [Array<Symbol>]       array
  #   @return [Array<String>]
  #
  def field_scopes: ((symArray|Symbol|String|nil) value) -> strArray

  # All known EMMA record fields (including those not currently in use).
  #
  # @type [Array<Symbol>]
  #
  EMMA_DATA_FIELDS: symArray

  # EMMA data field prefixes with trailing underscore for #model_html_id.
  #
  # @type [Array<String>]
  #
  FIELD_PREFIX: strArray

  # Suffixes indicating field names to be preserved in #model_html_id.
  #
  # @type [Array<String>]
  #
  RESERVED_SUFFIX: strArray

  # Create a base for .field-* and .value-* classes.
  #
  # @param [Symbol, String, nil] base   Default: 'None'.
  #
  # @return [String]
  #
  def model_html_id: ((Symbol|String|nil) base) -> String

  # Create a base for label and value identifiers.
  #
  # @param [Symbol, String, nil]  name
  # @param [String, nil]          base
  # @param [Symbol, nil]          field
  # @param [String, Symbol, nil]  label
  # @param [String, Integer, nil] index
  # @param [String, Symbol, nil]  group
  # @param [Hash]                 opt       Passed to #html_id.
  #
  # @return [String]
  #
  def field_html_id: (?(Symbol|String|nil) name, ?id_base: String|nil, ?field: Symbol|nil, ?label: String|Symbol|nil, ?index: String|Integer|nil, ?group: String|Symbol|nil, **untyped opt) -> String

  # format_org
  #
  # @param [any, nil] value
  #
  # @return [String, nil]
  #
  def format_org
    :     (Org|String|Integer|nil value, **untyped _ignored) -> String
    |     (ApplicationRecord      value, **untyped _ignored) -> (String | nil)
    |     (untyped                value, **untyped _ignored) -> nil

  # format_user
  #
  # @param [any, nil] value
  #
  # @return [String, nil]
  #
  def format_user
    :     (User|String|Integer|nil value, **untyped _ignored) -> String
    |     (ApplicationRecord       value, **untyped _ignored) -> (String | nil)
    |     (untyped                 value, **untyped _ignored) -> nil

  # Render a value into ISO 8601 format if possible.
  #
  # @param [any, nil] value
  #
  # @return [String, nil]
  #
  def format_datetime: (untyped value) -> (String | nil)

  # Match a major section title in a table-of-contents listing.
  #
  # @type [Regexp]
  #
  SECTION_TITLE_RE: Regexp

  # For use with String#scan to step through quote/attribute pairs.
  #
  # @type [Regexp]
  #
  BLURB_RE: Regexp

  # Reformat descriptions which are structured in a way that one would find
  # in MARC metadata.
  #
  # @param [String, Array]  text
  # @param [String, Regexp] separator
  #
  # @return [Array<String>]
  #
  # === Usage Notes
  # Descriptions like this don't currently seem to appear very often in search
  # results.  Even for those that do, they may not adhere to the expected
  # layout of information, and this method may not be that beneficial in those
  # cases.
  #
  def format_description: (String|anyArray text, ?separator: String|Regexp, **untyped _ignored) -> strArray

  # Seen in some IA records.
  #
  # @param [String] text
  #
  # @return [String]
  #
  def double_quotes_to_sections: (String text) -> String

  # Seen in some IA records.
  #
  # @param [String] text
  #
  # @return [String]
  #
  def double_dash_to_sections: (String text) -> String

  # Transform a string with newlines/semicolons into an array of lines.
  #
  # @param [String, Array]  text
  # @param [String, Regexp] separator
  #
  # @return [Array<String>]
  #
  def format_multiline: (String|anyArray text, ?separator: String|Regexp, **untyped _ignored) -> strArray

  VALID_LANG: String

  INVALID_LANG: String

  INVALID_ID: String

  # Wrap invalid language values in a *span*.
  #
  # @param [any]     value            Value to check.
  # @param [Boolean] code             If *true* display the ISO 639 code.
  #
  # @return [ActiveSupport::SafeBuffer, String, Array]
  #
  # -
  # === Variations
  # +
  #
  # @overload mark_invalid_languages(value, code: false)
  #   @param [String]        value
  #   @param [Boolean]       code
  #   @return [ActiveSupport::SafeBuffer, String, nil]
  #
  # @overload mark_invalid_languages(array, code: false)
  #   @param [Array<String>] array
  #   @param [Boolean]       code
  #   @return [Array<ActiveSupport::SafeBuffer, String>]
  #
  def mark_invalid_languages
    : (anyArray value, ?code: bool, **untyped _ignored) -> Array[String|ActiveSupport::SafeBuffer]
    | (String   value, ?code: bool, **untyped _ignored) -> (String | ActiveSupport::SafeBuffer)
    | (untyped  value, ?code: bool, **untyped _ignored) -> ActiveSupport::SafeBuffer

  # Wrap invalid identifier values in a *span*.
  #
  # @param [any] value                Value to check.
  #
  # @return [ActiveSupport::SafeBuffer, String, Array]
  #
  # -
  # === Variations
  # +
  #
  # @overload mark_invalid_identifiers(value)
  #   @param [String]        value
  #   @return [String, ActiveSupport::SafeBuffer]
  #
  # @overload mark_invalid_identifiers(array)
  #   @param [Array<String>] array
  #   @return [Array<String, ActiveSupport::SafeBuffer>]
  #
  def mark_invalid_identifiers
    : (anyArray value, **untyped _ignored) -> Array[String|ActiveSupport::SafeBuffer]
    | (String   value, **untyped _ignored) -> (String | ActiveSupport::SafeBuffer)
    | (untyped  value, **untyped _ignored) -> ActiveSupport::SafeBuffer

  private

  def self.included: (Module base) -> void
end
