# Methods supporting manipulation of Model instance fields.
#
module BaseDecorator::Fields
  include Emma::Json

  include BaseDecorator::Links

  # Field value used to explicitly indicate missing data.
  #
  # @type [String]
  #
  EMPTY_VALUE: String

  # Field/value pairs.
  #
  # @param [Model, Hash, nil] item    Default: `#object`.
  #
  # @return [Hash]
  #
  def field_values: (?(Model|anyHash|nil) item) -> anyHash

  # field_pairs
  #
  # @param [Model, Hash, nil]           item        Passed to #field_values.
  # @param [String, Symbol, nil]        action
  # @param [Symbol, Array<Symbol>, nil] field_root  Limits field configuration.
  #
  # @return [Hash{Symbol=>Hash}]
  #
  # == Usage Notes
  # If *field_root* is given it is used to transform the field into a path
  # into the configuration.  The only current use is to allow specification of
  # :file_data so that configuration lookup is limited to the hierarchy within
  # the configuration for :file_data.  (This allows [:file_data][:id] to be
  # associated with the proper field configuration.)
  #
  def field_pairs: (?(Model|anyHash|nil) item, ?action: String|Symbol|nil) -> Hash[Symbol,symHash]

  # Field type indicators mapped on to related class(es).
  #
  # @type [Hash{Symbol=>Array<Class>}]
  #
  RENDER_FIELD_TYPE_TABLE:  Hash[Symbol,Array[Class]]

  # Mapping of actual type to the appropriate field type indicator.
  #
  # @type [Hash{Class=>Symbol}]
  #
  RENDER_FIELD_TYPE: Hash[Class,Symbol]

  # Convert certain field types.
  #
  # @type [Hash{Symbol=>Symbol}]
  #
  REPLACE_FIELD_TYPE: Hash[Symbol,Symbol]

  # render_field_item
  #
  # @param [String] name
  # @param [*]      value
  # @param [Hash]   opt               Passed to render method except for:
  #
  # @option opt [String] :base
  # @option opt [String] :name
  # @option opt [Symbol] :type
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def render_field_item: (String name, untyped value, **untyped opt) -> ActiveSupport::SafeBuffer

  # Local options for #render_check_box.
  #
  # @type [Array<Symbol>]
  #
  CHECK_OPTIONS: symArray

  # render_check_box
  #
  # @param [String] name
  # @param [Any]    value
  # @param [Hash]   opt
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def render_check_box: (String name, untyped value, **untyped opt) -> ActiveSupport::SafeBuffer

  # This is a "hook" to allow customization by SearchDecorator.
  #
  # @param [Symbol]    field
  # @param [Hash, nil] config
  #
  # @return [Hash]
  #
  def field_properties: (Symbol field, ?(symHash|nil) config) -> symHash

  # Indicate whether the value is a valid range type.
  #
  # @param [*]       range
  # @param [Boolean] exception        If *true*, raise an exception if *false*.
  #
  # @raise [RuntimeError]             If not valid and *exception* is *true*.
  #
  def valid_range?: (untyped range, ?exception: bool) -> bool

  # Translate attributes.
  #
  # @param [Hash] opt
  #
  # @return [Hash]                    The potentially-modified *opt* hash.
  #
  # == Implementation Notes
  # Disabled input fields are given the :readonly attribute because the
  # :disabled attribute prevents those fields from being included in the data
  # sent with the form submission.
  #
  def normalize_attributes!: (symHash opt) -> symHash

  # The defined levels for rendering an item hierarchically.
  #
  # @param [Hash] opt
  #
  # @return [Hash{Symbol=>Array<Symbol,Integer>}]
  #
  def field_levels: (**untyped opt) -> Hash[Symbol, Array[Symbol|Integer]]

  # Return with the CSS classes associated with the items field scope(s).
  #
  # @param [Array, Symbol, String, nil] value
  #
  # @return [Array<String>]
  #
  # -
  # == Variations
  # +
  #
  # @overload field_scopes(single)
  #   Interpret the argument as a field name used to lookup the scope values.
  #   @param [Symbol, String, nil] single
  #   @return [Array<String>]
  #
  # @overload field_scopes(array)
  #   Extract the scopes from *array*.
  #   @param [Array<Symbol>]       array
  #   @return [Array<String>]
  #
  def field_scopes: ((symArray|Symbol|String|nil) value) -> strArray

  # EMMA data field prefixes with trailing underscore for #model_html_id.
  #
  # @type [Array<String>]
  #
  FIELD_PREFIX: strArray

  # Suffixes indicating field names to be preserved in #model_html_id.
  #
  # @type [Array<String>]
  #
  RESERVED_SUFFIX: strArray

  # Create a base for .field-* and .value-* classes.
  #
  # @param [Symbol, String, nil] base   Default: 'None'.
  #
  # @return [String]
  #
  def model_html_id: ((Symbol|String|nil) base) -> String

  # format_datetime
  #
  # @param [*] value
  #
  # @return [String, nil]
  #
  def format_datetime: (untyped value) -> (String | nil)

  # Match a major section title in a table-of-contents listing.
  #
  # @type [Regexp]
  #
  SECTION_TITLE_RE: Regexp

  # For use with String#scan to step through quote/attribute pairs.
  #
  # @type [Regexp]
  #
  BLURB_RE: Regexp

  # Reformat descriptions which are structured in a way that one would find
  # in MARC metadata.
  #
  # @param [String] text
  #
  # @return [Array<String>]
  #
  # == Usage Notes
  # Descriptions like this don't currently seem to appear very often in search
  # results.  Even for those that do, they may not adhere to the expected
  # layout of information, and this method may not be that beneficial in those
  # cases.
  #
  def format_description: (String text) -> strArray

  # Seen in some IA records.
  #
  # @param [String]
  #
  # @return [String]
  #
  def double_quotes_to_sections: (String text) -> String

  # Seen in some IA records.
  #
  # @param [String]
  #
  # @return [String]
  #
  def double_dash_to_sections: (String text) -> String

  # Transform a string with newlines/semicolons into an array of lines.
  #
  # @param [String] text
  #
  # @return [Array<String>]
  #
  def format_multiline: (String text) -> strArray

  VALID_LANGUAGE: String

  INVALID_LANGUAGE: String

  # Wrap invalid language values in a *span*.
  #
  # @param [Any]     value            Value to check.
  # @param [Boolean] code             If *true* display the ISO 639 code.
  #
  # @return [ActiveSupport::SafeBuffer, String, Array]
  #
  # -
  # == Variations
  # +
  #
  # @overload mark_invalid_languages(value, code: false)
  #   @param [String]        value
  #   @param [Boolean]       code
  #   @return [String, ActiveSupport::SafeBuffer, nil]
  #
  # @overload mark_invalid_languages(array, code: false)
  #   @param [Array<String>] array
  #   @param [Boolean]       code
  #   @return [Array<String, ActiveSupport::SafeBuffer>]
  #
  def mark_invalid_languages: (String   value, ?code: bool) -> (ActiveSupport::SafeBuffer | String | nil)
                            | (strArray value, ?code: bool) -> Array[ActiveSupport::SafeBuffer|String]

  # Wrap invalid identifier values in a *span*.
  #
  # @param [Any] value                Value to check.
  #
  # @return [ActiveSupport::SafeBuffer, String, Array]
  #
  # -
  # == Variations
  # +
  #
  # @overload mark_invalid_identifiers(value)
  #   @param [String]        value
  #   @return [String, ActiveSupport::SafeBuffer]
  #
  # @overload mark_invalid_identifiers(array)
  #   @param [Array<String>] array
  #   @return [Array<String, ActiveSupport::SafeBuffer>]
  #
  def mark_invalid_identifiers: (String   value) -> (ActiveSupport::SafeBuffer | String | nil)
                              | (strArray value) -> Array[ActiveSupport::SafeBuffer|String]

  private

  def self.included: (Module base) -> void
end
