# Methods supporting tabular display of Model instances.
#
module BaseDecorator::Table
  include BaseDecorator::Common

  include BaseDecorator::List

  include BaseDecorator::Row

  # Make the heading row stick to the top of the table when scrolling.
  #
  # @type [Boolean]
  #
  # @see file:stylesheets/layouts/controls/_tables.scss "CSS class .sticky-head"
  #
  STICKY_HEAD: bool

  # Give the heading row a background.
  #
  # @type [Boolean]
  #
  # @see file:stylesheets/layouts/controls/_tables.scss "CSS class .dark-head"
  #
  DARK_HEAD: bool

  # Options used by some or all of the methods involved in rendering items in
  # a tabular form.
  #
  # @type [Array<Symbol>]
  #
  MODEL_TABLE_OPTIONS:    symArray
  MODEL_TABLE_DATA_OPT:   symArray
  MODEL_TABLE_HEAD_OPT:   symArray
  MODEL_TABLE_ENTRY_OPT:  symArray
  MODEL_TABLE_ROW_OPT:    symArray
  MODEL_TABLE_PART_OPT:   symArray

  # Default number of rows per table page.
  #
  # @type [Integer]
  #
  TABLE_PAGE_SIZE: Integer

  # The collection of items to be presented in tabular form.
  #
  # @param [Hash] opt                 Modifies *object* results.
  #
  # @return [Array<Model>]
  # @return [ActiveRecord::Relation]
  # @return [ActiveRecord::Associations::CollectionAssociation]
  #
  def table_row_items: (**untyped opt) -> decoratorRowItems

  # The #model_type of individual associated items for iteration.
  #
  # @return [Symbol]
  #
  # @see BaseCollectionDecorator::SharedClassMethods#decorator_class
  #
  def table_row_model_type: () -> Symbol

  # The default CSS class for a table element.
  #
  # @return [String]
  #
  def table_css_class: () -> String

  # Indicate whether a table presents as an element with the HTML 'table' role.
  #
  def table_role?: () -> bool

  # The HTML role of the table element.
  #
  # @param [Boolean] table
  #
  # @return [String]
  #
  def table_role: (?table: bool) -> String

  # The HTML role of cells within the table.
  #
  # @param [Boolean] table
  #
  # @return [String]
  #
  def table_cell_role: (?table: bool) -> String

  # The number of rows of associated items per table page.
  #
  # @return [Integer]
  #
  def table_page_size: () -> Integer

  # Get a subset of associated items.
  #
  # @param [Hash] opt                 #ROW_PAGE_PARAMS passed to #row_page.
  #
  # @return [Array<Model>]
  #
  def table_row_page: (**untyped opt) -> Array[Model]

  # Options used by BaseCollectionDecorator::Table#render_table.
  #
  # @type [Array<Symbol>]
  #
  RENDER_TABLE_OPTIONS: symArray

  # Render the object for use within a table of items.
  #
  # @param [Integer] row
  # @param [Integer] col
  # @param [Hash]    opt              To column except:
  #
  # @option opt [Hash]   :outer_opt   Options to outer (row) element.
  # @option opt [Hash]   :inner_opt   Options to inner (column cell) element.
  # @option opt [Symbol] :outer_tag   If !`opt[:outer_opt][:tag]`; default: :tr
  # @option opt [Symbol] :inner_tag   If !`opt[:inner_opt][:tag]`; Default: :td
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see #table_heading
  #
  def render_table_row: (?row: Integer, ?col: Integer, **untyped opt) ?{ (Symbol field, FieldConfig prop, **untyped opt) -> (strArray|String|nil) } -> ActiveSupport::SafeBuffer

  # table_entry
  #
  # @param [Hash] opt                 To #render_table_row
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def table_entry: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Fields and configurations augmented with a :value entry containing the
  # current field value.
  #
  # @param [Boolean] limited          Do not include fields that are :ignored
  #                                     or have the wrong :role.
  # @param [Hash]    opt              Passed to #field_property_pairs and
  #                                     #list_field_value.
  #
  # @return [Hash{Symbol=>FieldConfig}]
  #
  def table_field_values: (?limited: bool, **untyped opt) -> Hash[Symbol, FieldConfig]

  # Transform a field value for rendering in a table.
  #
  # @param [any, nil]    value        Passed to #list_field_value.
  # @param [Symbol, nil] field        Passed to #list_field_value.
  # @param [Hash]        opt          Passed to #list_field_value.
  #
  # @return [any, nil]
  #
  def table_field_value: (untyped value, field: Symbol|nil, **untyped opt) -> (Field::Type | String | nil)

  # Setup row/column HTML options.
  #
  # @param [Symbol, String] field
  # @param [Integer, nil]   row
  # @param [Integer, nil]   col
  # @param [Hash, nil]      opt
  #
  # @return [Hash]
  #
  def model_rc_options: ((Symbol|String) field, ?(Integer|nil) row, ?(Integer|nil) col, ?(symHash|nil) opt) -> symHash

  private

  def self.included: (Module base) -> void
end
