# BookshareService::Properties
#
module BookshareService::Properties
  include ApiService::Properties

  # Configuration values from config/locales/service.en.yml
  #
  # @type [Hash{Symbol=>Any}]
  #
  CONFIGURATION: symHash

  # Maximum accepted value for a :limit parameter.
  #
  # @type [Integer]
  #
  # == Implementation Notes
  # Determined experimentally.
  #
  MAX_LIMIT: Integer

  # For use in example.
  #
  # @type [String]
  #
  DEFAULT_USER: String

  # The primary Bookshare account used for testing.
  #
  # @type [String]
  #
  TEST_ACCOUNT: String

  # The identifier (:userAccountId) for the test member "Placeholder Member".
  # (Only usable by #TEST_ACCOUNT)
  #
  # @type [String]
  #
  TEST_MEMBER: String

  # Bookshare accounts used for testing.
  #
  # @type [Array<String>]
  #
  TEST_USERS: strArray

  # Configuration for the API service.
  #
  # @type [Hash{Symbol=>Any}]
  #
  def configuration: () -> symHash

  attr_reader base_url: String

  # The URL for the API connection.
  #
  # @return [String]
  #
  # @see #BOOKSHARE_BASE_URL
  #
  def base_url: () -> String

  # Bookshare API key.
  #
  # @return [String, nil]
  #
  # @see #BOOKSHARE_API_KEY
  #
  def api_key: () -> (String | nil)

  # API version is not a part of request URLs.
  #
  # @return [String, nil]
  #
  # @see #BOOKSHARE_API_VERSION
  #
  def api_version: () -> (String | nil)

  private

  def self.included: (Module base) -> void
end
