# Interface to the shared data structure which holds the definition of the API
# requests and parameters.
#
module BookshareService::Definition
  private

  def self.included: (Module base) -> void
end
