module ManifestItem::Config
  # Indicates whether cells in the 'file_data' column include the ability to
  # upload a file associated with the manifest item.
  #
  # @type [Boolean]
  #
  # @see file:assets/javascripts/controllers/manifest-edit.js *EMBED_UPLOADER*
  #
  EMBED_UPLOADER: bool

  # To avoid complications for the initial release of bulk submissions, there
  # is no selection of destination repository -- it is implicitly 'EMMA'.
  #
  # To support repository selection, set this value to *true*.
  #
  # @type [Boolean]
  #
  ALLOW_NIL_REPOSITORY: bool

  # Status values and labels for the metadata associated with the item.
  #
  # @type [Hash{Symbol=>Hash}]
  #
  TYPE_CONFIGURATION: Hash[Symbol,symHash]

  # Values for each status column which indicate an unblocked status.
  #
  # @type [Hash{Symbol=>Array<Symbol>}]
  #
  STATUS_READY: Hash[Symbol,symArray]

  # Values for each status column which indicate an "OK" status.
  #
  # @type [Hash{Symbol=>Array<Symbol>}]
  #
  STATUS_VALID: Hash[Symbol,symArray]

  # ManifestItem record columns containing summary status information.
  #
  # @type [Array<Symbol>]
  #
  STATUS_COLUMNS: symArray

  # Status values and labels for the metadata associated with the item.
  #
  # @type [Hash{Symbol=>Hash{Symbol=>String}}]
  #
  STATUS: Hash[Symbol,Hash[Symbol,String]]

  # Used by methods defined in modules to allow the primary argument to be
  # missing/nil when used as a record instance method.
  #
  # @param [*, nil] item
  # @param [Symbol] from
  #
  # @return [*, ManifestItem]
  #
  def default_to_self
    :     (nil item, ?from: Symbol|nil) -> ManifestItem
    | [T] (T   item, ?from: Symbol|nil) -> T
end

# Status values for the remediated file associated with the item.
#
# @see "en.emma.type.manifest_item.file_status"
#
class FileStatus < EnumType
end

# Status values for the metadata associated with the item.
#
# @see "en.emma.type.manifest_item.data_status"
#
class DataStatus < EnumType
end

# Status values for the submission status of the item.
#
# @see "en.emma.type.manifest_item.ready_status"
#
class ReadyStatus < EnumType
end
