module ManifestItem::Assignable
  # :nocov:
  #include Record::Assignable

  #include Record::InstanceMethods

  # Ensure that blanks are allowed and that input values are normalized.
  #
  # @param [Hash, nil] attr
  # @param [Hash, nil] opt
  #
  # @return [Hash{Symbol=>Any}]
  #
  def attribute_options: (symHash attr, ?(symHash|nil) opt) -> symHash

  private

  def self.included: (Module base) -> void
end
