module ManifestItem::Assignable
  include ManifestItem::Config

  include ManifestItem::StatusMethods

  # :nocov:
  #include Record::Assignable

  # Ensure that blanks are allowed and that input values are normalized.
  #
  # @param [Model, Hash, ActionController::Parameters, nil] attr
  # @param [Hash]                                           opt
  #
  # @option opt [Boolean] :invalid    Allow invalid values.
  # @option opt [Symbol]  :meth       Caller (for diagnostics).
  #
  # @return [Hash{Symbol=>*}]
  #
  def normalize_attributes: ((Model|prmHash|nil) attr, **untyped opt) -> symHash

  # A mapping of key comparison value to actual database column name.
  #
  # @return [Hash{String=>Symbol}]
  #
  def key_mapping: () -> Hash[String,Symbol]

  @key_mapping: Hash[String,Symbol]

  # Include the default repository value if not specified.
  #
  # @param [Hash] attr
  #
  # @return [Hash]                    The *attr* argument, possibly modified.
  #
  def default_attributes!: (symHash attr) -> symHash

  private

  def self.included: (Module base) -> void
end
