module ManifestItem::EmmaIdentification
  # :nocov:
  #include Record::EmmaIdentification

  # Column name for the submission ID.
  #
  # @return [nil]
  #
  def sid_column: () -> nil

  private

  def self.included: (Module base) -> void
end
