module ManifestItem::FileData
  # :nocov:
  #include Record::FileData
  # :nocov:

  # Name of the file referenced by :file_data if it does not contain Shrine
  # uploader metadata.
  #
  # @return [String]
  # @return [nil]
  #
  def file_reference: () -> (String | nil)

  # Return the reported size of the file, either as determined by the uploader
  # or initialized by the client-side prior to bulk submission.
  #
  # @return [Integer, nil]
  #
  def file_size: () -> (Integer | nil)

  # Generate a record to express structured file data.
  #
  # @param [Hash, String, nil] data
  # @param [Hash]              opt    Passed to #json_parse
  #
  # @return [Hash{String=>any,nil}]
  #
  # @see config/locales/bulk.en.yml "en.emma.bulk.grid.file"
  #
  def make_file_record: (String|anyHash|nil data, **untyped opt) -> strHash

  private

  def self.included: (Module base) -> void
end
