module ManifestItem::Identification
  # :nocov:
  #include Record::Identification
  # :nocov:

  # Column name for the identifier of the associated user.
  #
  # @return [nil]
  #
  def user_column: () -> nil

  private

  def self.included: (Module base) -> void
end
