# Methods mixed in to record elements related to standard identifiers.
#
module Api::Shared::IdentifierMethods
  include Api::Shared::CommonMethods

  extend ::Api::Shared::IdentifierMethods

  # Limit on the number of individual values to keep for an identifier field.
  #
  # This is necessary because certain IA records have a *absurd* number of
  # :dc_identifier and/or :dc_relation values (2500 in some cases) and there's
  # no benefit in showing (let alone processing) all of those.
  #
  # @type [Integer]
  #
  MAX_IDENTIFIERS: Integer

  # Fields involving standard identifiers.
  #
  # @type [Array<Symbol>]
  #
  RELATION_FIELDS: symArray

  # Fields whose value(s) should be prefixed by standard identifier type.
  #
  # @type [Array<Symbol>]
  #
  IDENTIFIER_FIELDS: symArray

  # Fields whose value(s) should be prefixed by standard identifier type.
  #
  # @return [Array<Symbol>]
  #
  def identifier_fields: () -> symArray

  # Policy for how date multiple date values are handled.
  #
  # (The default is :required because this is what EMMA Unified Ingest
  # requires.)
  #
  # @return [Symbol]                  One of #ARRAY_MODES.
  #
  def id_array_mode: () -> Symbol

  # Produce standard identifiers of the form "(prefix):(value)".
  #
  # @param [Hash, nil] data           Default: *self*
  # @param [Hash]      opt            Passed to #update_field_value!.
  #
  # @option opt [Integer] :limit      Default: #MAX_IDENTIFIERS.
  # @option opt [Symbol]  :mode       Default: `#id_array_mode`.
  #
  # @return [void]
  #
  def normalize_identifier_fields!: (?(symHash|nil) data, **untyped opt) -> void

  # Produce standard identifiers of the form "(prefix):(value)".
  #
  # @param [String, PublicationIdentifier, Array, nil] values
  #
  # @return [Array<String>]
  #
  def normalize_identifiers: ((String | PublicationIdentifier | Array[String|PublicationIdentifier] | nil) values) -> strArray

  # Produce a standard identifier of the form "(prefix):(value)".
  #
  # @param [String, PublicationIdentifier, nil] value
  #
  # @return [String]
  # @return [nil]                     If *value* is not a valid identifier.
  #
  def normalize_identifier: ((String|PublicationIdentifier|nil) value) -> (String | nil)

  # Ensure that "related identifiers" doesn't include values which are already
  # included in the reported identifiers for the item.
  #
  # @param [Hash, nil] data           Default: *self*.
  #
  # @return [void]
  #
  # == Usage Notes
  # Make sure that this is invoked after #normalize_identifier_fields! to
  # ensure that #MAX_IDENTIFIERS has been applied to limit the number of array
  # elements in each field.
  #
  def clean_dc_relation!: (?(symHash|nil) data) -> void

  # The ISBN.
  #
  # @return [String]
  # @return [nil]                     If the value cannot be determined.
  #
  def isbn: () -> (String | nil)

  # Related ISBNs omitting the main ISBN if part of the data array.
  #
  # @return [Array<String>]
  #
  def related_isbns: () -> strArray

  # The main and related ISBNs.
  #
  # @return [Array<String>]
  #
  def all_isbns: () -> strArray
end
