# Methods which support acquiring a record from Internet Archive
# "Printdisabled Unencrypted Ebook API" endpoints.
#
module IaDownloadService::Action::Records
  include IaDownloadService::Common

  # Check for availability of a retrieval from Internet Archive.  If the file
  # requires on-the-fly generation, this will be triggered here.
  #
  # @param [Hash] opt                 Includes :identifier and :type.
  #
  # @return [Hash]
  #
  # @see file:app/assets/javascripts/feature/download.js *ProbeResponse*
  #
  def probe: (**untyped opt) -> symHash

  # Retrieve an item from Internet Archive.
  #
  # This should only be invoked after #probe indicates that the requested
  # content file has already been generated.
  #
  # @param [Hash] opt                 Includes :identifier and :type.
  #
  # @raise [ExecError]                If the retrieval failed.
  #
  # @return [Array(String,String,String)]
  # @return [Array(String,String,nil)]
  #
  def download: (**untyped opt) -> [String, String, (String|nil)]
end
