# XML-specific definition overrides for serialization.
#
# @see Api::Serializer::Xml::Schema
#
module IaDownload::Api::Serializer::Xml::Schema
  include IaDownload::Api::Serializer::Schema

  include Api::Serializer::Xml::Schema
end
