class SubmitChannel::Response < ApplicationCable::Response
  STATUS: Hash[Symbol,String]

  STATUS_INITIAL: String

  STATUS_STEP: String

  STATUS_INTERMEDIATE: String

  STATUS_FINAL: String

  STATUS_ACK: String

  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.data_url_base_path: () -> String

  def initialize: (?untyped values, **untyped opt) -> void

  # Indicate whether this response is part of a simulation.
  #
  def simulation?: () -> bool
end

class SubmitChannel::SubmitResponse < SubmitChannel::Response
  TEMPLATE: symHash

  def self.template: () -> symHash
end

class SubmitChannel::InitialResponse < SubmitChannel::SubmitResponse
  def self.default_status: () -> String
end

class SubmitChannel::StepResponse < SubmitChannel::SubmitResponse
  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.default_status: () -> String
end

class SubmitChannel::FinalResponse < SubmitChannel::StepResponse
  def self.default_status: () -> String
end

class SubmitChannel::ControlResponse < SubmitChannel::Response
  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.default_status: () -> String

  def initialize: (?untyped values, **untyped opt) -> void
end
