# The base class for SubmitJob responses.
#
class SubmitChannel::Response < ApplicationCable::Response
  STATUS: Hash[Symbol,String]

  STATUS_INITIAL: String

  STATUS_STEP: String

  STATUS_INTERMEDIATE: String

  STATUS_FINAL: String

  STATUS_ACK: String

  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.data_url_base_path: () -> String

  def initialize: (?untyped values, **untyped opt) -> void

  # Indicate whether this response is part of a simulation.
  #
  # @note Currently unused.
  #
  def simulation?: () -> bool
end

# The base class for SubmitJob responses indicating submission status.
#
class SubmitChannel::SubmitResponse < SubmitChannel::Response
  TEMPLATE: symHash

  def self.template: () -> symHash
end

# A response sent to indicate that the SubmitJob has started.
#
class SubmitChannel::InitialResponse < SubmitChannel::SubmitResponse
  def self.default_status: () -> String
end

# A response sent to when a SubmitJob submission step has completed.
#
class SubmitChannel::StepResponse < SubmitChannel::SubmitResponse
  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.default_status: () -> String
end

# A response sent to indicate that the SubmitJob has finished.
#
class SubmitChannel::FinalResponse < SubmitChannel::StepResponse
  def self.default_status: () -> String
end

# A response sent to return feedback from a client-issued SubmitJob action.
#
# @note Currently unused.
#
class SubmitChannel::ControlResponse < SubmitChannel::Response
  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.default_status: () -> String

  def initialize: (?untyped values, **untyped opt) -> void
end
