# Overrides for JSON serializers.
#
# @see Lookup::RemoteService::Api::Serializer::Json::Associations
#
module Lookup::WorldCat::Api::Serializer::Json::Associations
  extend ActiveSupport::Concern

  include Lookup::RemoteService::Api::Serializer::Json::Associations

  # -
  # noinspection LongLine
  # +
  module ClassMethods
    include Lookup::WorldCat::Api::Serializer::Json::Schema

    include Lookup::RemoteService::Api::Serializer::Json::Associations::ClassMethods
  end
end
