# Namespace for objects serialized to and de-serialized from the Bookshare API.
#
module Bs
  module Api
  end

  module Message
  end

  module Record
  end

  module Shared
  end
end

module Bs
  include Bs::Api::Common
end
