# Results from a WorldCat Metadata API v.1 SRU search.
#
# Inside an XML '<searchRetrievalResponse>' element.
#
# @see https://developer.api.oclc.org/wcv1#operations-SRU-search-sru
#
# -
# noinspection LongLine
# +
class Lookup::WorldCat::Message::Sru < Lookup::WorldCat::Api::Message
  include Lookup::WorldCat::Shared::CollectionMethods

  include Lookup::WorldCat::Shared::ResponseMethods

  LIST_ELEMENT: Class

  # Simulates the :totalResults field of similar Bookshare API records.
  #
  # @return [Integer]
  #
  # -
  # noinspection RubyInstanceMethodNamingConvention, RubyMismatchedReturnType
  # +
  def totalResults: () -> Integer

  # api_records
  #
  # @return [Array<Lookup::WorldCat::Record::OclcDcs>]
  #
  def api_records: () -> Array[Lookup::WorldCat::Record::OclcDcs]
end
