# Results from a WorldCat Metadata API v.1 SRU search.
#
# Inside an XML '<searchRetrievalResponse>' element.
#
# @see https://developer.api.oclc.org/wcv1#operations-SRU-search-sru
#
class Lookup::WorldCat::Message::Sru < Lookup::WorldCat::Api::Message
  include Lookup::WorldCat::Shared::CollectionMethods

  include Lookup::WorldCat::Shared::ResponseMethods

  LIST_ELEMENT: Class

  # Initialize a new instance and adjust :dc_identifier values.
  #
  # @param [Faraday::Response, Exception Model, Hash, String, nil] src
  # @param [Hash, nil]                                             opt
  #
  def initialize: (?(Faraday::Response|Model|String|anyHash|nil) src, **untyped opt) -> void

  # Overall total number of matching items.
  #
  # @return [Integer]
  #
  def total_results: () -> Integer

  # api_records
  #
  # @return [Array<Lookup::WorldCat::Record::OclcDcs>]
  #
  def api_records: () -> Array[Lookup::WorldCat::Record::OclcDcs]
end
