# Base class for object-specific serializers that process XML data.
#
class Bs::Api::Serializer::Xml < Api::Serializer::Xml
  include Bs::Api::Serializer::Xml::Schema

  include Bs::Api::Serializer::Xml::Associations
end
