# XML-specific definition overrides for serialization.
#
# @see Api::Serializer::Xml::Schema
#
module Search::Api::Serializer::Xml::Schema
  include Search::Api::Serializer::Schema

  include Api::Serializer::Xml::Schema
end
