# Current EMMA Unified Search API version.
#
# @type [String]
#
API_VERSION: String

class Object
  include ApiConcern

  include UploadConcern

  public

  # All ActiveRecord classes that respond to :outdated.
  #
  # @return [Array<Class>]
  #
  def record_classes: (?Class c) -> Array[Class]
end
