# Replacement for the directories hard-wired into the standard :stats task in
# order to report on code in "non-standard" directories and to report on SCSS.
#
# @type [Array<(String,String)>]
#
# === Implementation Notes
# Overrides of Rails::CodeStatistics and Rails::CodeStatisticsCalculator are
# required to report on CSS/SCSS/SASS.
#
EMMA_STATS_DIRECTORIES: Array[[String,String]]
