module Devise
  # Override definitions to be prepended to Devise::Controllers::StoreLocation.
  #
  module Controllers::StoreLocationExt
    # :nocov:
    include Devise::Controllers::StoreLocation

    # Replace "user_return_to" with "app.current_path".
    #
    # @param [Any] resource_or_scope
    #
    def stored_location_key_for: (untyped resource_or_scope) -> untyped
  end
end
