class LookupService::Request
  include LookupService::Common

  include Serializable

  TEMPLATE: symHash

  DEFAULT_QUERY: String

  attr_reader table: symHash

  def initialize:  (lookupArg|nil items) -> void
  def values:      () -> Array[String|PublicationIdentifier]
  def terms:       () -> strArray
  def add_term:    (PublicationIdentifier               value, **untyped opt) -> PublicationIdentifier
                 | (String|Symbol                       value, **untyped opt) -> String
                 | (String|Symbol prefix, ?(String|nil) value, **untyped opt) -> (String | nil)
  def fix_term:    (PublicationIdentifier term, ?(bool|strArray) author) -> PublicationIdentifier
                 | (String                term, ?(bool|strArray) author) -> String
                 | (nil                   term, ?(bool|strArray) author) -> nil
  def request:     () -> symHash
  def identifiers: () -> lookupRequestItems
  def id_types:    () -> symArray
  def to_h:        () -> lookupHash
  def dup:         () -> self
  def deep_dup:    () -> self

  def self.wrap: (untyped item) -> LookupService::Request
end
