# A collection of identifiers transformed into PublicationIdentifier and
# grouped by type.
#
class LookupService::Response < ApplicationJob::Response
  include LookupService::Common

  DEFAULT_SERVICE: String

  # Response data value entries.
  #
  # @type [Hash]
  #
  TEMPLATE: symHash

  # Create a new instance.
  #
  # @param [any, nil] values          LookupService::Response, Hash
  # @param [Hash]     opt
  #
  def initialize: ((LookupService::Response|symHash|nil) items, **untyped opt) -> void

  def self.template: () -> symHash
end
