# Values related to the details of serialization/de-serialization.
#
# @see Api::Schema
#
module Search::Api::Schema
  include Search::Api::Common

  include Api::Schema

  # service_name
  #
  # @return [String]
  #
  def service_name: () -> String

  # A table of schema property enumeration types mapped to literals which are
  # their default values.
  #
  # @return [Hash{Symbol=>String}]
  #
  def enumeration_defaults: () -> Hash[Symbol,String]

  # The enumeration types that may be given as the second argument to
  # #attribute, #has_one, or #has_many definitions.
  #
  # @return [Array<Symbol>]
  #
  def enumeration_types: () -> symArray
end
