# Values related to the details of serialization/de-serialization.
#
module Search::Api::Schema
  include Search::Api::Common

  include Api::Schema

  # The class name of the related service for logging.
  #
  # @return [String]
  #
  def service_name: () -> String
end
