class Manifest < ApplicationRecord
  include Model

  include Record

  include Record::Assignable

  include Record::Authorizable

  include Record::Describable

  include Record::Searchable

  include Record::Testing

  include Record::Debugging

  include Manifest::Config

  include Manifest::EmmaIdentification

  include Manifest::ItemMethods

  include Manifest::Searchable

  # :nocov:
  #extend Record::Describable::ClassMethods

  def org_id: () -> (Integer | nil)

  def user_id: () -> (Integer | nil)

  # A textual label for the record instance.
  #
  # @param [Manifest, nil] item       Default: self.
  #
  # @return [String, nil]
  #
  def label: (?(Manifest|nil) item) -> (String | nil)

  # Create a new instance.
  #
  # @param [Manifest, Hash, nil] attr   Passed to #assign_attributes via super.
  #
  # @note - for dev traceability
  #
  def initialize: (?(Manifest|prmHash|nil) attr) ?{ () -> untyped } -> void

  # Mark associated ManifestItem records as saved while renumbering their rows.
  #
  # @param [DateTime, nil] timestamp  Default: time now.
  # @param [Hash]          attr       Manifest field values to update.
  #
  # @return [self]
  #
  def save_changes!: (?(DateTime|nil) timestamp, **untyped attr) -> self

  # Back out of provisional ManifestItem changes.
  #
  # @param [Hash] attr                Manifest field values to update.
  #
  # @return [self]
  #
  def cancel_changes!: (**untyped attr) -> self

  # Generate a default Manifest title name.
  #
  # @return [String]
  #
  def self.default_name: () -> String
end
