class Org < ApplicationRecord
  include ActiveRecord::AttributeMethods::Dirty

  include Model

  include Record

  include Record::Assignable

  include Record::Searchable

  include Record::Sortable

  include Record::Testing

  include Record::Debugging

  include Org::Config

  include Org::Assignable

  # :nocov:
  #include Record::Rendering
  #extend  Record::Rendering

  # A short textual representation for the record instance.
  #
  # @param [Org, nil] item            Default: self.
  #
  # @return [String, nil]
  #
  def abbrev: (?(Org|nil) item) -> (String | nil)

  # A textual label for the record instance.
  #
  # @param [Org, nil] item  Default: self.
  #
  # @return [String, nil]
  #
  def label: (?(Org|nil) item) -> (String | nil)

  # Create a new instance.
  #
  # @param [Org, Hash, nil] attr   Passed to #assign_attributes via super.
  #
  # @note - for dev traceability
  #
  def initialize: (?(Org|prmHash|nil) attr) ?{ () -> untyped } -> void

  def org_id: () -> (Integer | nil)

  def org_key: () -> Symbol

  def self.org_key: () -> Symbol

  def uid: (?untyped item) -> (Integer | nil)

  def self.for_user: (?untyped user, **untyped opt) -> ActiveRecord::Relation

  # The 'users' table IDs of users associated with this organization.
  #
  # @return [Array<Integer>]
  #
  def user_ids: () -> Array[Integer]

  # The account names of users associated with this organization.
  #
  # @return [Array<String>]
  #
  # @note Currently unused.
  #
  def user_accounts: () -> strArray

  # The number of EMMA entries submitted by users of this organization.
  #
  # @return [Integer]
  #
  def upload_count: () -> Integer

  # The number of bulk manifests associated with users of this organization.
  #
  # @return [Integer]
  #
  def manifest_count: () -> Integer

  # A relation for all organization contact users.
  #
  # @return [ActiveRecord::Relation<User>]
  #
  def contacts: () -> ActiveRecord::Relation

  # A relation for all organization managers.
  #
  # @return [ActiveRecord::Relation<User>]
  #
  def managers: () -> ActiveRecord::Relation

  # Return the common name of *org*.
  #
  # @param [any, nil] org             User, String, Symbol, Integer; def: self
  #
  # @return [String, nil]
  #
  def org_name: (?untyped org) -> (String | nil)

  # Return the common name of *org*.
  #
  # @note This method assumes that if *org* is a String or Symbol it already
  #   represents an organization name unless it resolves to an org ID.
  #
  # @param [any, nil] org             User, String, Symbol, Integer
  #
  # @return [String, nil]
  #
  def self.org_name: (untyped org) -> (String | nil)

  # Ensure that :long_name is present and that :short_name is valid or can be
  # derived from :long_name.
  #
  # @param [Hash] attr
  # @param [Hash] opt           To #normalize_long_name, #normalize_short_name
  #
  # @return [Hash]              The possibly-modified *attr*.
  #
  def self.normalize_names!: (symHash attr, **untyped opt) -> symHash

  # Normalize a :long_name value.
  #
  # @param [any, nil]       value
  # @param [Boolean, Class] fatal     If *true* defaults to RuntimeError.
  #
  # @raise [Record::SubmitError]      If *value* is not acceptable for *field*.
  #
  # @return [String]                  Normalized value.
  # @return [nil]                     If missing and not fatal.
  #
  def self.normalize_long_name: (untyped value, ?fatal: bool|Class, **untyped _ignored) -> (String | nil)

  # Normalize a :short_name value.
  #
  # @param [any, nil]       value
  # @param [Boolean, Class] fatal     If *true* defaults to RuntimeError.
  #
  # @raise [Record::SubmitError]      If *value* is not acceptable for *field*.
  #
  # @return [String]                  Normalized value.
  # @return [nil]                     If missing and not fatal.
  #
  def self.normalize_short_name: (untyped value, ?fatal: bool|Class, **untyped _ignored) -> (String | nil)

  # This is the (non-persisted) organization associated with ID 0.
  #
  # User records use :org_id == 0 to indicate that the user is explicitly not
  # associated with any member organization, whereas a NIL field value
  # indicates that the user's organization has not yet been determined.
  #
  # @return [Org]
  #
  def self.none: () -> Org

  # Return the Org instance indicated by the argument.
  #
  # @param [any, nil] v               Model, Hash, String, Integer
  #
  # @return [Org, nil]                A fresh record unless *v* is an Org.
  #
  def self.instance_for
    : (Org     v) -> Org
    | (untyped v) -> (Org | nil)

  # If organization status transitions to :active or :inactive, transition all
  # organization users to the same status.
  #
  # @return [void]
  #
  # @see ActiveRecord::AttributeMethods::Dirty
  #
  def update_users: () -> void
end
