# Model for a periodical.
#
class Periodical < ApplicationRecord
  include Model

  include Record

  include Record::Authorizable

  # Indicate whether the periodical includes the indicated artifact.
  #
  # @param [Artifact, String, *] item
  #
  def include?: ((Artifact|String|untyped) item) -> bool

  # Indicate whether the periodical includes the indicated artifact.
  #
  # @param [Artifact, String, *] item
  #
  def has_artifact?: ((Artifact|String|untyped) item) -> bool
end
