class SearchPaginator < Paginator
  # Analyze the *list* object to generate the path for the next page of
  # results.
  #
  # @param [Search::Message::SearchTitleList, Array<Search::Record::MetadataRecord>, nil] list
  # @param [Hash, nil] url_params     Current request parameters.
  #
  # @return [String]                  Path to generate next page of results.
  # @return [nil]                     If there is no next page.
  #
  def next_page_path: (?list: Search::Message::SearchTitleList|Array[Search::Record::MetadataRecord]|nil, **untyped url_params) -> (String | nil)
end
