# Model for a title (i.e., a catalog entry).
#
class Title < ApplicationRecord
  include Model

  include Record

  include Record::Authorizable

  # Indicate whether the title includes the indicated artifact.
  #
  # @param [Artifact, String, *] item
  #
  def include?: (untyped item) -> bool

  # Indicate whether the title includes the indicated artifact.
  #
  # @param [Artifact, String, *] item
  #
  def has_artifact?: (untyped item) -> bool
end
