# Controller support methods for administration.
#
module AdminConcern
  extend ActiveSupport::Concern

  include ApplicationHelper

  # Administrative pages (except for :index).
  #
  # @type [Array<Symbol>]
  #
  ADMIN_PAGES: symArray

  private

  THIS_MODULE: Module
end
