# Controller support methods for access to the AWS S3 API service.
#
module AwsConcern
  extend ActiveSupport::Concern

  include ParamsHelper

  include ApiConcern

  REPOSITORY_PARAMS: symArray

  DEPLOYMENT_PARAMS: symArray

  NON_AWS_PARAMS: symArray

  # Access the AWS S3 API service.
  #
  # @return [AwsS3Service]
  #
  def aws_api: () -> AwsS3Service

  # Get a list of the partner repositories indicated.
  #
  # - If :emma is included it will be moved to the end of the list.
  # - If :ace is included it is replaced with :internetArchive since ACE items
  #   are transferred via Internet Archive through the 'ia' bucket.
  #
  # @param [String, Symbol, Array, nil] default   Default: '*'
  # @param [Hash]                       prm       Passed to #params_values.
  #
  # @return [Array<Symbol>]
  #
  def get_aws_repositories: (?default: String|Symbol|Array[String|Symbol]|nil, **untyped prm) -> symArray

  # Get a list of deployments indicated.
  #
  # @param [String, Symbol, Array, nil] default   Default: '*'
  # @param [Hash]                       prm       Passed to #params_values.
  #
  # @return [Array<Symbol>]
  #
  def get_aws_deployments: (?default: String|Symbol|Array[String|Symbol]|nil, **untyped prm) -> symArray

  # Get a list of values from one of the indicated parameter keys.
  #
  # @param [Hash, nil]     opt        Default: `#url_parameters`.
  # @param [Array<Symbol>] keys
  #
  # @return [Array<String>]
  #
  def params_values: (anyHash opt, *Symbol keys) -> strArray

  # Extract AWS S3 related parameters.
  #
  # @param [Hash, nil] opt            Default: `#url_parameters`.
  #
  # @return [Hash]
  #
  def aws_params: (?(anyHash|nil) opt) -> symHash

  # Get the name of the indicated S3 bucket.
  #
  # @param [Symbol, String]      repository
  # @param [Symbol, String, nil] deployment   Def: `#aws_deployment`.
  # @param [AwsS3Service, nil]   service      Def: `AwsS3Service.instance`.
  #
  # @raise [ApiService::RequestError]         If bucket is invalid.
  #
  # @return [String]
  #
  def repo_bucket: ((Symbol|String) repository, ?(Symbol|String|nil) deployment, ?service: AwsS3Service|nil, **untyped _ignored) -> String

  # Get the indicated S3 bucket.
  #
  # @param [Symbol, String]      repository
  # @param [Symbol, String, nil] deployment   Def: `#aws_deployment`.
  # @param [Hash]   opt                       Passed to #get_s3_bucket
  #
  # @option opt [AwsS3Service] :service       Default: `AwsS3Service.instance`
  #
  # @raise [ApiService::RequestError]         If bucket is invalid.
  #
  # @return [Aws::S3::Bucket]
  #
  # @note Currently unused.
  #
  def get_repo_bucket: ((Symbol|String) repository, ?(Symbol|String|nil) deployment, **untyped opt) -> Aws::S3::Bucket

  # Get all files (object keys) associated with the indicated S3 bucket.
  #
  # @param [Symbol, String]      repository
  # @param [Symbol, String, nil] deployment   Def: `#aws_deployment`.
  # @param [Hash]   opt                       Passed to #get_s3_objects
  #
  # @option opt [AwsS3Service] :service       Default: `AwsS3Service.instance`
  #
  # @raise [ApiService::RequestError]         If bucket is invalid.
  #
  # @return [Array<Aws::S3::Object>]
  #
  # @note Currently unused.
  #
  def get_repo_objects: ((Symbol|String) repository, ?(Symbol|String|nil) deployment, **untyped opt) -> Array[Aws::S3::Object]

  # Get a table of all AWS S3 buckets.
  #
  # @param [Hash] opt
  #
  # @option opt [AwsS3Service, nil] :service  Default: `AwsS3Service.instance`
  #
  # @raise [ApiService::RequestError]         If bucket is invalid.
  #
  # @return [Hash{String=>Aws::S3::Bucket}]
  #
  # @note Currently unused.
  #
  def get_s3_bucket_table: (**untyped opt) -> Hash[String,Aws::S3::Bucket]

  # Get a table of all AWS S3 buckets and their files (object keys).
  #
  # @param [Hash] opt
  #
  # @option opt [AwsS3Service, nil] :service  Default: `AwsS3Service.instance`
  #
  # @raise [ApiService::RequestError]         If bucket is invalid.
  #
  # @return [Hash{String=>Array<Aws::S3::Object>}]
  #
  def get_s3_object_table: (**untyped opt) -> Hash[String,Array[Aws::S3::Object]]

  # Get the named AWS S3 bucket.
  #
  # @param [String] name
  # @param [Hash]   opt                       Passed to #s3_bucket except for:
  #
  # @option opt [AwsS3Service, nil] :service  Default: `AwsS3Service.instance`
  #
  # @return [Aws::S3::Bucket]
  #
  # @note Currently used only by unused methods.
  #
  def get_s3_bucket: (String name, **untyped opt) -> Aws::S3::Bucket

  # List files (object keys) in `*bucket*`.
  #
  # @param [String, Aws::S3::Bucket] bucket
  # @param [Hash]   opt                       Passed to #s3_bucket except for:
  #
  # @option opt [AwsS3Service, nil] :service  Default: `AwsS3Service.instance`
  #
  # @return [Array<Aws::S3::Object>]
  #
  def get_s3_objects: ((String|Aws::S3::Bucket) bucket, **untyped opt) -> Array[Aws::S3::Object]

  # The URL to the associated object in AWS S3.
  #
  # @param [Upload, Record::Uploadable, Aws::S3::Object] item
  # @param [Hash]                                        opt
  #
  # @return [String, nil]
  #
  def get_s3_public_url: ((Upload|Record::Uploadable|Aws::S3::Object) item, **untyped opt) -> (String | nil)

  private

  THIS_MODULE: Module
end
