# Controller support methods for access to the Bookshare API service.
#
module BookshareConcern
  extend ActiveSupport::Concern

  include ApiConcern

  attr_reader bookshare_id: String | nil
  attr_reader series_id:    String | nil
  attr_reader edition_id:   String | nil
  attr_reader format:       String | nil
  attr_reader id:           String | nil
  attr_reader member:       String | nil
  attr_reader url:          String | nil

  # Access the Bookshare API service.
  #
  # @return [BookshareService]
  #
  def bs_api: () -> BookshareService

  # Return a member associated with the given user.
  #
  # @param [User, String] for_user    Default: `#current_user`.
  # @param [String]       _name       Member name (future).
  #
  # @return [String]
  # @return [nil]
  #
  def get_member: (?(User|String|nil) for_user, ?(String|nil) _name) -> (String | nil)

  # Extract the best-match URL parameter which represents an item identifier.
  #
  # @return [String]                  Value of `params[:id]`.
  # @return [nil]                     No :id, :bookshareId found.
  #
  def set_bookshare_id: () -> (String | nil)

  # Extract the URL parameter which specifies a journal/periodical series.
  #
  # @return [String]                  Value of `params[:series]`.
  # @return [nil]                     No :series, :seriesId found.
  #
  def set_series_id: () -> (String | nil)

  # Extract the URL parameter which specifies a journal/periodical edition.
  #
  # @return [String]                  Value of `params[:id]`.
  # @return [nil]                     No :id, :edition, :editionId found.
  #
  def set_edition_id: () -> (String | nil)

  # Extract the best-match URL parameter which represents an item format.
  #
  # @return [String]                  Value of `params[:fmt]`.
  # @return [nil]                     No :fmt found.
  #
  def set_format: () -> (String | nil)

  # Extract the URL parameter which specifies a reading list.
  #
  # @return [String]                  Value of `params[:id]`.
  # @return [nil]                     No :id, :readingListId found.
  #
  def set_reading_list_id: () -> (String | nil)

  # Extract the URL parameter which indicates a Bookshare member.
  #
  # @return [String]                  Value of `params[:member]`.
  # @return [nil]                     No :member, :forUser found.
  #
  def set_member: () -> (String | nil)

  # Extract the URL parameter which indicates a remote URL path.
  #
  # @return [String]                  Value of `params[:url]`.
  # @return [nil]                     No :url found.
  #
  def set_url: () -> (String | nil)

  private

  THIS_MODULE: Module
end
