# Controller support methods for downloads from EMMA collections originating
# from BiblioVault.
#
# Currently, there is only one collection (:bibliovault_ump) but future
# collections will use the same logic.
#
module BvDownloadConcern
  extend ActiveSupport::Concern

  include ApiConcern

  # Access the UVALIB BiblioVault collections service.
  #
  # @return [BvDownloadService]
  #
  def bv_download_api: () -> BvDownloadService

  # Options for ActionController::DataStreaming#send_data
  #
  # @type [Array<Symbol>]
  #
  SEND_DATA_OPT: symArray

  # Send a copy of an item from a BiblioVault collection.
  #
  # @param [String] url               Original S3 item URL.
  # @param [Hash]   opt               Passed to BvDownloadService#api_download.
  #
  # @return [void]                    Results written into `response`.
  #
  def bv_download_retrieval: (url: String, **untyped opt) -> (nil | untyped)

  private

  THIS_MODULE: Module

  include RepositoryHelper
end
