# Controller support methods for dynamic specification of service endpoints.
#
module EngineConcern
  extend ActiveSupport::Concern

  include ParamsHelper

  #include ActionController::Redirecting

  # The service identified by the given value.
  #
  # @param [String, Symbol, Class<ApiService>] service
  #
  # @return [String]
  #
  def service_name: ((String|Symbol|Class) service) -> String

  # The session key associated with the given service.
  #
  # @param [String, Symbol, Class<ApiService>] service
  #
  # @return [String]
  #
  def service_session_key: ((String|Symbol|Class) service) -> String

  # The URL of the user-selected service engine.
  #
  # @param [String, Symbol, Class<ApiService>] service
  #
  # @return [String, nil]             If different than the default engine.
  #
  def requested_engine: ((String|Symbol|Class) service) -> (String | nil)

  # Recall the user-selected service engine name or endpoint.
  #
  # @param [String, Symbol, Class<ApiService>] service
  #
  # @return [String, nil]
  #
  def get_session_engine: ((String|Symbol|Class) service) -> (String | nil)

  # Remember (or forget) the user-selected service engine name or endpoint.
  #
  # @param [String, Symbol, Class<ApiService>] service
  # @param [String, nil]                       new_value
  #
  # @return [String, nil]
  #
  def set_session_engine: ((String|Symbol|Class) service, (String|nil) new_value) -> (String | nil)

  # Process the URL parameter for setting the endpoint for the given service.
  #
  # The engine may be specified by deployment, e.g. "&engine=staging", or by
  # URL (if that URL matches or derives from a `service.engines` value).
  # If this resolves to the default engine then session['app.*.engine'] is
  # deleted; otherwise it will be set to a key of `service.engines` or to an
  # explicit URL if necessary.
  #
  # If no (valid) :engine parameter was supplied, this method evaluates the
  # current value of session['app.*.engine'], and will delete it if appropriate
  # (but without redirecting).
  #
  # @param [Class<ApiService>] service
  #
  # @return [any]
  # @return [nil]                     If not redirecting
  #
  def set_engine_callback: (Class service) -> (untyped | nil)

  private

  THIS_MODULE: Module
end
