# Controller support methods for creation of flash messages.
#
module FlashConcern
  extend ActiveSupport::Concern

  include FlashHelper

  # flash_link
  #
  # @param [String]       label
  # @param [String, Hash] path
  # @param [Hash]         opt
  #
  # @option opt [String] :tooltip   Alias for :title.
  # @option opt [String] :tip       Alias for :title.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def flash_link: (String label, String|anyHash path, **untyped opt) -> ActiveSupport::SafeBuffer

  private

  THIS_MODULE: Module
end
