# Support methods for the "/help" controller.
#
module HelpConcern
  extend ActiveSupport::Concern

  include HelpHelper

  attr_reader topic: Symbol | nil

  # get_help_entry
  #
  # @param [Symbol,nil] topic
  #
  # @return [Hash{Symbol=>Any}]
  #
  def get_help_entry: ((Symbol|nil) topic) -> symHash

  # Extract the URL parameter which specifies a help topic.
  #
  # @return [Symbol]                  Value of `params[:id]`.
  # @return [nil]                     No :id, :topic found.
  #
  def set_help_topic: () -> (Symbol | nil)

  private

  THIS_MODULE: Module
end
