# Controller support methods for access to the EMMA Unified Ingest service.
#
module IngestConcern
  extend ActiveSupport::Concern

  include ApiConcern

  include EngineConcern

  # Access the EMMA Unified Ingest service.
  #
  # @return [IngestService]
  #
  def ingest_api: () -> IngestService

  # Process the URL parameter for setting the ingest engine URL.
  #
  # @return [void]
  #
  def set_ingest_engine: () -> void

  private

  THIS_MODULE: Module
end
