# Support methods for the "/manifest_item" controller.
#
# @!method model_options
#   @return [ManifestItem::Options]
#
# @!method paginator
#   @return [ManifestItem::Paginator]
#
module ManifestItemConcern
  extend ActiveSupport::Concern

  include Emma::Common

  include Emma::Json

  include ImportConcern

  include SerializationConcern

  include ModelConcern

  # The manifest identified in URL parameters.
  #
  # @return [String, nil]
  #
  def manifest_id: () -> (String | nil)

  @manifest_id: String | nil

  # Extract POST parameters and data for bulk operations.
  #
  # @raise [RuntimeError]             If both :src and :data are present.
  #
  # @return [Hash{Symbol=>*}]
  #
  # @see ImportConcern#fetch_data
  #
  def manifest_item_bulk_post_params: () -> symHash

  # Get URL parameters relevant to the current operation.
  #
  # @return [Hash{Symbol=>*}]
  #
  def current_get_params: () -> symHash

  # Extract POST parameters that are usable for creating/updating a
  # ManifestItem instance.
  #
  # @return [Hash{Symbol=>*}]
  #
  def current_post_params: () -> symHash

  # Locate and filter ManifestItem records.
  #
  # @param [Array<String,Array>] items
  # @param [Array<Symbol>]       filters
  # @param [Hash]                opt
  #
  # @return [Paginator::Result]
  #
  def find_or_match_records: (*(String|anyArray) items, ?filters: symArray, **untyped opt) -> Paginator::Result

  # The related Manifest identified in URL parameters.
  #
  # @param [Hash] prm
  #
  # @return [Integer, nil]
  #
  def extract_manifest_id: (symHash prm) -> (Integer | nil)

  # Interpret data as JSON.
  #
  # @param [String, ActionDispatch::Request, nil] data
  #
  # @return [Array<Hash{Symbol=>*}>, nil]
  #
  def from_json: (String|ActionDispatch::Request|nil data) -> (Array[symHash] | nil)

  # Interpret data as CSV.
  #
  # @param [String, ActionDispatch::Request, nil] data
  #
  # @return [Array<Hash{Symbol=>*}>, nil]
  #
  def from_csv: (String|ActionDispatch::Request|nil data) -> (Array[symHash] | nil)

  # Transform import data into ManifestItem field values.
  #
  # @param [Hash{Symbol=>*}] item
  #
  # @return [Hash{Symbol=>*}]
  #
  def import_transform!: (symHash item) -> symHash

  # Transform ManifestItem field values for export.
  #
  # @param [Hash{Symbol=>*}] item
  #
  # @return [Hash{Symbol=>*}]
  #
  def export_transform!: (symHash item) -> symHash

  # Restoration of ManifestItem fields on import.
  #
  # @type [Hash{Symbol=>Symbol}]
  #
  IMPORT_FIELD: Hash[Symbol,Symbol]

  # Transform received data to allow some flexibility in the naming of import
  # columns by mapping into the expected field names.
  #
  # @param [Hash{Symbol=>*}] item
  #
  # @return [Hash{Symbol=>*}]
  #
  def normalize_import_name!: (symHash item) -> symHash

  # Transformation of ManifestItem fields on export.
  #
  # @type [Hash{Symbol=>Symbol}]
  #
  EXPORT_FIELD: Hash[Symbol,Symbol]

  # Transform potentially ambiguous field names into ones that are not likely
  # to clash if exported data is intermingled with fields from other systems
  # and then re-imported.
  #
  # @param [Hash{Symbol=>*}] item
  #
  # @return [Hash{Symbol=>*}]
  #
  def normalize_export_name!: (symHash item) -> symHash

  # Create and persist a new ManifestItem.
  #
  # @param [Hash, nil]       prm        Field values (def: `#current_params`).
  # @param [Boolean, String] force_id   If *true*, allow setting of :id.
  # @param [Boolean]         fatal      If *false*, use #save not #save!.
  #
  # @return [ManifestItem]              A new ManifestItem instance.
  #
  def create_record: (?symHash? prm, ?force_id: bool|String, ?fatal: bool, **untyped _ignored) -> ManifestItem

  # Retrieve the indicated ManifestItem for the '/edit' model form.
  #
  # @param [ManifestItem, *] item     Def.: record for ModelConcern#identifier.
  # @param [Hash]            opt      Passed to super
  #
  # @raise [Record::SubmitError]      Record could not be found.
  #
  # @return [ManifestItem, nil]       An existing persisted ManifestItem.
  #
  def edit_record: (?(String|Integer|ManifestItem|symHash|nil) item, **untyped opt) -> (ManifestItem | nil)

  # Update the indicated ManifestItem.
  #
  # @param [*]       item             Def.: record for ModelConcern#identifier.
  # @param [Boolean] fatal            If *false* use #update not #update!.
  # @param [Hash]    prm              Field values except #UPDATE_STATUS_OPTS
  #
  # @raise [Record::NotFound]               Record could not be found.
  # @raise [ActiveRecord::RecordInvalid]    Record update failed.
  # @raise [ActiveRecord::RecordNotSaved]   Record update halted.
  #
  # @return [ManifestItem, nil]         The updated ManifestItem instance.
  #
  def update_record: (?(String|Integer|Model|symHash|nil) item, ?fatal: bool, **untyped prm) -> (ManifestItem | nil)

  # Retrieve the indicated record(s) for the '/delete' page.
  #
  # @param [*]    items               To #search_records
  # @param [Hash] prm                 Default: `#current_params`
  #
  # @raise [RangeError]               If :page is not valid.
  #
  # @return [Paginator::Result]
  #
  def delete_records: (?(String|Symbol|Integer|Model|Array[String|Symbol|Integer|Model]|nil) items, **untyped prm) -> Paginator::Result

  RECORD_KEYS: symArray

  NON_DATA_KEYS: symArray

  NON_EDIT_KEYS: symArray

  # Set :editing state (along with any other fields if they are provided).
  #
  # @param [ManifestItem, nil] item   Def.: record for ModelConcern#identifier.
  # @param [Boolean, nil]      fatal  Passed to database method if present.
  # @param [Symbol, nil]       meth   Caller (for diagnostics).
  # @param [Hash]              attr   Field values.
  #
  # @raise [Record::NotFound]               Record could not be found.
  # @raise [ActiveRecord::RecordInvalid]    Record update failed.
  # @raise [ActiveRecord::RecordNotSaved]   Record update halted.
  #
  # @return [ManifestItem]
  # @return [nil]                     Only if *fatal* == *false*.
  #
  def start_editing: (?(ManifestItem|nil) item, ?fatal: bool|nil, ?meth: Symbol|nil, **untyped attr) -> (ManifestItem | nil)

  # Update with provided fields (if any) and clear :editing state.
  #
  # @param [ManifestItem, nil] item   Def.: record for ModelConcern#identifier.
  # @param [Symbol, nil]       meth   Caller (for diagnostics).
  # @param [Hash]              attr   Field values.
  #
  # @raise [Record::NotFound]               Record could not be found.
  # @raise [ActiveRecord::RecordInvalid]    Record update failed.
  # @raise [ActiveRecord::RecordNotSaved]   Record update halted.
  #
  # @return [Hash]
  #
  # @see file:controllers/manifest-edit.js *parseFinishEditResponse*
  #
  def finish_editing: (?(ManifestItem|nil) item, ?meth: Symbol|nil, **untyped attr) -> { :items => Hash[Integer,symHash], :pending => Hash[Integer,symHash]|nil, :problems => symHash }

  # Update with provided fields (if any) and clear :editing state.
  #
  # @param [ManifestItem, nil] item   Def.: record for ModelConcern#identifier.
  # @param [Hash]              attr   Field values.
  #
  # @raise [Record::NotFound]               Record could not be found.
  # @raise [ActiveRecord::RecordInvalid]    Record update failed.
  # @raise [ActiveRecord::RecordNotSaved]   Record update halted.
  #
  # @return [Hash]
  #
  # @see file:javascripts/controllers/manifest-edit.js *postRowUpdate*
  #
  def editing_update: (?(ManifestItem|nil) item, **untyped attr) -> { :items => Hash[Integer,symHash], :pending => Hash[Integer,symHash]|nil, :problems => symHash }

  # Upload a file to the AWS S3 Shrine :cache and update record :file_data with
  # the response.
  #
  # The Shrine response is augmented with an :emma_data entry containing the
  # record fields -- including :id since this may be the first "edit" of the
  # grid item and thus the first opportunity for the client to learn what
  # database entry is associated with that item.
  #
  # @param [ManifestItem, nil] item         Def.: ModelConcern#identifier.
  # @param [Boolean]           update_time  If *false* update :file_data only.
  # @param [Hash, nil]         env          Def.: `request.env`.
  # @param [Symbol, nil]       meth         Caller (for diagnostics).
  # @param [Hash]              opt          Field values.
  #
  # @return [Array<(Integer, Hash{String=>*}, Array<String>)>]
  #
  # @note If update_time is *false* the associated record must already exist.
  #
  def upload_file: (?(ManifestItem|nil) item, update_time: bool, ?env: anyHash|nil, ?meth: Symbol|nil, **untyped opt) -> httpResult

  # A relation for all rows of the indicated Manifest ordered by row.
  #
  # @param [String, nil] manifest_id
  # @param [Hash]        opt
  #
  # @option opt [String]       :manifest_id
  # @option opt [String, Hash] :manifest
  #
  # @return [ActiveRecord::Relation<ManifestItem>]
  #
  def all_manifest_items: (?(String|nil) manifest_id, **untyped opt) -> ActiveRecord::Relation

  # bulk_new_manifest_items
  #
  # @return [*]
  #
  def bulk_new_manifest_items: () -> untyped

  # bulk_create_manifest_items
  #
  # @param [Array<Symbol>] returning  Returned result columns.
  #
  # @raise [RuntimeError]             If both :src and :data are present.
  # @raise [Record::SubmitError]      If there were failure(s).
  #
  # @return [Array<Hash>]             Created rows.
  #
  def bulk_create_manifest_items: (?returning: symArray) -> Array[symHash]

  # bulk_edit_manifest_items
  #
  # @return [*]
  #
  def bulk_edit_manifest_items: () -> untyped

  # bulk_update_manifest_items
  #
  # @param [Array<Symbol>] returning  Returned result columns.
  #
  # @raise [RuntimeError]             If both :src and :data are present.
  # @raise [Record::SubmitError]      If there were failure(s).
  #
  # @return [Array<Hash>]             Modified rows.
  #
  def bulk_update_manifest_items: (?returning: symArray) -> Array[symHash]

  # bulk_delete_manifest_items
  #
  # @return [*]
  #
  def bulk_delete_manifest_items: () -> untyped

  # bulk_destroy_manifest_items
  #
  # This marks items for deletion unless `params[:commit]` is true.
  #
  # @raise [RuntimeError]             If both :src and :data are present.
  # @raise [Record::SubmitError]      If there were failure(s).
  #
  # @return [Array<Integer>]          Affected rows.
  #
  def bulk_destroy_manifest_items: () -> Array[Integer]

  # bulk_fields_manifest_items
  #
  # @raise [Record::SubmitError]      If there were failure(s).
  #
  # @return [Array<Hash>]             Modified items.
  #
  def bulk_fields_manifest_items: () -> Array[symHash]

  # Data for one or more manifest items from parameters.
  #
  # @return [Array<Hash>]
  #
  def bulk_item_data: () -> Array[symHash]

  # Transform a :returning result into an array of data hashes.
  #
  # @param [ActiveRecord::Result] result
  #
  # @return [Array<Hash{Symbol=>*}>]
  #
  def bulk_returning: (ActiveRecord::Result result) -> Array[symHash]

  # Generate a response to a POST.
  #
  # @param [Symbol, Integer, Exception, nil] status
  # @param [*]                               item
  # @param [Hash]                            opt
  #
  # @return [void]
  #
  def post_response
    : ((Symbol|Integer|nil) status, ?untyped   item, **untyped opt) -> void
    | (                              Exception item, **untyped opt) -> void

  # Create an Options instance from the current parameters.
  #
  # @return [ManifestItem::Options]
  #
  def get_model_options: () -> ManifestItem::Options

  # Create a Paginator for the current controller action.
  #
  # @param [Class<Paginator>] paginator  Paginator class.
  # @param [Hash]             opt        Passed to super.
  #
  # @return [ManifestItem::Paginator]
  #
  def pagination_setup: (?paginator: Class, **untyped opt) -> ManifestItem::Paginator

  # @private
  RESPONSE_OUTER: Symbol

  # Response values for de-serializing the index page to JSON or XML.
  #
  # @param [*]    list                Default: `paginator.page_items`
  # @param [Hash]  opt
  #
  # @return [Hash{Symbol=>Hash}]
  #
  def index_values: (?untyped list, **untyped opt) -> Hash[Symbol,symHash]

  # Response values for de-serializing the show page to JSON or XML.
  #
  # @param [Model, Hash, *] item
  # @param [Hash]           opt
  #
  # @return [Hash{Symbol=>*}]
  #
  def show_values: (?untyped item, **untyped opt) -> symHash

  private

  THIS_MODULE: Module
end
