# Support methods for controllers that implement CRUD semantics.
#
# === Usage Notes
# This module is expected to be included by a concern which selective overrides
# these methods to accommodate model-specific variations to this base logic.
#
module ModelConcern
  extend ActiveSupport::Concern

  include ExceptionHelper

  include FlashHelper

  include IdentityHelper

  include ParamsHelper

  include OptionsConcern

  include PaginationConcern

  include ParamsConcern

  include ResponseConcern

  def model_class: () -> Class

  def model_key: () -> Symbol

  def model_id_key: () -> Symbol

  def search_records_keys: () -> symArray

  def search_only_keys: () -> symArray

  def find_or_match_keys: (*Symbol added) -> symArray

  # The model record identified in URL parameters either as :selected or :id.
  #
  # @return [Integer, String, nil]
  #
  def identifier: () -> (Integer | String | nil)

  @identifier: Integer | String | nil

  # The database ID of a model record identified in URL parameters.
  #
  # @return [Integer, nil]
  #
  def db_id: () -> (Integer | nil)

  @db_id: Integer?

  # Only allow a list of trusted parameters through.
  #
  # @return [Hash]
  #
  def current_params: () ?{ (symHash) -> void } -> symHash

  @current_params: symHash

  # Get URL parameters relevant to the current operation.
  #
  # @return [Hash]
  #
  def current_get_params: () ?{ (symHash) -> void } -> symHash

  # Extract POST parameters that are usable for creating/updating a model
  # record instance.
  #
  # @return [Hash]
  #
  def current_post_params: () ?{ (symHash) -> void } -> symHash

  # model_request_params
  #
  # @param [any, nil]  item           Model, Hash
  # @param [Hash, nil] prm
  #
  # @return [Array<(Model, Hash)>]
  # @return [Array<(*,     Hash)>]
  #
  def model_request_params
    :     (Model item, ?(symHash|nil) prm) -> [Model, symHash]
    | [T] (T     item, ?(symHash|nil) prm) -> [T,     symHash]
    |     (              symHash      prm) -> [nil,   symHash]

  # extract_identifier
  #
  # @param [Hash] prm
  #
  # @return [Integer, String, nil]
  #
  def extract_identifier: (symHash prm) -> (Integer | String | nil)

  # If a user was not already specified, add the current user to the given
  # parameters.
  #
  # @param [Hash]      prm
  # @param [User, nil] user           Default: #current_user
  #
  # @return [Hash]
  #
  def current_user!: (symHash prm, ?(User|nil) user) -> symHash

  # If an organization was not already specified, add the organization of the
  # current user to the given parameters.
  #
  # @param [Hash]     prm
  # @param [Org, nil] org             Default: #current_org
  #
  # @return [Hash]
  #
  def current_org!: (symHash prm, ?(Org|nil) org) -> symHash

  # Generate arguments to ActiveRecord#order from *val*.
  #
  # @param [Hash] prm
  # @param [Hash] opt                 Passed to #normalize_sort_order.
  #
  # @return [Hash]
  #
  def normalize_sort_order!: (symHash prm, **untyped opt) -> symHash

  # Locate and filter model records.
  #
  # @param [Array]         items    Default: #identifier.
  # @param [Array<Symbol>] filters  Filter methods to limit/modify params
  # @param [Hash]          opt      To Record::Searchable#search_records;
  #                                   default: `#current_params` if no *items*
  #                                   are given.
  #
  # @raise [Record::SubmitError]    If :page is not valid.
  #
  # @return [Paginator::Result]
  #
  def find_or_match_records: (*(String|Integer|Array[String|Integer]) items, ?filters: symArray, **untyped opt) -> Paginator::Result

  # Transform options into predicates usable for database lookup.
  #
  # @param [Hash] opt
  #
  # @return [Hash]                    The argument, possibly modified.
  #
  def normalize_predicates!: (symHash opt) -> symHash

  # Transform options into predicates usable for database lookup.
  #
  # @param [Hash] opt
  #
  # @return [Hash]                    A possibly-modified copy of the argument.
  #
  def normalize_predicates: (symHash opt) -> symHash

  # Remove options that would otherwise be sent as SQL search term predicates.
  #
  # @param [Hash]  opt                May be modified.
  #
  # @return [Boolean]                 True if keys were removed.
  #
  def filter_predicates!: (symHash opt) -> bool

  # Select records for the current user unless a different user has been
  # specified (or all records if specified as '*', 'all', or 'false').
  #
  # @param [Hash]  opt                May be modified.
  #
  def filter_by_user!: (symHash opt) -> void

  # Select records for the current organization unless a different one has
  # been specified (or all records if specified as '*', 'all', or 'false').
  #
  # @param [Hash]  opt                May be modified.
  #
  def filter_by_org!: (symHash opt) -> void

  # Select records for a specific model record (or all records if specified as
  # '*', 'all', or 'false').
  #
  # @param [Hash]  opt                May be modified.
  # @param [Class] model
  #
  def filter_by_model!: (symHash opt, ?model: Class) -> void

  # Limit records to those in the given state (or records with an empty state
  # field if specified as 'nil', 'empty', or 'missing').
  #
  # @param [Hash]   opt               May be modified.
  # @param [Symbol] key               State URL parameter.
  #
  # @return [Hash, nil]               *opt* if changed.
  #
  def filter_by_state!: (symHash opt, ?key: Symbol) -> (symHash | nil)

  # Limit by workflow status group.
  #
  # @param [Hash]                 opt     May be modified.
  # @param [Symbol]               key     Group URL parameter.
  # @param [Symbol|Array<Symbol>] state   State parameter(s).
  #
  # @return [Hash, nil]                   *opt* if changed.
  #
  def filter_by_group!: (symHash opt, ?key: Symbol, ?state: Symbol|symArray) -> (symHash | nil)

  # Return with the specified model record.
  #
  # @param [any, nil] item      String, Integer, Hash, Model; def: #identifier.
  # @param [Hash]     opt       Passed to Record::Identification#find_record.
  #
  # @raise [Record::StatementInvalid] If :id not given.
  # @raise [Record::NotFound]         If *item* was not found.
  #
  # @return [Model, nil]        A fresh record unless *item* is a #model_class.
  #
  # @yield [record] Raise an exception if the record is not acceptable.
  # @yieldparam [Model] record
  # @yieldreturn [void]
  #
  # @see Record::Identification#find_record
  #
  def find_record: (?(String|Integer|Model|symHash|nil) item, **untyped opt) ?{ (Model record) -> void } -> (Model | nil)

  # Start a new model instance.
  #
  # @param [Hash, nil] prm            Field values (def: `#current_params`).
  # @param [Hash]      opt            Added field values.
  #
  # @option opt [Boolean] force       If *true* allow setting of :id.
  #
  # @return [Model]                   An un-persisted model instance.
  #
  # @yield [attr] Adjust attributes and/or raise an exception.
  # @yieldparam [Hash] attr           Supplied attributes for the new record.
  # @yieldreturn [void]
  #
  def new_record: (?symHash? prm, **untyped opt) ?{ (symHash attr) -> void } -> Model

  # Add a new model record to the database.
  #
  # @param [Hash, nil] prm            Field values (def: `#current_params`).
  # @param [Boolean]   fatal          If *false*, use #save not #save!.
  # @param [Hash]      opt            Added field values.
  #
  # @option opt [Boolean] force       If *true* allow setting of :id.
  #
  # @return [Model]                   The new persisted model record.
  #
  # @yield [attr] Adjust attributes and/or raise an exception.
  # @yieldparam [Hash] attr           Supplied attributes for the new record.
  # @yieldreturn [void]
  #
  def create_record: (?symHash? prm, ?fatal: bool, **untyped opt) ?{ (symHash attr) -> void } -> Model

  # Start editing an existing model record.
  #
  # @param [any, nil] item            Default: the record for #identifier.
  # @param [Hash]     opt             Passed to #find_record.
  #
  # @raise [Record::StatementInvalid] If :id not given.
  # @raise [Record::NotFound]         If *item* was not found.
  #
  # @return [Model, nil]      A fresh instance unless *item* is a #model_class.
  #
  # @yield [record] Raise an exception if the record is not acceptable.
  # @yieldparam [Model] record        May be altered by the block.
  # @yieldreturn [void]               Block not called if *record* is *nil*.
  #
  def edit_record: (?(String|Integer|Model|symHash|nil) item, **untyped opt) ?{ (Model record) -> void } -> (Model | nil)

  # Persist changes to an existing model record.
  #
  # @param [any, nil] item            Default: the record for #identifier.
  # @param [Boolean]  fatal           If *false* use #update not #update!.
  # @param [Hash]     prm             Field values (default: `#current_params`)
  #
  # @raise [Record::NotFound]               If the record could not be found.
  # @raise [ActiveRecord::RecordInvalid]    Model record update failed.
  # @raise [ActiveRecord::RecordNotSaved]   Model record update halted.
  #
  # @return [Model, nil]              The updated model record.
  #
  # @yield [record, attr] Raise an exception if the record is not acceptable.
  # @yieldparam [Model] record        May be altered by the block.
  # @yieldparam [Hash]  attr          New field(s) to be assigned to *record*.
  # @yieldreturn [void]               Block not called if *record* is *nil*.
  #
  def update_record: (?(String|Integer|Model|symHash|nil) item, ?fatal: bool, **untyped prm) ?{ (Model record, symHash attr) -> void } -> (Model | nil)

  # Retrieve the indicated model record(s) for the '/delete' page.
  #
  # @param [any, nil] items           To #search_records
  # @param [Hash]     opt             Default: `#current_params`
  #
  # @raise [RangeError]               If :page is not valid.
  #
  # @return [Paginator::Result]
  #
  # @yield [items, opt] Raise an exception unless the *items* are acceptable.
  # @yieldparam [Array] items         Identifiers of items to be deleted.
  # @yieldparam [Hash]  opt           Options to #search_records.
  # @yieldreturn [void]               Block not called if *record* is *nil*.
  #
  def delete_records: (?(Model|String|Integer|Array[Model|String|Integer]|nil) items, **untyped opt) ?{ (Array[Model|String|Integer] items, symHash opt) -> void } -> Paginator::Result

  # Remove the indicated model record(s).
  #
  # @param [any, nil] items
  # @param [Boolean]  fatal           If *false* do not #raise_failure.
  # @param [Hash]     opt             Default: `#current_params`
  #
  # @raise [Record::SubmitError]      If there were failure(s).
  #
  # @return [Array]                   Destroyed entries.
  #
  # @yield [record] Called for each record before deleting.
  # @yieldparam [Model] record
  # @yieldreturn [String,nil]         Error message if *record* unacceptable.
  #
  def destroy_records: (?(Model|String|Integer|Array[Model|String|Integer]|nil) items, ?fatal: bool, **untyped opt) ?{ (Model record) -> (String | nil) } -> Array[Model]

  # Action permitted if the current user is signed-in unless *record* is *nil*.
  #
  # @param [Model, Hash, nil] record
  # @param [Hash]             opt     Passed to #unauthorized.
  #
  # @raise [CanCan::AccessDenied]     Only if `opt[:fatal]` is not *false*.
  #
  # @return [Boolean]                 *false* only if `opt[:fatal]` is *false*
  #
  def authorized_session: (?(Model|symHash|:ignored|nil) record, **untyped opt) -> bool

  # Action permitted if the current user owns *record* or is a manager of the
  # organization of the user that owns *record*.
  #
  # @param [Model, Hash, nil] record
  # @param [Hash]             opt     Passed to #authorized.
  #
  # @raise [CanCan::AccessDenied]     Only if `opt[:fatal]` is not *false*.
  #
  # @return [Boolean]                 *false* only if `opt[:fatal]` is *false*
  #
  def authorized_self_or_org_manager: (Model|symHash|nil record, **untyped opt) -> bool

  # Action permitted if the current user a manager of the organization of the
  # user that owns *record*.
  #
  # @param [Model, Hash, nil] record
  # @param [Hash]             opt     Passed to #authorized.
  #
  # @raise [CanCan::AccessDenied]     Only if `opt[:fatal]` is not *false*.
  #
  # @return [Boolean]                 *false* only if `opt[:fatal]` is *false*
  #
  def authorized_org_manager: (Model|symHash|nil record, **untyped opt) -> bool

  # Action permitted if the current user owns *record* or is in the same
  # organization as the user that owns *record*.
  #
  # @param [Model, Hash, nil] record
  # @param [Hash]             opt     Passed to #authorized.
  #
  # @raise [CanCan::AccessDenied]     Only if `opt[:fatal]` is not *false*.
  #
  # @return [Boolean]                 *false* only if `opt[:fatal]` is *false*
  #
  # == Usage Notes
  # Technically this yields the same result as #authorized_org_member but it is
  # preferred in cases like ManifestItem where determining the associated user
  # is less costly than determining the associated organization.
  #
  def authorized_self_or_org_member: (Model|symHash|nil record, **untyped opt) -> bool

  # Action permitted if the current user is in the same organization as the
  # user that owns *record*.
  #
  # @param [Model, Hash, nil] record
  # @param [Hash]             opt     Passed to #authorized.
  #
  # @raise [CanCan::AccessDenied]     Only if `opt[:fatal]` is not *false*.
  #
  # @return [Boolean]                 *false* only if `opt[:fatal]` is *false*
  #
  def authorized_org_member: (Model|symHash|nil record, **untyped opt) -> bool

  # Raise an exception with a tailored message.
  #
  # @param [Model, Hash, nil]    item
  # @param [Symbol, String, nil] action   Default: `params[:action]`.
  # @param [Class, nil]          subject  Default: `#model_class`.
  # @param [Symbol, nil]         key
  # @param [Boolean]             fatal    If *false* return *false*.
  # @param [Hash]                attr     Added field values.
  #
  # @raise [CanCan::AccessDenied]     Always raised unless *fatal* is *false*.
  #
  # @return [Boolean]                 Always *false* iff *fatal* is *false*.
  #
  def unauthorized: (?(Model|symHash|:ignored|nil) item, ?action: Symbol|String|nil, ?subject: Class|nil, ?key: Symbol|nil, ?fatal: bool, **untyped attr) -> bool

  # Action permitted if the current user is an administrator or *record* meets
  # the criteria supplied by the block.
  #
  # @param [Model, Hash, nil] record
  # @param [Hash]             opt     Passed to #unauthorized.
  #
  # @raise [CanCan::AccessDenied]     Only if `opt[:fatal]` is not *false*.
  #
  # @return [Boolean]                 *false* only if `opt[:fatal]` is *false*
  #
  # @yield [record] Determine if *record* is permitted for the current user.
  # @yieldparam [Model, Hash, nil] record
  # @yieldreturn [Boolean] *true* if permitted.
  #
  def authorized: (Model|symHash|nil record, **untyped opt) { (Model|symHash|nil record) -> bool } -> bool

  # Indicate whether the current user is a manager of the organization to which
  # the owner of *record* belongs.
  #
  # @param [Model, Hash, nil] record
  #
  def authorized_manager?: (Model|symHash|nil record) -> bool

  # Indicate whether *record* is owned by someone in the current user's
  # organization.
  #
  # @param [Model, Hash, nil] record
  #
  def authorized_org?: (Model|symHash|nil record) -> bool

  # Indicate whether *record* is owned by the current user.
  #
  # @param [Model, Hash, nil] record
  #
  def authorized_user?: (Model|symHash|nil record) -> bool

  # Raise an exception.
  #
  # @param [Symbol, String, Array<String>, ExecReport, Exception, nil] problem
  # @param [any, nil]                                                  value
  #
  # @raise [Record::SubmitError]
  # @raise [ExecError]
  #
  # @see ExceptionHelper#raise_failure
  #
  def raise_failure: ((Symbol|String|strArray|Exception|ExecReport|nil) problem, ?untyped value) -> void

  private

  THIS_MODULE: Module
end
