# Controller support methods for managing model/controller options.
#
module OptionsConcern
  extend ActiveSupport::Concern

  include ParamsHelper

  # Access the @model_options instance created for the current controller.
  #
  # @return [Options]
  #
  def model_options: () -> Options

  # Create a @model_options instance from the current parameters.
  #
  # @return [Options]
  #
  def set_model_options: () -> Options

  private

  THIS_MODULE: untyped

  include ParamsHelper

  # :nocov:
  include AbstractController::Callbacks::ClassMethods

  include OptionsConcern
end
