# Support methods for the "/org" controller.
#
module OrgConcern
  extend ActiveSupport::Concern

  include ModelConcern

  # The identifier of the current model instance which #CURRENT_ID represents
  # in the context of OrgController actions.
  #
  # @return [Integer, nil]
  #
  def current_id: () -> (Integer | nil)

  # Get URL parameters relevant to the current operation.
  #
  # @return [Hash{Symbol=>*}]
  #
  def current_get_params: () -> symHash

  # Extract POST parameters that are usable for creating/updating a Manifest
  # instance.
  #
  # @return [Hash{Symbol=>*}]
  #
  def current_post_params: () -> symHash

  # Create an Options instance from the current parameters.
  #
  # @return [Org::Options]
  #
  def get_model_options: () -> Org::Options

  # Create a Paginator for the current controller action.
  #
  # @param [Class<Paginator>] paginator  Paginator class.
  # @param [Hash]             opt        Passed to super.
  #
  # @return [Org::Paginator]
  #
  def pagination_setup: (?paginator: Class, **untyped opt) -> Org::Paginator

  private

  THIS_MODULE: Module
end
