# Controller support methods for failure responses.
#
module ResponseConcern
  extend ActiveSupport::Concern

  include FlashHelper

  include ParamsHelper

  # Generate a flash message if there is an error.
  #
  # @param [Exception, String, *] error
  # @param [Integer, Symbol]      status
  # @param [Boolean]              xhr
  # @param [String, Symbol]       action
  # @param [Symbol]               meth
  #
  # @return [Integer, Symbol]         HTTP status.
  #
  def failure_response: (untyped error, ?status: Integer|Symbol|nil, ?xhr: bool|nil, ?action: Symbol|String|nil, ?meth: Symbol|nil) -> (Integer | Symbol)

  private

  THIS_MODULE: Module
end
