# Controller support methods for bulk submissions.
#
module SubmissionConcern
  extend ActiveSupport::Concern

  include ApiConcern

  # Access the bulk submission service.
  #
  # @return [SubmissionService]
  #
  def submission_api: () -> SubmissionService

  # start_submission
  #
  # @param [Manifest] manifest
  # @param [Hash]     opt             To SubmissionService#make_request
  #
  # @return [void]
  #
  # @note Currently unused.
  #
  def start_submission: (Manifest manifest, **untyped opt) -> void

  # stop_submission
  #
  # @param [Manifest] manifest
  # @param [Hash]     opt             To SubmissionService#make_request
  #
  # @return [void]
  #
  # @note Currently unused.
  #
  def stop_submission: (Manifest manifest, **untyped opt) -> void

  # pause_submission
  #
  # @param [Manifest] manifest
  # @param [Hash]     opt             To SubmissionService#make_request
  #
  # @return [void]
  #
  # @note Currently unused.
  #
  def pause_submission: (Manifest manifest, **untyped opt) -> void

  # resume_submission
  #
  # @param [Manifest] manifest
  # @param [Hash]     opt             To SubmissionService#make_request
  #
  # @return [void]
  #
  # @note Currently unused.
  #
  def resume_submission: (Manifest manifest, **untyped opt) -> void

  private

  THIS_MODULE: Module
end
