# Controller support methods for system information.
#
module SysConcern
  extend ActiveSupport::Concern

  include ApplicationHelper

  # System information pages (except for :index).
  #
  # @type [Array<Symbol>]
  #
  # @see "en.emma.page.sys.action"
  #
  SYS_PAGES: symArray

  # Get the path for a redirection from configuration.
  #
  # @param [Symbol] meth
  #
  # @return [String]
  #
  def sys_path_for: (Symbol meth) -> String

  private

  THIS_MODULE: Module
end
