# Support for command-line processing via Rake and the RubyMine IDE.
#
module TestHelper::CommandLine
  extend ::TestHelper::CommandLine

  # Get command-line argument "TEST_FORMATS=..." or ENV['TEST_FORMATS'].
  #
  # @param [Array<Symbol>] default
  #
  # @return [Array<Symbol>]
  #
  def cli_env_test_formats: (?default: symArray) -> symArray

  # Get command-line argument "TEST_BOOKSHARE=..." or ENV['TEST_BOOKSHARE'].
  #
  # @param [Array<Symbol>] default
  #
  # @return [Array<Symbol>]
  #
  def cli_env_test_bookshare: (?default: symArray) -> symArray

  # Get a setting from command-line arguments or environment variable.
  #
  # @param [Array, String, Symbol, nil] value
  # @param [String]                     var
  # @param [Array<Symbol>, nil]         default
  #
  # @return [Array<Symbol>, nil]
  #
  def cli_env_value
    : (?(Array[String|Symbol]|String|Symbol|nil) value, var: String, default: symArray) -> symArray
    | (?(Array[String|Symbol]|String|Symbol|nil) value, var: String, default: nil)      -> (symArray | nil)
end
