# Support for debugging tests.
#
module TestHelper::Debugging
  TEST_DEBUG_FRAME: String

  TEST_DEBUG_INDENT: String

  # Options for #show_test_start and #show_test_end.
  #
  # @private
  # @type [Array<Symbol>]
  #
  SHOW_TEST_OPT: symArray

  # Produce the top frame of debug output for a test.
  #
  # @param [String, Symbol, nil] test_name
  # @param [Symbol]              test       Overrides *test_name* if given.
  # @param [String]              part
  # @param [String]              frame      Default: #TEST_DEBUG_FRAME.
  #
  # @return [void]
  #
  def show_test_start: (String|Symbol|nil test_name, ?test: Symbol|nil, ?part: String|nil, ?frame: String|nil, **untyped _ignored) -> void

  # Produce the bottom frame of debug output for a test.
  #
  # @param [String, Symbol, nil] test_name
  # @param [Symbol]              test       Overrides *test_name* if given.
  # @param [String]              part
  # @param [String]              frame      Default: #TEST_DEBUG_FRAME.
  #
  # @return [void]
  #
  def show_test_end: (String|Symbol|nil test_name, ?test: Symbol|nil, ?part: String|nil, ?frame: String|nil, **untyped _ignored) -> void

  # Display item model in output.
  #
  # @param [ActiveRecord::Base] item
  # @param [Boolean, String]    indent
  # @param [Boolean]            reflections
  # @param [Hash]               opt           Passed to #show.
  #
  # @return [String]
  #
  def show_model: (ActiveRecord::Base item, ?indent: bool|String, ?reflections: bool, **untyped opt) -> String

  # Display item model associations in output.
  #
  # @param [ActiveRecord::Base] item
  # @param [Boolean, String]    indent  Default: #TEST_DEBUG_INDENT
  # @param [Hash]               opt     Passed to #show.
  #
  # @return [String]
  #
  def show_reflections: (ActiveRecord::Base item, ?indent: bool|String, **untyped opt) -> String

  # Display a URL in output.
  #
  # @param [URI, String, nil] url     Default: `#current_url`.
  # @param [Hash]             opt     Passed to #show.
  #
  # @return [String]
  #
  def show_url: (?(String|URI|nil) url, **untyped opt) -> String

  # Display a user in output.
  #
  # @param [String, Symbol, User, nil] user   Default: `#current_user`.
  # @param [Hash]                      opt    Passed to #show.
  #
  # @return [String]
  #
  def show_user: (?(String|Symbol|User|nil) user, **untyped opt) -> String

  # Display item contents in output.
  #
  # @param [Array<*>]        items
  # @param [Boolean, String] indent
  # @param [Boolean]         output   If *false* the result is only returned.
  # @param [Hash]            opt      Passed to #show_model.
  #
  # @return [String]                  The displayable result.
  #
  # @yield To supply additional items.
  # @yieldreturn [Array, String, any, nil]
  #
  def show: (*untyped items, ?indent: bool|String, ?output: bool, **untyped opt) ?{ () -> untyped } -> String

  # Generate a line prefix string for #show output.
  #
  # @param [Boolean, Integer, String, nil] indent
  # @param [Integer, String, nil]          default    If *indent* is *true*.
  #
  # @return [String, nil]
  #
  def show_prefix: (bool|Integer|String|nil indent, default: Integer|String|nil) -> (String | nil)

  # Send one or more lines to $stderr.
  #
  # @param [Array,nil] lines          Nil elements are interpreted as newlines.
  #
  # @return [void]
  #
  def show_lines: (*untyped lines) -> void

  TRACE_NL: String

  TRACE_BODY: Integer

  TRACE_SEPARATOR: Hash[String,String]

  SHOW_PRE_SEND_OPT: symArray

  SHOW_POST_SEND_OPT: symArray

  SHOW_TRACE_OPT: symArray

  # Display conditions prior to invoking an HTTP method.
  #
  # @param [Symbol] verb              HTTP verb (:get, :put, :post, :delete)
  # @param [String] url               Target URL or relative path.
  # @param [String] user              Default: `#current_user`.
  # @param [Symbol] format            Result format (:html, :json, :xml).
  # @param [Hash]   opt               Passed to #show_trace.
  #
  # @return [String, nil]             The displayable result.
  #
  def show_pre_send: (Symbol verb, String url, ?user: String|nil, ?format: Symbol|nil, **untyped opt) -> (String | nil)

  # Display conditions after invoking an HTTP method.
  #
  # @param [Symbol, String, Integer]      expect
  # @param [Symbol, String, Integer]      status
  # @param [ActionDispatch::TestResponse] response
  # @param [Hash]                         opt       Passed to #show_trace.
  #
  # @return [String, nil]             The displayable result.
  #
  def show_post_send: (?expect: Symbol|String|Integer|nil, ?status: Symbol|String|Integer|nil, ?response: ActionDispatch::TestResponse|nil, **untyped opt) -> (String | nil)

  # show_trace
  #
  # @param [String, Integer] indent
  # @param [Boolean, nil]    trace
  # @param [Hash] opt                 Passed to #show.
  #
  # @return [String, nil]             The displayable result.
  #
  # @yield To supply pairs to be displayed.
  # @yieldreturn [Hash]
  #
  def show_trace: (?indent: String|Integer, ?trace: bool|nil, **untyped opt) ?{ () -> anyHash } -> (String | nil)

  # Execute the provided block with tracing turned off to allow for executions
  # which do not clutter the output.
  #
  def without_tracing: [T] () { () -> T } -> T

  # Flag indicating that #show_trace should be silenced.
  #
  # @return [Boolean, nil]
  #
  attr_accessor silence_tracing: bool | nil
end

# This module is included in ActionDispatch::IntegrationTest to support
# tracing of HTTP method calls.
#
# @!method original_get
#   The superclass :get method (without pre/post trace output).
#
# @!method original_put
#   The superclass :put method (without pre/post trace output).
#
# @!method original_post
#   The superclass :post method (without pre/post trace output).
#
# @!method original_patch
#   The superclass :patch method (without pre/post trace output).
#
# @!method original_delete
#   The superclass :delete method (without pre/post trace output).
#
# @!method original_head
#   The superclass :head method (without pre/post trace output).
#
module TestHelper::Debugging::Trace
  include TestHelper::Debugging

  PRE_OPT: symArray

  POST_OPT: symArray

  TRACE_OPT: symArray

  # Override HTTP methods defined in ActionDispatch::Integration::Runner in
  # order to surround the method calls with trace debugging information.
  #
  # No override methods are created if *base* is some other class/module
  # which doesn't define these methods.
  #
  # @param [Module] base
  #
  def self.included: (Module base) -> void

  def original_get:    () -> untyped
  def original_put:    () -> untyped
  def original_post:   () -> untyped
  def original_patch:  () -> untyped
  def original_delete: () -> untyped
  def original_head:   () -> untyped

end
