# Access to sample models.
#
module TestHelper::Samples
  # A string added to the start of each title created on a non-production
  # instance to help distinguish it from other index results.
  #
  # @type [String]
  #
  TITLE_PREFIX: String

  # File fixture for Uploads.
  #
  # @type [String]
  #
  UPLOAD_FILE: String

  # Generate a unique user account email name.
  #
  # @param [User, String] original
  #
  # @return [String]
  #
  def unique_email: (User|String original) -> String
end
