# System test support methods.
#
module TestHelper::SystemTests
  # Alias for Capybara::Node::Actions#click_link_or_button which isn't being
  # seen by RubyMine dynamic checking for some reason.
  def click_on: (?String? locator, **untyped opt) -> Capybara::Node::Element

  private

  # Include the submodules defined in test/test_helper/system_tests/*.
  #
  # @param [Module] base
  #
  def self.included: (Module base) -> void
end
