module ObjectExt
  include SystemExtension

  # Recursive freezing support.
  #
  # @see Hash#deep_freeze
  #
  def deep_freeze: () -> self

  # Recursive duplication support.
  #
  # @see Hash#rdup
  #
  def rdup: () -> (untyped | self)

  # A stand-in for #inspect for more limited output.
  #
  # @param [any, nil] item            Default: `self`.
  # @param [Integer]  max
  #
  # @return [String]
  #
  def summary: (?untyped item, ?max: Integer) -> String
end

class Object
  include ObjectExt
end
