module Emma::Common::ObjectMethods
  # Transform a hash into a struct recursively.  (Any hash value which is
  # itself a hash will be converted to a struct).
  #
  # @param [Hash]    hash
  # @param [Boolean] arrays           If *true*, convert hashes within arrays.
  #
  # @return [Struct]
  #
  def struct: (anyHash hash, ?bool arrays) -> Struct[untyped]

  # Translate a item into a class.
  #
  # @param [Symbol, String, Class, *] item
  #
  # @return [Class, nil]
  #
  def to_class
    : (nil     item) -> nil
    | (untyped item) -> (Class | nil)
end
