# Braille file format metadata extractor.
#
class FileParser::Braille < FileParser
  include FileFormat::Braille

  # Metadata extracted from the file format instance.
  #
  # @return [OpenStruct]
  #
  def metadata: () -> OpenStruct
end
