# HTML file format metadata extractor.
#
class FileParser::Html < FileParser
  include FileFormat::Html

  # Metadata extracted from the file format instance.
  #
  # @return [OpenStruct]
  #
  def metadata: () -> OpenStruct
end
