# Metadata extractor for a non-specific format.
#
class FileParser::Other < FileParser
  include FileFormat::Other

  # Metadata extracted from the file format instance.
  #
  # @return [OpenStruct]
  #
  def metadata: () -> OpenStruct
end
