# RTF file format metadata extractor.
#
class FileParser::Rtf < FileParser
  include FileFormat::Rtf

  # Metadata extracted from the file format instance.
  #
  # @return [OpenStruct]
  #
  def metadata: () -> OpenStruct
end
