# Tactile file format metadata extractor.
#
class FileParser::Tactile < FileParser
  include FileFormat::Tactile

  # Metadata extracted from the file format instance.
  #
  # @return [OpenStruct]
  #
  def metadata: () -> OpenStruct
end
