class BsApiControllerTest < ActionDispatch::IntegrationTest
  CONTROLLER: String

  OPTIONS: symHash

  TEST_USERS: Array[String|nil]

  TEST_READERS: Array[String|nil]

  TEST_WRITERS: Array[String|nil]

  TEST_API_PATH: String
end
