class HealthControllerTest < ApplicationControllerTestCase
  CTRLR: Symbol

  PRM: symHash

  OPT: symHash

  TEST_READERS: symArray

  READ_FORMATS: symArray | Symbol

  NO_READ: symArray

  @readers: Array[User|nil]

  # ===========================================================================
  # :section: Methods
  # ===========================================================================

  public

  # Perform a HealthController test.
  #
  # @param [Symbol] action
  # @param [String] url
  # @param [Symbol] meth              Calling test method.
  # @param [Hash]   opt               Passed to #assert_result.
  #
  # @return [void]
  #
  def check_url_test: (Symbol action, String url, meth: Symbol|nil, **untyped opt) -> void
end
