class HomeControllerTest < ActionDispatch::IntegrationTest
  CONTROLLER: Symbol

  OPTIONS: symHash

  TEST_USERS: symArray

  TEST_READERS: symArray

  READ_FORMATS: symArray | Symbol

  @readers: Array[User|nil]

  TEST_USER: Symbol
end
