class ManifestControllerTest < ApplicationControllerTestCase
  MODEL: Class

  CTRLR: Symbol

  PRM: symHash

  OPT: symHash

  TEST_READERS: symArray

  TEST_WRITERS: symArray

  READ_FORMATS: symArray | Symbol

  WRITE_FORMATS: symArray | Symbol

  NO_READ: symArray

  NO_WRITE: symArray

  @readers: Array[User|nil]

  @writers: Array[User|nil]

  @generate: ManifestSampleGenerator

  # The default :index action redirects to :list_own.
  #
  # @param [Hash] opt
  #
  # @return [String]
  #
  def index_redirect: (**untyped opt) ?{ () -> (Symbol|String|Proc|nil) } -> String
end
