class MemberControllerTest < ActionDispatch::IntegrationTest
  MODEL: Class

  CONTROLLER: Symbol

  PARAMS: symHash

  OPTIONS: symHash

  TEST_USERS: symArray

  TEST_READERS: symArray

  TEST_WRITERS: symArray

  READ_FORMATS: Symbol | symArray

  WRITE_FORMATS: Symbol | symArray

  @readers: Array[User|nil]

  @writers: Array[User|nil]
end
