class SearchControllerTest < ApplicationControllerTestCase
  CTRLR: Symbol

  PRM: symHash

  OPT: symHash

  TEST_READERS: symArray

  READ_FORMATS: symArray | Symbol

  @readers: Array[User|nil]
end
