class LookupChannel::Response < ApplicationCable::Response
  # @see file://app/assets/javascripts/shared/lookup-response.js *TEMPLATE*
  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.data_url_base_path: () -> String
end

class LookupChannel::LookupResponse < LookupChannel::Response
end

class LookupChannel::StatusResponse < LookupChannel::Response
  # Create a new instance.
  #
  # @param [any, nil] values
  # @param [Hash]     opt
  #
  def initialize: (?untyped values, **untyped opt) -> void

  def payload_normalize: (untyped value, ?except: symArray|Symbol|nil) -> symHash
end

class LookupChannel::InitialResponse < LookupChannel::StatusResponse
  def self.default_status: () -> String
end
