# Methods mixed in to record elements related to catalog titles.
#
module Lookup::RemoteService::Shared::TitleMethods
  include Api::Shared::TitleMethods
  include Lookup::RemoteService::Shared::IdentifierMethods

  # A unique identifier for this catalog title.
  #
  # @return [String, nil]
  #
  def identifier: () -> (String | nil)

  # The title and subtitle of this catalog title.
  #
  # @param [Symbol] field
  #
  # @return [String]
  #
  def full_title: (?(Symbol|nil) field) -> String

  # Name of publisher.
  #
  # @param [Symbol] field
  #
  # @return [String, nil]
  #
  def publisher_name: (?(Symbol|nil) field) -> (String | nil)

  # The place of publication.
  #
  # @param [Symbol] field
  #
  # @return [String, nil]
  #
  def publication_place: (?(Symbol|nil) field) -> (String | nil)

  # The date of publication.
  #
  # @param [Symbol] field
  #
  # @return [String, nil]
  #
  def publication_date: (?(Symbol|nil) field) -> (String | nil)

  # The year of publication.
  #
  # @param [Symbol] field
  #
  # @return [String, nil]
  #
  def publication_year: (?(Symbol|nil) field) -> (String | nil)

  # The type of work containing an article (if relevant).
  #
  # @param [Symbol] field
  #
  # @return [String, nil]
  #
  def series_type: (?(Symbol|nil) field) -> (String | nil)

  # The volume of the journal containing an article (if relevant).
  #
  # @param [Symbol] field
  #
  # @return [String, nil]
  #
  def series_volume: (?(Symbol|nil) field) -> (String | nil)

  # The issue of the journal containing an article (if relevant).
  #
  # @param [Symbol] field
  #
  # @return [String, nil]
  #
  def series_issue: (?(Symbol|nil) field) -> (String | nil)

  # language_list
  #
  # @param [Symbol] field
  #
  # @return [Array<String>]
  #
  def language_list: (?(Symbol|nil) field) -> strArray

  # subject_list
  #
  # @param [Symbol] field
  #
  # @return [Array<String>]
  #
  def subject_list: (?(Symbol|nil) field) -> strArray

  # description_list
  #
  # @param [Symbol] field
  #
  # @return [Array<String>]
  #
  def description_list: (?(Symbol|nil) field) -> strArray
end
