# The base URL for relative requests.
#
# @type [String]
#
BASE_URL: String

# If *true* then #show and #show_reflections will produce output on the
# console.
#
# @type [Boolean]
#
DEBUG_TESTS: bool

# If not testing client-side behavior for system tests, setting this to *false*
# will use Rack::Test rather than Selenium.
#
# NOTE: This is unverified.
#
# @type [Boolean]
#
TESTING_JAVASCRIPT: bool

NO_JAVASCRIPT: bool

# Support methods for tests.
#
module TestHelper
  include CommandLine

  include Debugging

  include IntegrationTests

  include Samples

  include Utility

  private

  # Include the submodules defined in test/test_helper/*, except for
  # TestHelper::SystemTests, which must be included separately.
  #
  # @param [Module] base
  #
  def self.included: (Module base) -> void
end

# The output format(s) to test.
#
# The current test task may have already set this constant; if not the default
# value set here will be used.
#
# @type [Array<Symbol>]
#
# @see file:lib/tasks/test_application.rake
#
TEST_FORMATS: symArray

# Bookshare API aspects to test.
#
# The current test task may have already set this constant; if not the default
# value set here will be used.
#
# @type [Array<Symbol>]
#
# @see file:lib/tasks/test_application.rake
#
# == Usage Notes
# No Bookshare-specific tests are run unless specified by the test task or if
# run explicitly from the IDE.
#
TEST_BOOKSHARE: symArray

# Augment the base class for test cases.
#
class ActiveSupport::TestCase
  include Emma::Common

  include TestHelper
end

# Augment the base class for integration test cases.
#
class ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers

  include TestHelper #::Samples

  include TestHelper::Debugging::Trace

  extend TestHelper::Utility
end

# Make relative paths expand correctly.
#
class ActionDispatch::Integration::Session
end
