# Common view helper methods.
#
module ApplicationHelper
  include Emma::Constants

  include Emma::Common

  include HtmlHelper

  include ConfigurationHelper

  # Raw configuration entries for each controller that supplies content (i.e.,
  # those controllers with a subdirectory in app/view) plus 'emma.generic'
  # and distinct entries for each 'emma.user' Devise controller.
  #
  # @type [Hash{Symbol=>Hash}]
  #
  CONTROLLER_CONFIGURATION: Hash[Symbol,symHash]

  # Configuration for application properties.
  #
  # @type [Hash{Symbol=>*}]
  #
  APP_CONFIG: symHash

  # The controllers for the application.
  #
  # @type [Array<Symbol>]
  #
  APP_CONTROLLERS: symArray

  # The name of this application for display purposes.
  #
  # @return [String]
  #
  # @note Currently unused.
  #
  def app_name: () -> String

  # Indicate whether a view template partial exists.
  #
  # @param [String] path
  # @param [Array]  prefixes          Default: [params[:controller]].
  #
  # @option prefixes.last [Hash]      Hash values to use in place of `params`.
  #
  def partial_exists?: (String path, *(String|Symbol) prefixes) -> bool

  # The "mailto:" link for the general e-mail contact.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def contact_email: () -> ActiveSupport::SafeBuffer

  private

  def self.included: (Module base) -> void
end
