# Support methods for working with authentication strategies.
#
module AuthHelper
  include Emma::Common

  extend ::AuthHelper

  # Generate the authentication data to be associated with the given user.
  #
  # @param [User, nil] user
  #
  # @return [OmniAuth::AuthHash, nil]
  #
  def auth_hash
    : (User user) -> OmniAuth::AuthHash
    | (nil  user) -> nil

  private

  def self.included: (Module base) -> void
end
