# View helper methods for the "Bookshare API Explorer" ("/bs_api" pages).
#
module BsApiHelper
  include Emma::Common

  include ApiHelper

  extend ::BsApiHelper

  # @private
  BOOKSHARE_USER: String

  # Transform name(s) into Bookshare username(s).
  #
  # @param [String, Symbol, Array<String,Symbol>] name
  #
  # @return [String]
  # @return [Array<String>]
  #
  # -
  # == Variations
  # +
  #
  # @overload bookshare_user(name)
  #   @param [String, Symbol] name
  #   @return [String]
  #
  # @overload bookshare_user(names)
  #   @param [Array<String,Symbol>] names
  #   @return [Array<String>]
  #
  def bookshare_user
    : ((String|Symbol)      name)  -> String
    | (Array[String|Symbol] names) -> strArray

  # Generate a URL to an external (Bookshare-related) site, refactored so that
  # it passes through the application's "Bookshare API Explorer" endpoint.
  #
  # @param [String] path
  # @param [Hash]   prm               Passed to #make_path.
  #
  # @return [String]
  #
  def bs_api_explorer_url: (String path, **untyped prm) -> String

  private

  def self.included: (Module base) -> void
end
