# Support methods for working with request cookies.
#
module CookieHelper
  # Get the current value of the cookie from the request.
  #
  # @param [Symbol, String] key
  #
  # @return [*]
  #
  def get_cookie: ((Symbol|String) key) -> untyped

  # Set the cookie in the request and the response.
  #
  # @param [Symbol, String] key
  # @param [*]              value     Defaults to *true*.
  #
  # @return [Any]                     The cookie value.
  # @return [nil]                     If the cookie could not be set.
  #
  def set_cookie: ((Symbol|String) key, ?untyped value) -> (untyped | nil)

  # Remove the cookie from the request and indicate removal in the response.
  #
  # @param [Symbol, String] key
  #
  # @return [void]
  #
  def delete_cookie: ((Symbol|String) key) -> void

  private

  def self.included: (Module base) -> void
end
