type flashArg  = String | Symbol | Exception | ExecReport | ExecReport::FlashPart | nil
type flashArgs = flashArg | Array[flashArg]

# Methods for creating and displaying flash messages.
#
module FlashHelper
  include Emma::Common

  include EncodingHelper

  include HtmlHelper

  include XmlHelper

  # Maximum length of any one flash message.
  #
  # @type [Integer]
  #
  # === Implementation Notes
  # This has been sized very conservatively so that it also works in the
  # desktop setting where the instance shares the 4096-byte cookie space with
  # other local applications.
  #
  # This shouldn't be a big problem; if it is then it might be time to consider
  # investing in setting up infrastructure for an alternative cookie mechanism.
  #
  FLASH_MAX_ITEM_SIZE: Integer

  # Maximum size of all combined flash messages.
  #
  # @type [Integer]
  #
  FLASH_MAX_TOTAL_SIZE: Integer

  # If *true*, the flash container should be displayed inline on the page.
  #
  # @type [Boolean, nil]
  #
  attr_reader flash_inline: bool | nil

  # If *true*, the flash container should float above the page.
  #
  # @type [Boolean, nil]
  #
  attr_reader flash_floating: bool | nil

  # Specify that flash messages are displayed inline on the page.
  #
  # @param [Boolean] on
  #
  # @return [Boolean]
  #
  def set_flash_inline: (?bool on) -> bool

  # Specify that flash messages should float above the page.
  #
  # @param [Boolean] on
  #
  # @return [Boolean]
  #
  def set_flash_floating: (?bool on) -> bool

  # Specify that the flash container should be cleared on page refresh.
  #
  # @param [Boolean] on
  #
  # @return [Boolean]
  #
  def set_flash_reset: (?bool on) -> bool

  # Indicate whether the flash container should be cleared on page refresh.
  #
  # @return [Boolean]
  #
  def flash_reset: () -> bool

  @flash_reset: bool | nil

  # Each instance translates to a distinct line in the flash message.
  #
  class FlashPart < ExecReport::FlashPart
    include HtmlHelper

    # Create a new instance.
    #
    def initialize: ((ExecReport::Part|String|Integer|anyArray|anyHash|nil) topic, ?(ExecReport::Part|String|anyArray|anyHash|nil) details) -> void

    # Generate HTML elements for the parts of the entry.
    #
    # @param [Integer, nil] first     Index of first column (def: 1).
    # @param [Integer, nil] last      Index of last column (def: `parts.size`).
    # @param [Hash]         part      Options passed to inner #html_div.
    # @param [String]       css       Characteristic CSS class/selector.
    # @param [Hash]         opt       Passed to outer #html_div
    #
    # @option opt [String, nil]  :separator   Default: #HTML_BREAK.
    # @option opt [Boolean, nil] :html
    #
    # @return [ActiveSupport::SafeBuffer]
    #
    # @see #render_part
    #
    def render: (?first: Integer|nil, ?last: Integer|nil, ?part: symHash|nil, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

    # Generate an HTML element for a single part of the entry.
    #
    # @param [String, nil]  part
    # @param [Integer, nil] pos       Position of part (starting from 1).
    # @param [Integer, nil] first     Index of the first column.
    # @param [Integer, nil] last      Index of the last column.
    # @param [String]       css       Characteristic CSS class/selector.
    # @param [Hash]         opt       Passed to #html_div.
    #
    # @return [ActiveSupport::SafeBuffer]
    #
    def render_part: ((String|nil) part, ?pos: Integer|nil, ?first: Integer|nil, ?last: Integer|nil, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

    # A short-cut for creating a FlashHelper::FlashPart only if required.
    #
    # @param [FlashPart, *] other
    #
    # @return [FlashPart]
    #
    def self.[]: (untyped other) -> FlashPart
  end

  # Success flash notice.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash notice messages.
  #
  # @see #flash_notice
  # @see #flash_format
  #
  def flash_success: (*flashArg args, **untyped opt) -> strArray

  # Failure flash notice.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash alert messages.
  #
  # @see #flash_alert
  # @see #flash_format
  #
  def flash_failure: (*flashArg args, **untyped opt) -> strArray

  # Flash notice.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Symbol, nil]                                             topic
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash notice messages.
  #
  # @see #set_flash
  # @see #flash_format
  #
  def flash_notice: (*flashArg args, ?topic: Symbol|nil, **untyped opt) -> strArray

  # Flash alert.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Symbol, nil]                                             topic
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash alert messages.
  #
  # @see #set_flash
  # @see #flash_format
  #
  def flash_alert: (*flashArg args, ?topic: Symbol|nil, **untyped opt) -> strArray

  # Flash notification, which appears on the next page to be rendered.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Symbol]      type         :alert or :notice
  # @param [Symbol, nil] topic
  # @param [Boolean]     clear        If *true* clear flash first.
  # @param [Hash]        opt          Passed to #flash_format.
  #
  # @return [Array<String>]           Current *type* flash messages.
  #
  # @see #flash_format
  #
  def set_flash: (*flashArg args, type: Symbol, ?topic: Symbol|nil, ?clear: bool|nil, **untyped opt) -> strArray

  # Success flash now.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash.now notice messages.
  #
  # @note Currently unused.
  #
  # @see #flash_now_notice
  # @see #flash_format
  #
  def flash_now_success: (*flashArg args, **untyped opt) -> strArray

  # Failure flash now.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash.now alert messages.
  #
  # @see #flash_now_alert
  # @see #flash_format
  #
  def flash_now_failure: (*flashArg args, **untyped opt) -> strArray

  # Flash now notice.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Symbol, nil]                                             topic
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash.now notice messages.
  #
  # @see #set_flash_now
  # @see #flash_format
  #
  def flash_now_notice: (*flashArg args, ?topic: Symbol|nil, **untyped opt) -> strArray

  # Flash now alert.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Symbol, nil]                                             topic
  # @param [Hash]                                                    opt
  #
  # @return [Array<String>]           Current flash.now alert messages.
  #
  # @see #set_flash_now
  # @see #flash_format
  #
  def flash_now_alert: (*flashArg args, ?topic: Symbol|nil, **untyped opt) -> strArray

  # Flash now notification, which appears on the current page when it is
  # rendered.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Symbol]      type         :alert or :notice
  # @param [Symbol, nil] topic
  # @param [Hash]        opt
  #
  # @return [Array<String>]           Current *type* flash.now messages.
  #
  # @see #flash_format
  #
  def set_flash_now: (*flashArg args, type: Symbol, ?topic: Symbol|nil, **untyped opt) -> strArray

  # Create items(s) to be included in the 'X-Flash-Message' header to support
  # the ability of the client to update the flash display.
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Hash]                                                    opt
  #
  # @return [String]
  #
  # @see #flash_format
  #
  def flash_xhr: (*flashArg args, **untyped opt) -> String

  # @type [Array<Symbol>]
  FLASH_TARGETS: symArray

  # Prepend the method invoking flash if there is not already one at the start
  # of *args*.
  #
  # @param [Array]          args
  # @param [Symbol, String] meth      Calling method (if not at args[0]).
  #
  # @return [Array]                   The original *args*, possibly modified.
  #
  def prepend_flash_source!: (Array[flashArg] args, ?meth: Symbol|String|nil) -> Array[flashArg]

  # Return the effective flash type.
  #
  # @param [Symbol, String, nil] type
  #
  # @return [Symbol]
  #
  def flash_target: ((Symbol|String|nil) `type`) -> Symbol

  # Theoretical space available for flash messages.
  #
  # @return [Integer]
  #
  # @see ActionDispatch::Flash::RequestMethods#commit_flash
  # @see ActionDispatch::Flash::FlashHash#to_session_value
  #
  def flash_space_available: () -> Integer

  # String to display if item(s) were omitted.
  #
  # @param [Integer, nil] count   Total number of items.
  # @param [Boolean]      html
  #
  # @return [String]                    If *html* is *false*.
  # @return [ActiveSupport::SafeBuffer] If *html* is *true*.
  #
  def flash_omission
    : (?(Integer|nil) count, ?html: bool,  **untyped ingored) -> (ActiveSupport::SafeBuffer | String)
    | (?(Integer|nil) count,  html: false, **untyped ingored) -> String
    | (?(Integer|nil) count,  html: true,  **untyped ingored) -> ActiveSupport::SafeBuffer

  # Create item(s) to be included in the flash display.
  #
  # By default, when displaying an Exception, this method also logs the
  # exception and its stack trace (to avoid "eating" the exception when this
  # method is called from an exception handler block).
  #
  # @param [Array<String,Symbol,ExecReport,Exception,FlashPart,nil>] args
  # @param [Symbol, nil] topic
  # @param [Hash]        opt          To #flash_template except for:
  #
  # @option opt [Boolean] :inspect    If *true* apply #inspect to messages.
  # @option opt [Any]     :status     Override reported exception status.
  # @option opt [Boolean] :log        If *false* do not log exceptions.
  # @option opt [Boolean] :trace      If *true* always log exception trace.
  # @option opt [Symbol]  :meth       Calling method.
  # @option opt [Boolean] :xhr        Format for 'X-Flash-Message'.
  #
  # @return [ActiveSupport::SafeBuffer]
  # @return [String]                      For :xhr.
  #
  # -
  # === Variations
  # +
  #
  # @overload flash_format(meth, error, *args, topic: nil, **opt)
  #   @param [Symbol]                  meth   Calling method.
  #   @param [ExecReport, Exception]   error  Error (message) if :alert.
  #   @param [Array<String,FlashPart>] args   Additional message part(s).
  #   @param [Symbol, nil]             topic
  #   @param [Hash]                    opt
  #
  # @overload flash_format(error, *args, topic: nil, **opt)
  #   @param [ExecReport, Exception]   error  Error (message) if :alert.
  #   @param [Array<String,FlashPart>] args   Additional message part(s).
  #   @param [Symbol, nil]             topic
  #   @param [Hash]                    opt
  #
  # @overload flash_format(meth, *args, topic: nil, **opt)
  #   @param [Symbol]                  meth   Calling method.
  #   @param [Array<String,FlashPart>] args   Additional message part(s).
  #   @param [Symbol, nil]             topic
  #   @param [Hash]                    opt
  #
  # @overload flash_format(*args, topic: nil, **opt)
  #   @param [Array<String,FlashPart>] args   Additional message part(s).
  #   @param [Symbol, nil]             topic
  #   @param [Hash]                    opt
  #
  def flash_format: (*flashArg args, ?topic: Symbol|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | String)

  # Create item(s) to be included in the flash display.
  #
  # @param [String, Array, FlashPart] item
  # @param [Hash]                     opt
  #
  # @option opt [Boolean] :inspect  If *true* show inspection of *item*.
  # @option opt [Boolean] :html     If *true* force ActiveSupport::SafeBuffer.
  # @option opt [Integer] :max      See below.
  #
  # @return [ActiveSupport::SafeBuffer]   If *item* is HTML or *html* is true.
  # @return [String]                      If *item* is not HTML.
  # @return [Array]                       If *item* is an array.
  #
  # -
  # === Variations
  # +
  #
  # @overload flash_item(string, max: FLASH_MAX_ITEM_SIZE, **opt)
  #   Create a single flash item which conforms to the maximum per-item size.
  #   @param [ActiveSupport::SafeBuffer, String] string
  #   @return [ActiveSupport::SafeBuffer, String]
  #   @return [ActiveSupport::SafeBuffer]               If :html is *true*.
  #
  # @overload flash_item(array, max: FLASH_MAX_TOTAL_SIZE, **opt)
  #   Create a set of flash items which conforms to the overall maximum size.
  #   @param [Array<ActiveSupport::SafeBuffer,String>] array
  #   @return [Array<ActiveSupport::SafeBuffer,String>]
  #   @return [Array<ActiveSupport::SafeBuffer>]        If :html is *true*.
  #
  def flash_item
    : (Array[String|FlashPart] array,  **untyped opt) -> Array[ActiveSupport::SafeBuffer|String]
    | ((String|FlashPart)      string, **untyped opt) -> (ActiveSupport::SafeBuffer | String)

  # An item's actual impact toward the total flash size.
  #
  # @param [String, Array<String>] item
  # @param [Boolean]               html
  #
  # @return [Integer]
  #
  # === Usage Notes
  # This does not account for any separators that would be added when
  # displaying multiple items.
  #
  def flash_item_size: ((String|strArray) item, ?html: bool) -> Integer

  # Render an item in the intended form for addition to the flash.
  #
  # @param [String, FlashPart] item
  # @param [Boolean, nil]      html     Force ActiveSupport::SafeBuffer.
  # @param [Boolean, nil]      xhr
  # @param [Boolean, nil]      inspect  Show inspection of *item*.
  # @param [Integer, nil]      max      Max length of result.
  #
  # @return [String]                    If *html* is *false*.
  # @return [ActiveSupport::SafeBuffer] If *html* is *true*.
  #
  def flash_item_render: ((String|FlashPart) item, ?html: bool|nil, ?xhr: bool|nil, ?inspect: bool|nil, ?max: Integer|nil) -> (ActiveSupport::SafeBuffer | String)

  # If a :topic was specified, it is used as part of a set of I18n paths used
  # to locate a template to which the flash message is applied.
  #
  # @param [String, Array<String>] msg
  # @param [Symbol, String]        topic
  # @param [Symbol, String, nil]   meth
  # @param [Boolean, nil]          html
  # @param [String, nil]           separator
  # @param [Hash]                  opt        Passed to I18n#t.
  #
  # @return [String]                          # Even if html is *true*.
  #
  def flash_template: ((String|strArray) msg, topic: Symbol|String, ?meth: Symbol|String|nil, ?html: bool|nil, ?separator: String|nil, **untyped opt) -> String

  # I18n scope based on the current class context.
  #
  # @return [String]
  #
  def flash_i18n_scope: () -> String

  # Build an I18n path.
  #
  # @param [Array<String,Symbol,nil,Array>] parts
  #
  # @return [Symbol]
  #
  def flash_i18n_path: (*(Array[String|Symbol|nil]|String|Symbol|nil) parts) -> Symbol

  private

  def self.included: (Module base) -> void
end
