# HTTP utilities.
#
module HttpHelper
  # A mapping of status ranges to their related HTTP statuses.
  #
  # @type [Hash{Symbol=>Array,Range}]
  #
  HTTP_STATUS_CODE_RANGE: Hash[Symbol,(Array[Integer]|Range[Integer])]

  # A mapping of HTTP status to its symbolic form.
  #
  # @type [Hash{Integer=>Symbol}]
  #
  HTTP_STATUS_CODE_TO_SYMBOL: Hash[Integer,Symbol]

  # A mapping of status ranges to their related symbolic HTTP statuses.
  #
  # @type [Hash{Symbol=>Array<Symbol>}]
  #
  HTTP_SYMBOLIC_CODE_RANGE: Hash[Symbol,symArray]

  # Indicate whether the value represents an HTTP status code which is part of
  # the given named range.
  #
  # @param [Symbol]   range
  # @param [any, nil] code            Symbol, Integer
  #
  def http_status?: (Symbol range, untyped code) -> bool

  # Indicate whether the value represents an HTTP 1xx status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  # @note Currently unused.
  #
  def http_info?: (untyped code) -> bool

  # Indicate whether the value represents an HTTP 2xx status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  def http_success?: (untyped code) -> bool

  # Indicate whether the value represents an HTTP 3xx status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  def http_redirect?: (untyped code) -> bool

  # Indicate whether the value represents an HTTP 301, 303 or 308 status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  # @note Currently unused.
  #
  def http_permanent_redirect?: (untyped code) -> bool

  # Indicate whether the value represents an HTTP 302 or 307 status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  def http_temporary_redirect?: (untyped code) -> bool

  # Indicate whether the value represents a failure HTTP status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  # @note Currently unused.
  #
  def http_error?: (untyped code) -> bool

  # Indicate whether the value represents an HTTP 4xx status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  # @note Currently unused.
  #
  def http_client_error?: (untyped code) -> bool

  # Indicate whether the value represents an HTTP 5xx status.
  #
  # @param [any, nil] code            Symbol, Integer
  #
  # @note Currently unused.
  #
  def http_server_error?: (untyped code) -> bool

  private

  def self.included: (Module base) -> void
end
