# Methods supporting I18n lookup.
#
module I18nHelper
  # Parse ERB within the item found at the given config location.
  #
  # @param [String] path
  # @param [Hash]   opt               Passed to I18n#translate.
  #
  # @return [Any]
  #
  def i18n_erb: (String path, **untyped opt) -> untyped

  # Interpret ERB.
  #
  # @param [Any]                              val
  # @param [Thread::Backtrace::Location, nil] loc
  #
  # @return [Any]
  #
  def erb_interpolate: (untyped val, ?(Thread::Backtrace::Location|nil) loc) -> untyped

  private

  # Interpret ERB within a string.
  #
  # @param [String]                           str
  # @param [Thread::Backtrace::Location, nil] loc
  #
  # @return [String]
  #
  def erb_process: (String str, ?(Thread::Backtrace::Location|nil) loc) -> String

  def self.included: (Module base) -> void
end
