# Support methods for working with authorization roles.
#
module RoleHelper
  include Emma::Common

  # Indicate whether the current user has the :developer role.
  #
  # == Implementation Notes
  # Currently the :developer role applies regardless of the model.
  #
  def developer?: () -> bool

  # Indicate whether the current user has the :administrator role.
  #
  def administrator?: () -> bool

  # Indicate whether the (current) user has the given role or role prototype.
  #
  # If *role* is blank then the method always returns *true*.
  #
  # @param [Symbol, String, nil] role
  # @param [User, nil]           user   Default: `current_user`.
  #
  def user_has_role?: ((Symbol|String|nil) role, ?(User|nil) user) -> bool

  private

  def self.included: (Module base) -> void
end
