# View helper support methods related to `#session`.
#
module SessionDebugHelper
  include DevHelper

  include GridHelper

  include IdentityHelper

  include ParamsHelper

  include SysHelper

  # Indicate whether on-screen debugging is applicable.
  #
  # @param [Symbol,String,nil] controller   Controller-specific debugging.
  #
  def session_debug?: (?(Symbol|String|nil) controller) -> bool

  # Session keys that are not reported in the session debug table.
  #
  # @type [Array<String>]
  #
  SESSION_SKIP_KEYS: strArray

  # Request headers that are not reported in the session debug table.
  #
  # @type [Array<String>]
  #
  REQUEST_SKIP_HDRS: strArray

  # Render a table of values from `#session`.
  #
  # @param [Boolean] extended         If *true* show request headers.
  # @param [String]  css              Characteristic CSS class/selector.
  # @param [Hash]    opt              Passed to outer #html_div.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def session_debug: (?extended: bool, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  private

  def self.included: (Module base) -> void
end
