# View helper methods related to authentication.
#
module SessionsHelper
  include IdentityHelper

  # Default sign-in tooltip.
  #
  # @type [String]
  #
  SIGN_IN_TOOLTIP: String

  # Default sign-out tooltip.
  #
  # @type [String]
  #
  SIGN_OUT_TOOLTIP: String

  # Link to sign-in options page.
  #
  # @param [String, nil]          label   Default: `#get_label(:new)`
  # @param [String, Boolean, nil] path    Default: `new_user_session_path`
  # @param [Hash]                 opt     Passed to #make_link except:
  #
  # @option opt [String, Symbol] :provider  Passed to #get_sessions_label.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # === Usage Notes
  # Use :path = *false* to disable without changing the appearance.
  #
  def sign_in_link: (?label: String|nil, ?path: String|bool|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Sign out link.
  #
  # @param [String]             label   Default: `#get_label(:destroy)`
  # @param [String, false, nil] path    Default: `destroy_user_session_path`
  # @param [Hash]               opt     Passed to #make_link except:
  #
  # @option opt [String, Symbol] :provider  Passed to #get_sessions_label.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # === Usage Notes
  # Use :path = *false* to disable without changing the appearance.
  #
  def sign_out_link: (?label: String|nil, ?path: String|false|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Get link label from the config/locales/controllers/user.en.yml.
  #
  # @param [String, Symbol]      action
  # @param [String, Symbol, nil] provider
  # @param [Hash]                opt        Passed to TranslationHelper#t.
  #
  # @return [String]
  #
  def get_sessions_label: ((Symbol|String) action, ?(Symbol|String|nil) provider, **untyped opt) -> String

  private

  def self.included: (Module base) -> void
end
