# API schema - EmmaRepository
#
# "Identifier for a repository"
#
# @see "en.emma.repository.*"
# @see https://api.swaggerhub.com/domains/bus/emma-federated-shared-components/0.0.6#/components/schemas/EmmaRepository  JSON schema specification
#
class EmmaRepository < EnumType
  # Partner repository configurations.
  #
  # @type [Hash{Symbol=>any}]
  #
  CONFIGURATION: symHash

  # The default repository for uploads.
  #
  # @type [String]
  #
  # @see "en.emma.repository._default"
  #
  DEFAULT: String

  # Values associated with each past or present source repository.
  #
  # @type [Hash{Symbol=>Hash}]
  #
  # @see "en.emma.repository"
  # @see https://api.swaggerhub.com/domains/bus/emma-federated-shared-components/0.0.6#/components/schemas/EmmaRepository  JSON schema specification
  #
  ENTRY: Hash[Symbol,symHash]

  # Values associated with each currently-active source repository.
  #
  # @type [Hash{Symbol=>Hash}]
  #
  # @see "en.emma.repository"
  # @see https://api.swaggerhub.com/domains/bus/emma-federated-shared-components/0.0.6#/components/schemas/EmmaRepository  JSON schema specification
  #
  ACTIVE: Hash[Symbol,symHash]

  # The repositories that require the "partner repository workflow".
  #
  # @type [Array<Symbol>]
  #
  PARTNER: symArray

  # The repositories that can handle "partner repository workflow" requests.
  #
  # If the repository is not also in #PARTNER then related
  # submissions are handled as EMMA-native, but with the additional step of
  # reflecting the submission in the S3 bucket.
  #
  # @type [Array<Symbol>]
  #
  S3_QUEUE: symArray

  # The repositories that represent EMMA publisher collections.
  #
  # @type [Array<Symbol>]
  #
  COLLECTION: symArray

  # The repositories whose items come from Internet Archive.
  #
  # @type [Array<Symbol>]
  #
  IA_HOSTED: symArray

  # The repositories that require the "partner repository workflow".
  #
  # @type [Array<Symbol>]
  #
  def self.partner: () -> symArray

  # The repositories that can handle "partner repository workflow" requests.
  #
  # If the repository is not also in #PARTNER then related
  # submissions are handled as EMMA-native, but with the additional step of
  # reflecting the submission in the S3 bucket.
  #
  # @type [Array<Symbol>]
  #
  def self.s3_queue: () -> symArray

  # The repositories that represent EMMA publisher collections.
  #
  # @type [Array<Symbol>]
  #
  def self.collection: () -> symArray

  # The repositories whose items come from Internet Archive.
  #
  # @type [Array<Symbol>]
  #
  def self.ia_hosted: () -> symArray

  # Indicate whether `*v*` represents a partner repository.
  #
  # @param [any, nil] v
  #
  def self.partner?: (untyped v) -> bool

  # Indicate whether `*v*` represents a repository that can handle
  # "partner repository workflow" requests.
  #
  # @param [any, nil] v
  #
  def self.s3_queue?: (untyped v) -> bool

  # Indicate whether `*v*` represents an EMMA publisher collection.
  #
  # @param [any, nil] v
  #
  def self.collection?: (untyped v) -> bool

  # Indicate whether `*v*` represents a repository hosted by Internet Archive.
  #
  # @param [any, nil] v
  #
  def self.ia_hosted?: (untyped v) -> bool

  # Indicate whether the instance is a partner repository.
  #
  # @param [any, nil] v               Default: #value.
  #
  def partner?: (untyped v) -> bool

  # Indicate whether the instance is a "partner repository workflow"
  # repository.
  #
  # @param [any, nil] v               Default: #value.
  #
  def s3_queue?: (untyped v) -> bool

  # Indicate whether the instance is an EMMA publisher collection.
  #
  # @param [any, nil] v               Default: #value.
  #
  def collection?: (?untyped v) -> bool

  # Indicate whether the instance is a repository hosted by Internet Archive.
  #
  # @param [any, nil] v               Default: #value.
  #
  def ia_hosted?: (?untyped v) -> bool
end
