# ISO 8601 year.
#
class IsoYear < IsoDate
  module Methods
    include IsoDate::Methods

    # Indicate whether `*v*` would be a valid value for an item of this type.
    #
    # @param [any, nil] v
    #
    def valid?: (untyped v) -> bool

    # Transform *v* into a valid form.
    #
    # @param [any, nil] v
    #
    # @return [String, nil]
    #
    def normalize: (untyped v) -> (String | nil)

    private

    def self.included: (Module base) -> void
  end

  include Methods

  # Indicate whether the instance is valid.
  #
  # @param [String, nil] v            Default: #value.
  #
  def valid?: (?untyped v) -> bool
end
