# API schema - RemediationFields - RemediationStatus
#
# @see "en.emma.type.search.RemediationStatus"
# @see https://api.swaggerhub.com/domains/bus/emma-federated-shared-components/0.0.5#/components/schemas/RemediationFields/rem_status   JSON schema specification
#
class RemediationStatus < EnumType
end
