# Role prototypes.
#
# A "role prototype" (or, more casually, "role") is associated with a set of
# one or more RoleCapability values which characterize the functionalities for
# which a user with the given role is authorized.
#
# @see "en.emma.type.ability.RolePrototype"
# @see Ability
#
class RolePrototype < EnumType
end
