# Emma::Config
#
module Emma::Config
  include Emma::Common

  # Load a YAML configuration file.
  #
  # @param [String, Pathname] path    Relative or absolute path to the file.
  # @param [Boolean]          erb     If *false* don't attempt ERB translation.
  #
  # @return [Hash{Symbol=>Any}]       Contents of the YAML file.
  # @return [nil]                     If there was a problem.
  #
  def self.load: (String|Pathname path, ?bool erb) -> symHash?
end
