# Emma::Project
#
module Emma::Project
  # The web site for project information.
  #
  # @type [String]
  #
  PROJECT_SITE: String

  # The email address for project information.
  #
  # @type [String]
  #
  PROJECT_EMAIL: String

  # The web site for the "emma-users" mailing list.
  #
  # @type [String]
  #
  MAILING_LIST_SITE: String

  # The email address for the "emma-users" mailing list.
  #
  # @type [String]
  #
  MAILING_LIST_EMAIL: String

  # The email address for general information.
  #
  # @type [String]
  #
  CONTACT_EMAIL: String

  # The email address for support.
  #
  # @type [String]
  #
  HELP_EMAIL: String

  # The email address for requesting EMMA enrollment.
  #
  # @type [String]
  #
  ENROLL_EMAIL: String
end
