# Emma::Project
#
module Emma::Project
  # The web site for project information.
  #
  # @type [String]
  #
  PROJECT_SITE: String

  # The email address for project information.
  #
  # @type [String]
  #
  PROJECT_EMAIL: String

  # The email address for support and general information.
  #
  # @type [String]
  #
  CONTACT_EMAIL: String
end
