# Overrides for JSON serializers.
#
# @see Api::Serializer::Json::Associations
#
module IaDownload::Api::Serializer::Json::Associations
  extend ActiveSupport::Concern

  include Api::Serializer::Json::Associations

  module ClassMethods
    include IaDownload::Api::Serializer::Json::Schema

    include Api::Serializer::Json::Associations::ClassMethods
  end
end
