# JSON-specific definition overrides for serialization.
#
# @see Api::Serializer::Json::Schema
#
module IaDownload::Api::Serializer::Json::Schema
  include IaDownload::Api::Serializer::Schema

  include Api::Serializer::Json::Schema
end
