# Bs::Record::Bookmark
#
# @attr [String]                           bookshareId
# @attr [IsoDate]                          dateAdded
# @attr [Bs::Record::Format]               format
# @attr [Array<Bs::Record::Link>]          links
# @attr [String]                           location
# @attr [Integer]                          position
# @attr [Float]                            progression
# @attr [String]                           text
# @attr [Float]                            totalProgression
#
# @see https://apidocs.bookshare.org/reference/index.html#_bookmark
#
class Bs::Record::Bookmark < Bs::Api::Record
  include Bs::Shared::LinkMethods
end
