# Bs::Record::ContributorName
#
# @attr [String]                  displayName
# @attr [String]                  indexName
# @attr [Array<Bs::Record::Link>] links
#
# @see https://apidocs.bookshare.org/reference/index.html#_contributor_name
#
class Bs::Record::ContributorName < Bs::Api::Record
  include Bs::Shared::LinkMethods

  # Convert object to string.
  #
  # @return [String]
  #
  def to_s: () -> String

  # A label for the item.
  #
  # @return [String]
  #
  def label: () -> String

  # Return the unique identifier for the represented item.
  #
  # @return [String]
  #
  def identifier: () -> String
end
