# Bs::Record::Narrator
#
# @attr [BsGender]       gender
# @attr [String]         name
# @attr [BsNarratorType] type
#
# @see https://apidocs.bookshare.org/reference/index.html#_narrator
#
class Bs::Record::Narrator < Bs::Api::Record
  # Convert object to string.
  #
  # @return [String]
  #
  def to_s: () -> String

  # A label for the item.
  #
  # @return [String]
  #
  def label: () -> String
end
