# Bs::Record::PeriodicalSeriesMetadataSummary
#
# @attr [Array<Bs::Record::Category>]          categories
# @attr [Array<String>]                        countries
# @attr [String]                               description
# @attr [Integer]                              editionCount
# @attr [String]                               externalCategoryCode
# @attr [String]                               issn
# @attr [Array<String>]                        languages
# @attr [Bs::Record::PeriodicalEditionSummary] latestEdition
# @attr [Array<Bs::Record::Link>]              links
# @attr [String]                               publisher
# @attr [String]                               seriesId
# @attr [BsSeriesType]                         seriesType
# @attr [String]                               title
#
# @see https://apidocs.bookshare.org/reference/index.html#_periodical_series_metadata_summary
#
class Bs::Record::PeriodicalSeriesMetadataSummary < Bs::Api::Record
  include Bs::Shared::LinkMethods

  include Bs::Shared::PeriodicalMethods
end
