# Bs::Record::PeriodicalSubscription
#
# @attr [IsoDate]                                     dateSubscribed
# @attr [BsPeriodicalFormat]                          format
# @attr [Array<Bs::Record::Link>]                     links
# @attr [Bs::Record::PeriodicalSeriesMetadataSummary] periodical
#
# @see https://apidocs.bookshare.org/reference/index.html#_periodical_subscription
#
class Bs::Record::PeriodicalSubscription < Bs::Api::Record
  include Bs::Shared::ArtifactMethods

  include Bs::Shared::LinkMethods
end
