# Bs::Record::PopularListSummary
#
# @attr [String]                  description
# @attr [String]                  id
# @attr [Array<Bs::Record::Link>] links
#
# @see https://apidocs.bookshare.org/reference/index.html#_popular_list_summary
#
class Bs::Record::PopularListSummary < Bs::Api::Record
  include Bs::Shared::LinkMethods
end
