# Bs::Record::Sponsor
#
# @attr [Boolean]                 allowAdultContent
# @attr [Boolean]                 canDownload
# @attr [Boolean]                 deleted
# @attr [String]                  emailAddress
# @attr [Boolean]                 hasAgreement
# @attr [String]                  language
# @attr [Array<Bs::Record::Link>] links
# @attr [Boolean]                 locked
# @attr [Bs::Record::Name]        name
# @attr [String]                  phoneNumber
# @attr [BsSiteType]               site
# @attr [String]                  title
#
# @see https://apidocs.bookshare.org/membership/index.html#_sponsor
#
class Bs::Record::Sponsor < Bs::Api::Record
  include Bs::Shared::AccountMethods

  include Bs::Shared::LinkMethods
end
