# Bs::Record::UsageRestriction
#
# @attr [String] name
# @attr [String] usageRestrictionId
#
# @see https://apidocs.bookshare.org/reference/index.html#_usage_restriction
#
class Bs::Record::UsageRestriction < Bs::Api::Record
  # Convert object to string.
  #
  # @return [String]
  #
  def to_s: () -> String

  # A label for the item.
  #
  # @return [String]
  #
  def label: () -> String

  # Return the unique identifier for this item.
  #
  # @return [String]
  #
  def identifier: () -> String
end
