# Bs::Record::UserPod
#
# @attr [BsDisabilityType] disabilityType
# @attr [String]           proofSource
#
# @see https://apidocs.bookshare.org/membership/index.html#_user_pod
#
class Bs::Record::UserPod < Bs::Api::Record
  # A label for the item.
  #
  # @return [String]
  #
  def label: () -> String
end
