# Bs::Record::UserSubscriptionType
#
# @attr [String] description
# @attr [String] name
#
# @see https://apidocs.bookshare.org/membership/index.html#_user_subscription_type
#
class Bs::Record::UserSubscriptionType < Bs::Api::Record
  # Convert object to string.
  #
  # @return [String]
  #
  def to_s: () -> String

  # A label for the item.
  #
  # @return [String]
  #
  def label: () -> String
end
