# Bs::Record::UserSubscription
#
# @attr [Bs::Record::DownloadTimeframe]    downloadTimeframe
# @attr [IsoDate]                          endDate
# @attr [Array<Bs::Record::Link>]          links
# @attr [String]                           notes
# @attr [Integer]                          numBooksAllowed
# @attr [IsoDate]                          startDate
# @attr [String]                           subscriptionId
# @attr [Bs::Record::UserSubscriptionType] userSubscriptionType
#
# @see https://apidocs.bookshare.org/membership/index.html#_user_subscription
#
class Bs::Record::UserSubscription < Bs::Api::Record
  include Bs::Shared::LinkMethods

  include Bs::Shared::SubscriptionMethods
end
