# The base class for serialization/de-serialization of objects derived from
# AwsS3::Api::Record.
#
class AwsS3::Api::Serializer < Api::Serializer
  include AwsS3::Api::Serializer::Schema

  include AwsS3::Api::Serializer::Associations
end
