module CodeStatisticsCalculatorExt
  # Replacement for Rails::CodeStatisticsCalculator#PATTERNS to include CSS.
  #
  # @type [Hash{Symbol=>Hash{Symbol=>Regexp}}]
  #
  PATTERNS: Hash[Symbol,Hash[Symbol,Regexp]]

  @lines:       Integer
  @classes:     Integer
  @methods:     Integer
  @code_lines:  Integer

  # This replacement addresses several issues:
  #
  # * Handles inline block comments for JavaScript.
  #
  # @param [File] io
  # @param [Symbol] file_type
  #
  # @return [void]
  #
  def add_by_io: (File io, String file_type) -> void
end
