module CodeStatisticsExt
  EXTENSIONS: symArray

  FILE_REGEX: Regexp

  NON_CODE: Array[Regexp|String]

  def calculate_directory_statistics: (String directory, ?(Regexp|String) pattern) -> CodeStatisticsCalculator

  def calculate_code: () -> Integer
end
