module OmniAuth
  class Configuration
    # Because OmniAuth::Configuration#defaults invokes this method
    # unconditionally, defining the local logger here in this override rather
    # than in 'config/initializers.rb' avoids creation of an extra unused
    # logger instance.
    #
    # @return [Emma::Logger]
    #
    def self.default_logger: () -> Emma::Logger
  end
end
