# OAuth2 negotiation.
#
# @see AUTH_PROVIDERS
# @see https://github.com/plataformatec/devise#omniauth
#
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include SessionConcern

  # == GET  /users/auth/PROVIDER
  # == POST /users/auth/PROVIDER
  #
  # Initiate authentication with the remote service.
  #
  # _see #user_bookshare_omniauth_authorize_path  Route helper                  # if BS_AUTH
  # @see #user_shibboleth_omniauth_authorize_path Route helper
  #
  def passthru: () -> void

  # == GET  /users/auth/bookshare/callback                                      # if BS_AUTH
  # == POST /users/auth/bookshare/callback
  #
  # Callback from the Bookshare auth service to finalize authentication.
  #
  # @see #user_bookshare_omniauth_callback_path   Route helper
  # @see AuthConcern#set_auth_data
  #
  def bookshare: () -> void

  # == GET  /users/auth/shibboleth/callback
  # == POST /users/auth/shibboleth/callback
  #
  # Callback from Shibboleth to finalize authentication.
  #
  # @see #user_shibboleth_omniauth_callback_path   Route helper
  # @see AuthConcern#set_auth_data
  #
  def shibboleth: () -> void

  # == GET /users/auth/PROVIDER/failure
  #
  # Called from OmniAuth::FailureEndpoint#redirect_to_failure and redirects to
  # Devise::OmniauthCallbacksController#after_omniauth_failure_path_for.
  #
  def failure: () -> void

  # Display a flash error message.
  #
  # @param [String, nil] message
  # @param [String, nil] provider
  #
  # @return [void]
  #
  def set_flash_alert: (?(String|nil) message, ?(String|nil) provider) -> void
end
