# Authentication provider negotiation.
#
# @see AUTH_PROVIDERS
# @see https://github.com/plataformatec/devise#omniauth
#
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include SessionConcern

  # === GET  /users/auth/PROVIDER
  # === POST /users/auth/PROVIDER
  #
  # Initiate authentication with the remote service.
  #
  # @see #user_shibboleth_omniauth_authorize_path Route helper
  #
  def passthru: () -> void

  # === GET  /users/auth/shibboleth/callback
  # === POST /users/auth/shibboleth/callback
  #
  # The callback from Shibboleth to finalize authentication.
  #
  # @see #user_shibboleth_omniauth_callback_path
  # @see AuthConcern#set_auth_data
  #
  def shibboleth: () -> void

  # === GET /users/auth/PROVIDER/failure
  #
  # Called from OmniAuth::FailureEndpoint#redirect_to_failure and redirects to
  # Devise::OmniauthCallbacksController#after_omniauth_failure_path_for.
  #
  def failure: () -> void
end
