# Individual EMMA account password maintenance.
#
# @see file:app/views/user/passwords/**
#
class User::PasswordsController < Devise::PasswordsController
  include FlashConcern

  include SessionConcern

  include RunStateConcern

  # == GET /users/password/new
  #
  def new: () -> void

  # == POST /users/password
  #
  def create: () -> void

  # == GET /users/password/edit[?reset_password_token=TOKEN]
  #
  def edit: () -> void

  # == PUT /users/password
  #
  def update: () -> void
end
