# User session controller.
#
# @see file:app/views/user/sessions/**
#
class User::SessionsController < Devise::SessionsController
  include ApiConcern

  include AuthConcern

  include SessionConcern

  include RunStateConcern

  # :nocov:
  #include AbstractController::Callbacks

  NO_AUTH: symArray

  PARAM_AUTH: symArray

  NO_TIMEOUT: symArray

  # === GET /users/sign_in
  #
  # Prompt the user for login credentials.
  #
  # @see #new_user_session_path       Route helper
  #
  def new: () -> void

  # === POST /users/sign_in
  #
  # Begin login session.
  #
  # @see #user_session_path           Route helper
  #
  def create: () -> void

  # === DELETE /users/sign_out[?revoke=(true|false)]
  #
  # End login session.
  #
  # If the "no_revoke" parameter is missing or "false" then the local session   # if BS_AUTH
  # is  ended _and_ its associated OAuth2 token is revoked.  If "no_revoke" is
  # "true" then only the local session is ended.
  #
  # @see #destroy_user_session_path   Route helper
  # @see AuthConcern#delete_auth_data
  #
  def destroy: () -> void

  # === GET /users/sign_in_local
  #
  # Sign in with an EMMA user account encrypted password.
  #
  # @see #sign_in_local_path          Route helper
  #
  def sign_in_local: () -> void

  # === GET /users/sign_in_as?uid=NAME&token=AUTH_TOKEN
  # === GET /users/sign_in_as?auth=(OmniAuth::AuthHash)
  #
  # Sign in using information supplied outside of the OAuth2 flow.
  #
  # @see #sign_in_as_path             Route helper
  # @see AuthConcern#local_sign_in
  #
  # === Usage Notes
  # The initial request to this endpoint is redirected by Warden::Manager to    # if BS_AUTH
  # OmniAuth::Strategies::Bookshare#request_call.  The second request is
  # performed from OmniAuth::Strategies::Bookshare#callback_phase which
  # provides the value for 'omniauth.auth'.
  #
  def sign_in_as: () -> void

  # Called to avoid timing-out waiting for credentials.
  #
  # @return [void]
  #
  def no_devise_timeout: () -> void
end
