# BookshareService::Request::AssignedTitles
#
# == Usage Notes
#
# === From API section 2.4 (Assigned Titles):
# Assigned titles are titles that have been assigned to an organization member
# by a sponsor of that organization.
#
module BookshareService::Request::AssignedTitles
  include BookshareService::Common

  include BookshareService::Testing

  # == GET /v2/myAssignedTitles
  #
  # == 2.4.1. Get my assigned titles
  # As an organization member, get titles that have been assigned to me.
  #
  # @param [Hash] opt                 Passed to #api.
  #
  # @option opt [String]                :start
  # @option opt [Integer]               :limit        Default: 10
  # @option opt [BsMyAssignedSortOrder] :sortOrder    Default: 'title'
  # @option opt [BsSortDirection]       :direction    Default: 'asc'
  #
  # @return [Bs::Message::TitleMetadataSummaryList]
  #
  # @see https://apidocs.bookshare.org/reference/index.html#_my-assigned-titles
  #
  def get_my_assigned_titles: (**untyped opt) -> Bs::Message::TitleMetadataSummaryList

  # == GET /v2/assignedTitles/(userIdentifier)
  #
  # == 2.4.2. Get titles assigned to an organization member
  # As a sponsor or Membership Assistant, get a list of titles that have been
  # assigned to a particular organization member.
  #
  # @param [User, String, nil] user   Default: `@user`.
  # @param [Hash]              opt    Passed to #api.
  #
  # @option opt [String]              :start
  # @option opt [Integer]             :limit        Default: 10
  # @option opt [BsAssignedSortOrder] :sortOrder    Default: 'title'
  # @option opt [BsSortDirection]     :direction    Default: 'asc'
  #
  # @return [Bs::Message::AssignedTitleMetadataSummaryList]
  #
  # @see https://apidocs.bookshare.org/reference/index.html#_titles-assigned-member
  #
  def get_assigned_titles: (?user: User|String|nil, **untyped opt) -> Bs::Message::AssignedTitleMetadataSummaryList

  # == POST /v2/assignedTitles/(userIdentifier)
  #
  # == 2.4.3. Assign a title to an organization member
  # As a sponsor or Membership Assistant, assign a specific title to a
  # particular organization member.
  #
  # @param [User, String, nil] user         Default: `@user`.
  # @param [String]            bookshareId
  # @param [Hash]              opt          Passed to #api.
  #
  # @return [Bs::Message::AssignedTitleMetadataSummaryList]
  #
  # @see https://apidocs.bookshare.org/reference/index.html#_title-assign
  #
  def create_assigned_title: (bookshareId: String, ?user: User|String|nil, **untyped opt) -> Bs::Message::AssignedTitleMetadataSummaryList

  # == DELETE /v2/assignedTitles/(userIdentifier)/(bookshareId)
  #
  # == 2.4.4. Un-assign a title for an organization member
  # As a sponsor or Membership Assistant, un-assign a specific title for a
  # particular organization member.
  #
  # @param [User, String, nil] user         Default: `@user`.
  # @param [String]            bookshareId
  # @param [Hash]              opt          Passed to #api.
  #
  # @return [Bs::Message::AssignedTitleMetadataSummaryList]
  #
  # @see https://apidocs.bookshare.org/reference/index.html#_title-unassign
  #
  def remove_assigned_title: (bookshareId: String, ?user: User|String|nil, **untyped opt) -> Bs::Message::AssignedTitleMetadataSummaryList
end
