# Metadata record schema for an item lookup.
#
# @attr [Array<DatePart>] date_parts
# @attr [DateTime]        date_time
# @attr [Integer]         timestamp
#
# @see https://api.crossref.org/swagger-ui/index.html#model-Date
#
class Lookup::Crossref::Record::Date < Lookup::Crossref::Api::Record
  include Lookup::Crossref::Shared::DateMethods
end
