# Lookup::Crossref::Record::Query
#
# @see https://api.crossref.org/swagger-ui/index.html#model-Query
#
class Lookup::Crossref::Record::Query < Lookup::Crossref::Api::Record
  include Lookup::Crossref::Shared::CommonMethods
end
