# Overrides for XML serializers.
#
# @see Lookup::RemoteService::Api::Serializer::Xml::Associations
#
module Lookup::Crossref::Api::Serializer::Xml::Associations
  extend ActiveSupport::Concern

  include Lookup::RemoteService::Api::Serializer::Xml::Associations

  module ClassMethods
    include Lookup::Crossref::Api::Serializer::Xml::Schema

    include Lookup::RemoteService::Api::Serializer::Xml::Associations::ClassMethods
  end
end
