# Methods mixed in to record elements related to catalog titles.
#
module Lookup::GoogleBooks::Shared::TitleMethods
  include Lookup::RemoteService::Shared::TitleMethods
  include Lookup::GoogleBooks::Shared::IdentifierMethods

  # A unique identifier for this catalog title.
  #
  # @return [String, nil]
  #
  def identifier: () -> (String | nil)

  # Field(s) that may hold the title string.
  #
  # @return [Array<Symbol>]
  #
  def title_fields: () -> symArray

  # Field(s) that may hold the subtitle string.
  #
  # @return [Array<Symbol>]
  #
  def subtitle_fields: () -> symArray

  # One or more title strings.
  #
  # @return [Array<String>]
  #
  def title_values: () -> strArray

  # One or more subtitle strings.
  #
  # @return [Array<String>]
  #
  def subtitle_values: () -> strArray

  # Name of publisher.
  #
  # @return [String, nil]
  #
  def publisher_name: () -> (String | nil)

  # The date of publication.
  #
  # @return [String, nil]
  #
  def publication_date: () -> (String | nil)

  # The year of publication.
  #
  # @return [String, nil]
  #
  def publication_year: () -> (String | nil)

  # language_list
  #
  # @return [Array<String>]
  #
  def language_list: () -> strArray

  # subject_list
  #
  # @return [Array<String>]
  #
  def subject_list: () -> strArray

  # description_list
  #
  # @return [Array<String>]
  #
  def description_list: () -> strArray
end
