# Generic exception for Google Search API problems.
#
# === Usage Notes
# This is generally *not* the base class for exceptions in the Crossref
# namespace:  Variants based on the error types defined under "emma.error.api"
# are derived from the related ApiService class; e.g.:
#
#   `LookupService::Crossref::AuthError < ApiService::AuthError`
#
# Only a distinct error type defined under "emma.error.search" would derive
# from this class; e.g. if "emma.error.lookup.google_search.unique" existed it
# would be defined as:
#
#   `LookupService::Crossref::UniqueError < LookupService::Crossref::Error`
#
# An exception in the Crossref namespace can be identified by checking for
# `exception.is_a?(LookupService::Crossref::Error::ClassType)`.
#
class LookupService::Crossref::Error < ApiService::Error
  # Methods included in related error classes.
  #
  module ClassType
    include ApiService::Error::ClassType

    # Name of the service and key into config/locales/error.en.yml.
    #
    # @return [Symbol]
    #
    def service: () -> Symbol

    private

    def self.included: (Module base) -> void
  end

  include ClassType
end

class LookupService::Crossref::AuthError < ApiService::AuthError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::CommError < ApiService::CommError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::SessionError < ApiService::SessionError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::ConnectError < ApiService::ConnectError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::TimeoutError < ApiService::TimeoutError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::XmitError < ApiService::XmitError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::RecvError < ApiService::RecvError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::ParseError < ApiService::ParseError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::RequestError < ApiService::RequestError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::NoInputError < ApiService::NoInputError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::ResponseError < ApiService::ResponseError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::EmptyResultError < ApiService::EmptyResultError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::HtmlResultError < ApiService::HtmlResultError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::RedirectionError < ApiService::RedirectionError
  include LookupService::Crossref::Error::ClassType
end

class LookupService::Crossref::RedirectLimitError < ApiService::RedirectLimitError
  include LookupService::Crossref::Error::ClassType
end
