# Control record tracking queueing submission to an AWS S3 bucket.
#
# @see file:config/locales/state_table.en.yml *en.emma.state_table.action.batch_queue*
#
# @!method started?
# @!method submitting?
# @!method unretrieved?
# @!method retrieved?
# @!method canceled?
# @!method aborted?
#
# @!method started!
# @!method submitting!
# @!method unretrieved!
# @!method retrieved!
# @!method canceled!
# @!method aborted!
#
class Action::BatchQueue < Action::BulkOperation
  include Record::Sti::Leaf

  include Record::Steppable

  # Enqueue items to the appropriate AWS S3 bucket.
  #
  # @param [Array] items
  # @param [Hash]  opt
  #
  # @option opt [Boolean] :async      If *true* run callback asynchronously.
  # @option opt [Symbol]  :meth       Name of caller (for logging).
  #
  # @return [Boolean]
  #
  def submit!: (untyped items, **untyped opt) -> bool

  # A textual description of the type of the Model instance.
  #
  # @return [String]
  #
  def self.describe_type: (*untyped, **untyped) ?{ () -> untyped } -> String

  # A textual description of the status of the Action instance.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [String]
  #
  def self.describe_status: (Action action, **untyped opt) -> String
end
