# Upload items' files to AWS S3.
#
# @see file:config/locales/state_table.en.yml *en.emma.state_table.action.batch_store*
#
# @!method started?
# @!method storing?
# @!method stored?
# @!method canceled?
# @!method aborted?
#
# @!method started!
# @!method storing!
# @!method stored!
# @!method canceled!
# @!method aborted!
#
class Action::BatchStore < Action::BulkOperation
  include Record::Sti::Leaf

  include Record::Steppable

  include Record::Uploadable

  # Store items' files to AWS S3 :cache via Shrine.
  #
  # @param [Array] items
  # @param [Hash]  opt
  #
  # @option opt [Boolean] :update_record  If *false* caller will update record.
  # @option opt [Boolean] :auto_retry     If *true* automatically retry.
  # @option opt [Boolean] :async          If *true* run callback asynchronously
  # @option opt [Symbol]  :meth           Name of caller (for logging).
  #
  # @return [Boolean]
  #
  def store!: (untyped items, **untyped opt) -> bool

  # A textual description of the type of the Model instance.
  #
  # @return [String]
  #
  def self.describe_type: (*untyped) ?{ () -> untyped } -> String

  # A textual description of the status of the Action instance.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [String]
  #
  def self.describe_status: (Action action, **untyped opt) -> String
end
