# Add or update entries in the Unified Index.
#
# @see file:config/locales/state_table.en.yml *en.emma.state_table.action.batch_index*
#
# @!method started?
# @!method indexing?
# @!method indexed?
# @!method canceled?
# @!method aborted?
#
# @!method started!
# @!method indexing!
# @!method indexed!
# @!method canceled!
# @!method aborted!
#
class Action::BatchIndex < Action::BulkOperation
  include Record::Sti::Leaf

  include Record::Steppable

  # Add items to the Unified Index.
  #
  # @param [Array] items
  # @param [Hash]  opt
  #
  # @option opt [Boolean] :async      If *true* run callback asynchronously.
  # @option opt [Symbol]  :meth       Name of caller (for logging).
  #
  # @return [Boolean]
  #
  def index!: (untyped items, **untyped opt) -> bool

  # A textual description of the type of the Model instance.
  #
  # @return [String]
  #
  def self.describe_type: (*untyped, **untyped) ?{ () -> untyped } -> String

  # A textual description of the status of the Action instance.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [String]
  #
  def self.describe_status: (Action action, **untyped opt) -> String
end
