# Remove items' files uploaded to AWS S3 storage.
#
# @see file:config/locales/state_table.en.yml *en.emma.state_table.action.batch_un_store*
#
# @!method started?
# @!method unstoring?
# @!method completed?
# @!method canceled?
# @!method aborted?
#
# @!method started!
# @!method unstoring!
# @!method completed!
# @!method canceled!
# @!method aborted!
#
class Action::BatchUnStore < Action::BulkOperation
  include Record::Sti::Leaf

  include Record::Steppable

  include Record::Uploadable

  # Remove the uploaded file associated with this item.
  #
  # @param [Array] items
  # @param [Hash]  opt
  #
  # @option opt [Boolean] :async      If *true* run callback asynchronously.
  # @option opt [Symbol]  :meth       Name of caller (for logging).
  #
  # @return [Boolean]
  #
  def unstore!: (untyped items, **untyped opt) -> bool

  # A textual description of the type of the Model instance.
  #
  # @return [String]
  #
  def self.describe_type: (*untyped _ignored) ?{ () -> untyped } -> String

  # A textual description of the status of the Action instance.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [String]
  #
  def self.describe_status: (Action action, **untyped opt) -> String
end
