# Remove item from the database.
#
# @see file:config/locales/state_table.en.yml *en.emma.state_table.action.un_record*
#
# @!method started?
# @!method removing?
# @!method completed?
# @!method canceled?
# @!method aborted?
#
# @!method started!
# @!method removing!
# @!method completed!
# @!method canceled!
# @!method aborted!
#
class Action::UnRecord < Action::BulkPart
  include Record::Sti::Leaf

  include Record::Steppable

  # Remove the item from the database.
  #
  # @param [Hash] opt
  #
  # @option opt [Boolean] :async      If *true* run callback asynchronously.
  # @option opt [Symbol]  :meth       Name of caller (for logging).
  #
  # @return [Boolean]
  #
  def remove!: (**untyped opt) -> bool

  # A textual description of the type of the Model instance.
  #
  # @return [String]
  #
  def self.describe_type: (*untyped _ignored) ?{ () -> untyped } -> String

  # A textual description of the status of the Action instance.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [String]
  #
  def self.describe_status: (Action action, **untyped opt) -> String
end
