# Shared view helper methods supporting general page layout.
#
module LayoutHelper::Common
  include Emma::Common

  include Emma::Constants

  include FormHelper

  include HtmlHelper

  include SearchTermsHelper

  # If the client is responsible for managing hidden inputs on forms then they
  # should not be generated via #search_form.
  #
  # @type [Boolean]
  #
  CLIENT_MANAGES_HIDDEN_INPUTS: bool

  # A form used to create/modify a search.
  #
  # @param [Symbol, String, nil] target
  # @param [Symbol, String, nil] id       @note [1]
  # @param [Hash, nil]           hidden   note [1]
  # @param [Hash]                opt      Passed to #html_form.
  #
  # @return [ActiveSupport::SafeBuffer]   An HTML form element.
  # @return [nil]                         Search is not available for *target*.
  #
  # @yield To supply additional field(s) for the '<form>'.
  # @yieldreturn [String, Array<String>]
  #
  # @note [1] If #CLIENT_MANAGES_HIDDEN_INPUTS then id and hidden are ignored.
  #
  def search_form: ((Symbol|String|nil) target, ?(Symbol|String|nil) id, ?hidden: anyHash|nil, **untyped opt) ?{ () -> (String|strArray) } -> (ActiveSupport::SafeBuffer | nil)

  # A form used to create/modify a search.
  #
  # When searching via the indicated *target*, and *id* is supplied then the
  # current URL parameters are included as hidden fields so that the current
  # search is repeated but augmented with the added parameter.
  #
  # Otherwise a new search is assumed.
  #
  # @param [Symbol, String, nil] target
  # @param [Symbol, String, nil] id       Passed to #hidden_parameter_for.
  # @param [Hash, nil]           hidden   Passed to #hidden_parameter_for.
  # @param [Hash]                opt      Passed to #html_form.
  #
  # @return [ActiveSupport::SafeBuffer]   An HTML form element.
  # @return [nil]                         Search is not available for *target*.
  #
  # @yield To supply additional field(s) for the '<form>'.
  # @yieldreturn [String, Array<String>]
  #
  # @note Used only if #CLIENT_MANAGES_HIDDEN_INPUTS is false.
  #
  def search_form_with_hidden: ((Symbol|String|nil) target, ?(Symbol|String|nil) id, ?hidden: anyHash|nil, **untyped opt) { () -> (String|strArray) } -> (ActiveSupport::SafeBuffer | nil)

  # The target path for searches from the search bar.
  #
  # @param [Symbol, String, nil] target   Default: #DEFAULT_SEARCH_CONTROLLER
  # @param [Hash]                opt      Passed to #url_for.
  #
  # @return [String]
  #
  def search_target_path: (?(Symbol|String|nil) target, **untyped opt) -> String
end
