# View helper methods for the page '<footer>'.
#
module LayoutHelper::Footer
  include LayoutHelper::Common

  include GridHelper

  # Render a table of values from `#session`.
  #
  # @param [Hash] opt                 Passed to outer #html_div.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def footer_table: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Content for the footer.
  #
  # @param [Hash] opt
  #
  # @return [Hash]
  #
  def footer_items: (**untyped opt) -> symHash
end
