# View helper methods for the '<header>' search filter controls.
#
module LayoutHelper::SearchFilters
  include LayoutHelper::Common

  include HtmlHelper

  include GridHelper

  include ParamsHelper

  include SearchModesHelper

  module ClassMethods
    include Emma::Common

    include HtmlHelper

    # Get the search menu configuration for the current context.
    #
    # @param [Symbol, String] menu_name
    # @param [Hash, nil]      properties
    #
    # @return [Hash]
    #
    def search_menu_config: ((Symbol|String) menu_name, (symHash|nil) properties) -> symHash

    # current_menu_config
    #
    # @param [Symbol, String]      menu_name
    # @param [Symbol, String, nil] target     Target search controller.
    #
    # @return [Hash]
    #
    # @see #search_menu_map
    #
    def current_menu_config: ((Symbol|String) menu_name, ?target: Symbol|String|nil, **untyped _ignored) -> symHash

    # Generate an array of label/value pairs to be used with #select_tag.
    #
    # @param [Symbol] menu_name
    # @param [Hash, String, Symbol, Class, Array<Array>] values
    # @param [Hash]   opt             Passed to #make_menu_label.
    #
    # @return [Array<Array(String,String)>]
    #
    # @overload make_menu(menu_name, entries, **opt)
    #   @param [Symbol]        menu_name
    #   @param [Hash]          entries      Configuration information.
    #   @param [Hash]          opt
    #
    # @overload make_menu(menu_name, i18n_scope, **opt)
    #   @param [Symbol]        menu_name
    #   @param [String]        i18n_scope
    #   @param [Hash]          opt
    #
    # @overload make_menu(menu_name, enum_type, **opt)
    #   @param [Symbol]        menu_name
    #   @param [Symbol]        enum_type    Passed to EnumType.pairs_for.
    #   @param [Hash]          opt
    #
    # @overload make_menu(menu_name, enum_class, **opt)
    #   @param [Symbol]        menu_name
    #   @param [Class]         enum_class
    #   @param [Hash]          opt
    #
    # @overload make_menu(menu_name, menu_pairs, **opt)
    #   @param [Symbol]        menu_name
    #   @param [Array<Array>]  menu_pairs
    #   @param [Hash]          opt
    #
    def make_menu: (Symbol menu_name, (String|Symbol|Class|symHash|Array[[untyped,untyped]]) values, **untyped opt) -> Array[[String,String]]

    # Format a menu label.
    #
    # @param [Symbol, String] menu_name
    # @param [String]         label       Original label text.
    # @param [Hash]           opt         Passed to #current_menu_config except
    #
    # @option opt [Symbol] :fmt           One of:
    #
    #   *nil*       No formatting.
    #   *false*     No formatting.
    #   :none       No formatting.
    #   :titleize   Format in "title case".
    #   :upcase     Format as all uppercase.
    #   :downcase   Format as all lowercase.
    #   Symbol      Other String method.
    #   *true*      Use :menu_format configuration value.
    #   (missing)   Use :menu_format configuration value.
    #
    # @return [String]
    #
    # === Usage Notes
    # This method is only engaged for menus with values that are not backed by
    # configuration information that maps values to labels.
    #
    def make_menu_label: ((Symbol|String) menu_name, String label, **untyped opt) -> String

    # The names and base properties of all of the search control menus.
    #
    # @return [Hash]
    #
    def search_menu_base: () -> symHash

    @search_menu_base: symHash

    # Search control menu configurations for each controller configured to
    # display them.
    #
    # @return [Hash{Symbol=>Hash}]
    #
    def search_menu_map: () -> Hash[Symbol,symHash]

    @search_menu_map: Hash[Symbol,symHash]

    # Per-controller tables of the menu configurations associated with each
    # :url_param value.
    #
    # @return [Hash{Symbol=>Hash}]
    #
    def search_parameter_menu_map: () -> Hash[Symbol,symHash]

    @search_parameter_menu_map: Hash[Symbol,symHash]

    # Create reverse sort entries.
    #
    # @param [Array<Array<String,String>>] pairs
    # @param [Hash]                        config
    #
    # @return [Array<Array<String,String>>]
    #
    def add_reverse_pairs: (Array[[String,String]] pairs, symHash config) -> Array[[String,String]]

    # Indicate whether a :sort value is a reversed (descending) sort.
    #
    # @param [String, Symbol] value   A :sort key.
    # @param [String]         suffix
    #
    # @note Currently unused.
    #
    def is_reverse?: (String|Symbol|nil value, ?String suffix) -> bool

    # Change a :sort value to indicate a normal (ascending) sort.
    #
    # @param [String, Symbol] value   Base :sort key.
    # @param [String]         suffix
    #
    # @return [String, nil]
    #
    # @note Currently unused.
    #
    def ascending_sort: (String|Symbol|nil value, ?String suffix) -> (String | nil)

    # Change a :sort value to indicate a reversed (descending) sort.
    #
    # @param [String, Symbol] value   Base :sort key.
    # @param [String]         suffix
    #
    # @return [String, nil]
    #
    def descending_sort: (String|Symbol|nil value, ?String suffix) -> (String | nil)

    private

    def self.included: (Module base) -> void
  end

  include ClassMethods

  # The names and properties of all of the search filter menus and default
  # values.
  #
  # TODO: resolve bias toward :search controller
  #
  # @type [Hash{Symbol=>Hash}]
  #
  SEARCH_FILTERS_ROOT: Hash[Symbol,symHash]

  # The value "en.emma.page.search.search_filters._default" contains each of
  # the properties that can be expressed for a menu.  If a property there has a
  # non-nil value, then that value is used as the default for that property.
  #
  # @type [Hash]
  #
  SEARCH_MENU_DEFAULT: symHash

  # Properties for the "filter reset" button.
  #
  # @type [Hash]
  #
  # @see #reset_menu
  #
  SEARCH_RESET_CONTROL: symHash

  # Search filter configurations for each controller where they are enabled.
  #
  # @type [Hash{Symbol=>Hash}]
  #
  SEARCH_FILTERS_CONFIG: Hash[Symbol,symHash]

  # Indicate whether the search control panel starts in the open state.
  #
  # @type [Boolean]
  #
  SEARCH_FILTERS_START_EXPANDED: bool

  # Configuration for advanced search values.
  #
  # @type [Hash{Symbol=>Hash}]
  #
  ADV_SEARCH_CONFIG: Hash[Symbol,symHash]

  # Labels/tooltips for expanding and contracting search filters.
  #
  # @type [Hash{Symbol=>Hash{Symbol=>String,ActiveSupport::SafeBuffer}}]
  #
  ADV_SEARCH: Hash[Symbol,Hash[Symbol,String|ActiveSupport::SafeBuffer]]

  # Indicate whether it is appropriate to show the search filter controls.
  #
  # @param [Hash, nil] opt            Default: `#request_parameters`.
  #
  def show_search_filters?: (?(symHash|nil) opt) -> bool

  # One or more rows of search filter controls.
  #
  # @param [String, Symbol] target        Default: `#search_target`.
  # @param [Hash]           opt           Passed to #html_div.
  #
  # @return [ActiveSupport::SafeBuffer]   An HTML element.
  # @return [nil]                         No controls were found for *target*.
  #
  # @see "en.emma.page.*.search_filters"
  # @see #blank_menu
  # @see #sort_menu
  # @see #size_menu
  # @see #repository_menu
  # @see #prefix_limit_menu
  # @see #deployment_menu
  # @see #generic_menu
  # @see #before_menu
  # @see #after_menu
  # @see #reset_menu
  #
  def search_filter_container: (?target: String|Symbol|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # A control for toggling the visibility of advanced search filter controls.
  #
  # @param [String] css               Characteristic CSS class/selector.
  # @param [Hash]   opt               Passed to #button_tag.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def advanced_search_button: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # A hidden HTML elements which indicates that the page has been constructed
  # with search filters which cause a new search whenever a value is selected.
  #
  # @param [String] css               Characteristic CSS class/selector.
  # @param [Hash]   opt
  #
  # @return [ActiveSupport::SafeBuffer]
  # @return [nil]
  #
  def immediate_search_marker: (?css: String|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Options consumed by internal methods which should not be passed on along to
  # the methods which generate HTML elements.
  #
  # @type [Array<Symbol>]
  #
  # @see GridHelper#GRID_OPT
  #
  MENU_OPT: symArray

  # An empty placeholder for a menu position.
  #
  # @param [Hash] opt                 Passed to #menu_spacer.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def blank_menu: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Perform a search specifying a collation order for the results.
  # (Default: `params[:sort]`.)
  #
  # @param [Symbol] menu_name           Control name (should be :sort).
  # @param [Hash]   opt                 Passed to #menu_container.
  #
  # @return [ActiveSupport::SafeBuffer] An HTML element.
  # @return [nil]                       Menu is not available in this context.
  #
  # @see ParamsConcern#save_search_menus
  #
  def sort_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Perform a search specifying a results page size.
  #
  # @param [Symbol] menu_name           Control name (should be :size).
  # @param [Hash]   opt                 Passed to #menu_container.
  #
  # @return [ActiveSupport::SafeBuffer] An HTML element.
  # @return [nil]                       Menu is not available in this context.
  #
  # @see Paginator#page_size
  #
  def size_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Filter on repository.
  #
  # @param [Symbol] menu_name           Control name (should be :repository).
  # @param [Hash]   opt                 Passed to #menu_container.
  #
  # @return [ActiveSupport::SafeBuffer] An HTML element.
  # @return [nil]                       Menu is not available in this context.
  #
  def repository_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Specify initial number of entries per object key.
  #
  # @param [Symbol] menu_name           Control name (should be :prefix_limit).
  # @param [Hash]   opt                 Passed to #menu_container.
  #
  # @return [ActiveSupport::SafeBuffer] An HTML element.
  # @return [nil]                       Menu is not available in this context.
  #
  def prefix_limit_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Filter on deployment.
  #
  # @param [Symbol] menu_name           Control name (should be :deployment).
  # @param [Hash]   opt                 Passed to #menu_container.
  #
  # @return [ActiveSupport::SafeBuffer] An HTML element.
  # @return [nil]                       Menu is not available in this context.
  #
  def deployment_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Any menu without a specific method.
  #
  # @param [Symbol] menu_name           Control name.
  # @param [Hash]   opt                 Passed to #menu_container.
  #
  # @return [ActiveSupport::SafeBuffer] An HTML element.
  # @return [nil]                       Menu is not available in this context.
  #
  def generic_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  private

  # A menu control preceded by a menu label (if provided).
  #
  # @param [Symbol]              menu_name  Control name.
  # @param [String, nil]         label      Label text passed to #menu_label.
  # @param [String, Symbol, nil] target     Search target controller.
  # @param [Hash]                opt        Passed to #menu_control.
  #
  # @return [ActiveSupport::SafeBuffer]     HTML label and control elements.
  # @return [nil]                           Menu is not available for *target*.
  #
  def menu_container: (Symbol menu_name, ?label: String|nil, ?target: String|Symbol|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # A dropdown menu element.
  #
  # If *selected* is not specified `#SEARCH_MENU[menu_name][:url_param]` is
  # used to extract a value from `#request_parameters`.
  #
  # If no option is currently selected, an initial "null" selection is
  # prepended.
  #
  # Normally the element is a '<div>' but if #immediate_search? is true then it
  # is a '<form>' which allows the enclosed '<select>' to perform a new
  # modified search upon selection.
  #
  # @param [Symbol]              menu_name  Control name.
  # @param [String, Symbol, nil] target     Passed to #search_form.
  # @param [String, Array, nil]  selected   Selected menu item(s).
  # @param [String, Symbol, nil] label_id   ID of associated label element.
  # @param [Boolean, nil]        disabled
  # @param [String]              css        Characteristic CSS class/selector.
  # @param [Hash]                opt        Passed to #search_form except for
  #                                           #MENU_OPT and:
  #
  # @option opt [any, nil] :default         Provided default value.
  # @option opt [Hash]     :config          Pre-fetched menu configuration.
  #
  # @return [ActiveSupport::SafeBuffer]     HTML menu element.
  # @return [nil]                           If menu unavailable for *target*.
  #
  # @see GridHelper#grid_cell_classes
  #
  def menu_control: (Symbol menu_name, ?target: String|Symbol|nil, ?selected: String|anyArray|nil, ?label_id: String|Symbol|nil, ?disabled: bool|nil, ?css: String|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # A label associated with a dropdown menu element.
  #
  # @param [String, Symbol] menu_name     Control name.
  # @param [String]         css           Characteristic CSS class/selector.
  # @param [Hash]           opt           Passed to #control_label.
  #
  # @return [ActiveSupport::SafeBuffer]   Empty if no label was present.
  #
  def menu_label: ((String|Symbol) menu_name, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # menu_tooltip
  #
  # @param [String, Symbol] menu_name   Control name.
  # @param [Hash]           opt         Passed to #config_tooltip.
  #
  # @return [String]                    Tooltip text.
  # @return [nil]                       If no tooltip was defined.
  #
  def menu_tooltip: ((String|Symbol) menu_name, **untyped opt) -> (String | nil)

  # Date selection for the end of a date range.
  #
  # @param [Symbol] menu_name           Control name (should be :before).
  # @param [Hash]   opt                 Passed to #date_container.
  #
  # @return [ActiveSupport::SafeBuffer] HTML label and control elements.
  # @return [nil]                       If menu is not available.
  #
  def before_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Date selection for the beginning of a date range.
  #
  # @param [Symbol] menu_name           Control name (should be :after).
  # @param [Hash]   opt                 Passed to #date_container.
  #
  # @return [ActiveSupport::SafeBuffer] HTML label and control elements.
  # @return [nil]                       If menu is not available.
  #
  def after_menu: (Symbol menu_name, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # A date control preceded by a label (if provided).
  #
  # @param [Symbol]              menu_name  Control name.
  # @param [String, nil]         label      Label text passed to #date_label.
  # @param [String, Symbol, nil] target     Search target controller.
  # @param [Hash]                opt        Passed to #date_control.
  #
  # @return [ActiveSupport::SafeBuffer]     HTML label and control elements.
  # @return [nil]                           Menu is not available for *target*.
  #
  # @see #menu_container
  #
  def date_container: (Symbol menu_name, ?label: String|nil, ?target: String|Symbol|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # A date selection element.
  #
  # If *selected* is not specified `#SEARCH_MENU[name][:url_param]` is used to
  # extract a value from `#request_parameters`.
  #
  # If no option is currently selected, an initial "null" selection is
  # prepended.
  #
  # @param [Symbol]              menu_name  Control name.
  # @param [String, Symbol, nil] target     Search target controller.
  # @param [String, Date, nil]   selected   Date value.
  # @param [String, Symbol, nil] label_id   ID of associated label element.
  # @param [String]              css        Characteristic CSS class/selector.
  # @param [Hash]                opt        Passed to #search_form except for
  #                                           #MENU_OPT and:
  #
  # @option opt [Date, String]   :selected  Initial value.
  # @option opt [Hash]           :config    Pre-fetched configuration info.
  #
  # @return [ActiveSupport::SafeBuffer]     HTML menu element.
  # @return [nil]                           If menu is not available.
  #
  # @see GridHelper#grid_cell_classes
  #
  def date_control: (Symbol menu_name, ?label: String|nil, ?target: String|Symbol|nil, ?selected: String|Date|nil, ?label_id: String|Symbol|nil, ?css: String|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # A label associated with a dropdown menu element.
  #
  # @param [Symbol] menu_name             Control name.
  # @param [String] css                   Characteristic CSS class/selector.
  # @param [Hash]   opt                   Passed to #control_label.
  #
  # @return [ActiveSupport::SafeBuffer]   Empty if no label was configured or
  #                                         provided.
  def date_label: (Symbol menu_name, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # date_tooltip
  #
  # @param [Symbol] menu_name         Control name.
  # @param [Hash]   opt               Passed to #config_tooltip'.
  #
  # @return [String]                  Tooltip text.
  # @return [nil]                     If no tooltip was defined.
  #
  def date_tooltip: (Symbol menu_name, **untyped opt) -> (String | nil)

  # The control for resetting filter menu selections to their default state.
  #
  # @param [Hash] opt                 Passed to #menu_spacer and #reset_button.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def reset_menu: (**untyped opt) -> ActiveSupport::SafeBuffer

  # A button to reset all filter menu selections to their default state.
  #
  # @param [String] css           Characteristic CSS class/selector.
  # @param [Hash]   opt           Passed to #link_to except for #MENU_OPT and:
  #
  # @option opt [String] :url     Default from #request_parameters.
  # @option opt [String] :label   Button label.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see #SEARCH_RESET_CONTROL
  # @see #reset_parameters
  # @see GridHelper#grid_cell_classes
  #
  def reset_button: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # URL parameters that should be cleared for the current search target.
  #
  # @param [Hash] opt                 Default: `#request_parameters`.
  #
  # @return [Hash]
  #
  def reset_parameters: (?untyped opt) -> symHash

  # A blank element used for occupying "voids" in the search control panel.
  #
  # @param [String] css               Characteristic CSS class/selector.
  # @param [Hash]   opt               Passed to #html_div except #MENU_OPT.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see GridHelper#grid_cell_classes
  #
  def menu_spacer: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # A label associated with a dropdown menu element.
  #
  # @param [String, Symbol]      name     Control name.
  # @param [String, Symbol, nil] target   Search target controller.
  # @param [String, nil]         label    Label text override.
  # @param [String]              css      Characteristic CSS class/selector.
  # @param [Hash]                opt      Passed to #label_tag except for
  #                                         #MENU_OPT and:
  #
  # @option opt [Hash] :config            Pre-fetched configuration info.
  #
  # @return [ActiveSupport::SafeBuffer]   Empty if no label was present.
  #
  # @see GridHelper#grid_cell_classes
  #
  def control_label: ((String|Symbol) name, ?target: String|Symbol|nil, ?label: String|nil, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Indicate whether the menu is already sorted.
  #
  # @param [Array<Array(String,*)>] menu
  #
  def entries_sorted?: (Array[[String,untyped]] menu) -> bool

  # Return a sorted copy of the menu.
  #
  # @param [Array<Array(String,*)>] menu
  #
  # @return [Array<Array(String,*)>]
  #
  def sort_entries: (Array[[String,untyped]] menu) -> Array[[String,untyped]]

  # Sort the menu by value if the value is a number or by the label otherwise.
  #
  # @param [Array<Array(String,*)>] menu
  #
  # @return [Array<Array(String,*)>]    The possibly-modified *menu*.
  #
  def sort_entries!: (Array[[String,untyped]] menu) -> Array[[String,untyped]]

  public

  # current_menu_config
  #
  # @param [Symbol, String]      menu_name
  # @param [Symbol, String, nil] target     Default: `#search_target`.
  #
  # @return [Hash]
  #
  def current_menu_config: ((String|Symbol) menu_name, ?target: Symbol|String|nil, **untyped _ignored) -> symHash

  # Get the configured tooltip for the control.
  #
  # @param [String, Symbol] name      Control name.
  # @param [Hash]           opt       Passed to #current_menu_config.
  #
  # @return [String]                  Tooltip text.
  # @return [nil]                     If no tooltip was defined.
  #
  def config_tooltip: ((Symbol|String) name, **untyped opt) -> (String | nil)
end
