# View helper methods for the '<header>' search bar.
#
module LayoutHelper::SearchBar
  include LayoutHelper::SearchFilters

  include ConfigurationHelper

  include LinkHelper

  include ParamsHelper

  include SearchTermsHelper

  # A table of search bar behavior for each controller.
  #
  # @type [Hash{Symbol=>Hash}]
  #
  SEARCH_BAR: symHash

  # The icon used within the search bar to clear the current search.
  #
  # @type [String]
  #
  CLEAR_SEARCH_ICON: String

  # Indicate whether it is appropriate to show the search bar.
  #
  # @param [Symbol, String, nil] ctrlr  Default: params[:controller].
  # @param [Hash, nil]           opt    Default: `#request_parameters`.
  #
  def show_search_bar?: (?(Symbol|String|nil) ctrlr, ?(symHash|nil) opt) -> bool

  # Indicate whether it is appropriate to show the search input menu.
  #
  # @param [Symbol, String, nil] ctrlr  Passed to #search_input_types.
  # @param [Hash]                opt    Passed to #search_input_types.
  #
  def show_input_select?: (?(Symbol|String|nil) ctrlr, **untyped opt) -> bool

  # search_bar_container
  #
  # @param [Symbol, String, nil]   target     Default: `#search_input_target`
  # @param [Array, Hash, nil]      fields     Default: `#search_input_types`.
  # @param [Hash, nil]             values     Default: `#url_parameters`.
  # @param [Symbol, Array<Symbol>] only
  # @param [Symbol, Array<Symbol>] except
  # @param [Integer, nil]          maximum    Maximum input rows in group.
  # @param [Integer, nil]          minimum    Minimum input rows in group.
  # @param [Hash]                  form_opt   Passed to #html_form.
  #
  # @return [ActiveSupport::SafeBuffer]
  # @return [nil]                             Search unavailable for *target*.
  #
  def search_bar_container: (?target: Symbol|String|nil, ?fields: symArray|symHash|nil, ?values: symHash|nil, ?only: Symbol|symArray|nil, ?except: Symbol|symArray|nil, ?maximum: Integer|nil, ?minimum: Integer|nil, **untyped form_opt) -> (ActiveSupport::SafeBuffer | nil)

  # Generate a row within a search-bar-group.
  #
  # @param [Symbol, String, nil] field      Passed to #search_input.
  # @param [String, nil]         value      Passed to #search_input.
  # @param [Boolean, nil]        first      If *true* this is the first row.
  # @param [Boolean, nil]        last       If *true* this is the last row.
  # @param [Hash]                opt        Passed to outer #html_div except:
  #
  # @option opt [String, Symbol]  :target
  # @option opt [String, Boolean] :unique   Passed to #unique_id.
  # @option opt [Integer]         :index    Passed to #unique_id.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def search_bar_row: ((Symbol|String|nil) field, ?(String|nil) value, ?first: bool|nil, ?last: bool|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Reveal the next search-bar-row in the current search-bar-group.
  #
  # @param [Hash] opt                 Passed to #search_row_control.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def search_row_add: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Reveal the associated search-bar-row.
  #
  # @param [Hash] opt                 Passed to #search_row_control.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def search_row_remove: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Generate an element for selecting search type.
  #
  # @param [String] css                     Characteristic CSS class/selector.
  # @param [Hash]   opt                     Passed to #select_tag except for
  #                                           #MENU_OPT and:
  #
  # @option opt [String, Symbol]  :target
  # @option opt [String, Boolean] :unique   Passed to #unique_id.
  # @option opt [Integer]         :index    Passed to #unique_id.
  #
  # @return [ActiveSupport::SafeBuffer]     An HTML input element.
  # @return [nil]                           Search unavailable for target.
  #
  def search_input_select: (?css: String|nil, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Generate an element for entering search terms.
  #
  # @param [Symbol, String, nil] field
  # @param [String, nil]         value
  # @param [Hash]                opt        Passed to #html_div except for:
  #
  # @option opt [String, Symbol]  :target
  # @option opt [String, Boolean] :unique   Passed to #unique_id.
  # @option opt [Integer]         :index    Passed to #unique_id.
  #
  # @return [ActiveSupport::SafeBuffer]     An HTML input element.
  # @return [nil]                           Search unavailable for target.
  #
  # @see #search_input
  #
  def search_bar: ((Symbol|String|nil) field, ?(String|nil) value, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # search_bar_label
  #
  # @param [Symbol, String, nil] ctrlr    Default: *target*
  # @param [Symbol, String, nil] target   Default: `#search_input_target`
  # @param [Hash]                opt      Passed to #config_lookup.
  #
  # @return [String]                      The specified value.
  # @return [nil]                         No non-empty value was found.
  #
  def search_bar_label: (?(Symbol|String|nil) ctrlr, ?target: Symbol|symArray|nil, **untyped opt) -> (String | nil)

  # An operation on a search-bar-row.
  #
  # @param [String, Symbol] operation
  # @param [String]         css             Characteristic CSS class/selector.
  # @param [Hash]           opt             Passed to #icon_button except for:
  #
  # @option opt [any, nil]        :field    Discarded.
  # @option opt [any, nil]        :target   Discarded.
  # @option opt [String, Boolean] :unique   Passed to #unique_id.
  # @option opt [Integer]         :index    Passed to #unique_id.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def search_row_control: ((String|Symbol) operation, ?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # The URL parameter to which search terms should be applied.
  #
  # @param [Symbol, String, nil] ctrlr  Default: `#search_input_target`
  # @param [Hash]                opt    Passed to #search_input_type.
  #
  # @return [Symbol]                    The specified value.
  # @return [nil]                       No non-empty value was found.
  #
  def search_input_field: (?(Symbol|String|nil) ctrlr, **untyped opt) -> (Symbol | nil)

  # Screen-reader-only label for the input field.
  #
  # @param [Symbol, String, nil] ctrlr  Passed to #search_input_type.
  # @param [Hash]                opt    Passed to #search_input_type.
  #
  # @return [String]                    The specified value.
  # @return [nil]                       No non-empty value was found.
  #
  def search_input_label: (?(Symbol|String|nil) ctrlr, **untyped opt) -> (String | nil)

  # Placeholder text displayed in the search input box.
  #
  # @param [Symbol, String, nil] ctrlr  Passed to #search_input_type.
  # @param [Hash]                opt    Passed to #search_input_type.
  #
  # @return [String]                    The specified value.
  # @return [nil]                       No non-empty value was found.
  #
  def search_input_placeholder: (?(Symbol|String|nil) ctrlr, **untyped opt) -> (String | nil)

  # Properties of the indicated search input type.
  #
  # @param [Symbol, String, nil] ctrlr    Default: `#search_input_types`
  # @param [Symbol, String, nil] target   Default: `#search_input_types`
  # @param [Symbol, String, nil] field    Input type; first one if not given.
  # @param [Hash]                opt      Passed to #search_input_types.
  #
  # @return [Hash{Symbol=>Symbol,String}]
  #
  def search_input_type: (?(Symbol|String|nil) ctrlr, ?target: Symbol|symArray|nil, ?field: Symbol|symArray|nil, **untyped opt) -> Hash[Symbol,(Symbol|String)]

  # All defined input types.
  #
  # @param [Symbol, String, nil] ctrlr    Default: *target*
  # @param [Symbol, String, nil] target   Default: `#search_input_target`
  # @param [Hash]                opt      Passed to #config_lookup.
  #
  # @return [Hash{Symbol=>Hash}]
  #
  def search_input_types: (?(Symbol|String|nil) ctrlr, ?target: Symbol|symArray|nil, **untyped opt) -> symHash

  # search_input_target
  #
  # @param [Symbol, String, nil] ctrlr    Default: *target*
  # @param [Symbol, String, nil] target   Default: `#search_target`
  #
  # @return [Symbol]                      The controller used for searching.
  # @return [nil]                         If search input should not be enabled
  #
  def search_input_target: (?(Symbol|String|nil) ctrlr, ?target: Symbol|symArray|nil, **untyped _ignored) -> (Symbol | nil)

  # Generate a form search field input control.
  #
  # @param [Symbol, String, nil] field      Default: `#search_input_field`.
  # @param [Symbol, String, nil] ctrlr      Default: *target*.
  # @param [Symbol, String, nil] target     Default: `#search_input_target`.
  # @param [String, nil]         value      Default: `params[*field*]`.
  # @param [String]              css        Characteristic CSS class/selector.
  # @param [Hash]                opt        Passed to #search_field_tag except:
  #
  # @option opt [String, Boolean] :unique   Passed to #unique_id.
  # @option opt [Integer]         :index    Passed to #unique_id.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @note Used by UploadDecorator#parent_entry_select
  #
  def search_input: ((Symbol|symArray|nil) field, ?(String|Symbol|nil) ctrlr, ?target: Symbol|symArray|nil, ?value: String|nil, ?css: String, **untyped opt) -> ActiveSupport::SafeBuffer

  SEARCH_READY_TOOLTIP: String

  SEARCH_NOT_READY_TOOLTIP: String

  # Generate a form submit control.
  #
  # @param [Symbol, String, nil] ctrlr    Default: *target*
  # @param [Symbol, String, nil] target   Default: `#search_input_target`
  # @param [String, nil]         label    Default: `#search_button_label`.
  # @param [String]              css      Characteristic CSS class/selector.
  # @param [Hash]                opt      Passed to #submit_tag.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def search_button: (?(Symbol|String|nil) ctrlr, ?target: Symbol|symArray|nil, ?label: String|nil, ?css: String, **untyped opt) -> ActiveSupport::SafeBuffer

  # search_button_label
  #
  # @param [Symbol, String, nil] ctrlr    Default: *target*
  # @param [Symbol, String, nil] target   Default: `#search_input_target`
  # @param [Hash]                opt      Passed to #config_lookup.
  #
  # @return [String]                      The specified value.
  # @return [nil]                         No non-empty value was found.
  #
  # @note Used by UploadDecorator#parent_entry_select
  #
  def search_button_label: (?(Symbol|String|nil) ctrlr, ?target: Symbol|symArray|nil, **untyped opt) -> (String | nil)

  # search_clear_button
  #
  # @param [String] css                     Characteristic CSS class/selector.
  # @param [Hash]   opt                     Passed to #icon_button except for:
  #
  # @option opt [String, Boolean] :unique   Passed to #unique_id.
  # @option opt [Integer]         :index    Passed to #unique_id.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see file:javascripts/feature/advanced-search.js *clearSearchTerm()*
  #
  def search_clear_button: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  SEARCH_CONTROLS: symArray

  # A container for the search submit, filter reset, and filter toggle buttons.
  #
  # @param [Symbol, String, nil]   ctrlr    Default: *target*
  # @param [Symbol, String, nil]   target   Default: `#search_button`
  # @param [String, nil]           form     Form element identifier.
  # @param [String]                css      Characteristic CSS class/selector.
  # @param [Hash]                  opt      Passed to #html_div except:
  #
  # @option opt [Symbol, Array<Symbol>] :only     One or more #SEARCH_CONTROLS.
  # @option opt [Symbol, Array<Symbol>] :except   One or more #SEARCH_CONTROLS.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def search_controls: (?(Symbol|String|nil) ctrlr, ?target: Symbol|symArray|nil, ?form: String|nil, ?css: String, **untyped opt) -> ActiveSupport::SafeBuffer

  # Filter values from an array.
  #
  # @param [Array<Symbol>, Symbol, nil] obj
  # @param [Array<Symbol>, Symbol, nil] only
  # @param [Array<Symbol>, Symbol, nil] except
  #
  # @return [Array]                   A modified copy of *obj*.
  #
  def filter: ((Symbol|symArray|nil) obj, ?only: Symbol|symArray|nil, ?except: Symbol|symArray|nil, **untyped _ignored) -> symArray

  # Filter values from an array.
  #
  # @param [Array<Symbol>]              array
  # @param [Array<Symbol>, Symbol, nil] only
  # @param [Array<Symbol>, Symbol, nil] except
  #
  # @return [Array]                   The original object, possibly modified.
  #
  def filter!: (symArray array, ?only: Symbol|symArray|nil, ?except: Symbol|symArray|nil, **untyped _ignored) -> symArray
end
