# Base class for all controllers.
#
class ApplicationController < ActionController::Base
  include Emma::TypeMethods

  include ParamsHelper

  include ConfigurationConcern

  include MetricsConcern

  include ResponseConcern

  # The current layout template.
  #
  # @return [String]                  Basename of views/layouts/* template.
  # @return [FalseClass]              If this is an XHR request.
  #
  def current_layout: () -> (String | false)

  # Indicate whether rendering within a modal dialog ('<iframe>').
  #
  def modal?: () -> bool

  @modal: bool

  # This is a catch-all for endpoints which are intentionally being rejected
  # with extreme prejudice.
  #
  def return_to_sender: () -> void

  # Return the IP address of the requester.
  #
  # @param [ActionDispatch::Request, nil] req       Default: `request`.
  # @param [Array<String>, nil]           proxies   Trusted proxies.
  #
  # @return [String]
  #
  def sender_ip: (?(ActionDispatch::Request|nil) req, ?(strArray|nil) proxies) -> String
end
