# Handle Bookshare-only "/category" pages.
#
# @see CategoryHelper
# @see file:app/views/category/**
#
# @note These endpoints are not currently presented as a part of EMMA.
#
# == Usage Notes
# Categories can be seen by anyone, including anonymous users.
#
class CategoryController < ApplicationController
  include UserConcern

  include ParamsConcern

  include SessionConcern

  include RunStateConcern

  include PaginationConcern

  include SerializationConcern

  include BookshareConcern

  # :nocov:
  #include AbstractController::Callbacks

  attr_reader page: Paginator
  attr_reader list: Bs::Message::CategoriesList

  # == GET /category
  #
  # List all categories.
  #
  # @see BookshareService::Request::Titles#get_categories
  #
  def index: () -> void

  # Response values for de-serializing the index page to JSON or XML.
  #
  # @param [Bs::Message::CategoriesList] list
  # @param [Hash]                        opt
  #
  # @return [Hash{Symbol=>Hash}]
  #
  def index_values: (?Bs::Message::CategoriesList list, **untyped opt) -> symHash
end
