# Manage bulk operation manifests
#
# @see ManifestDecorator
# @see ManifestsDecorator
# @see file:app/views/manifest/**
#
class ManifestController < ApplicationController
  include UserConcern

  include ParamsConcern

  include OptionsConcern

  include SessionConcern

  include RunStateConcern

  include PaginationConcern

  include IngestConcern

  include ManifestConcern

  # :nocov:
  #include AbstractController::Callbacks

  #include ActionController::RespondWith

  #extend  CanCan::ControllerAdditions::ClassMethods

  LISTS: symArray

  MENUS: symArray

  UNIT_OPS: symArray

  OPS: symArray

  @list: Array[Manifest] | Array[Integer] | Array[String] | nil

  # Single item.
  #
  # @return [Manifest, nil]
  #
  attr_reader item: Manifest | nil

  # === GET /manifest
  #
  # List bulk operation manifests.
  #
  # @see #manifest_index_path           Route helper
  # @see ManifestController#list_items
  #
  def index: () -> nil

  # === GET /manifest/show/(:id)
  #
  # Redirects to #show_select if :id is missing.
  #
  # @see #show_manifest_path          Route helper
  # @see ManifestConcern#find_record
  #
  def show: () -> void

  # === GET /manifest/new
  #
  # @see #new_manifest_path           Route helper
  # @see ManifestConcern#new_record
  #
  def new: () -> void

  # === POST  /manifest/create
  # === PUT   /manifest/create
  # === PATCH /manifest/create
  #
  # @see #create_manifest_path        Route helper
  # @see ManifestConcern#create_record
  #
  def create: () -> void

  # === GET /manifest/edit/(:id)
  #
  # Redirects to #edit_select if :id is not given.
  #
  # @see #edit_manifest_path          Route helper
  # @see ManifestConcern#edit_record
  #
  def edit: () -> void

  # === POST  /manifest/update/:id
  # === PUT   /manifest/update/:id
  # === PATCH /manifest/update/:id
  #
  # @see #update_manifest_path        Route helper
  #
  def update: () -> void

  # === GET /manifest/delete/:id
  #
  # Redirects to #delete_select if :id is not given.
  #
  # @see #delete_manifest_path          Route helper
  # @see ManifestConcern#delete_records
  #
  def delete: () -> void

  # === DELETE /manifest/destroy/:id
  #
  # @see #destroy_manifest_path           Route helper
  # @see ManifestConcern#destroy_records
  #
  def destroy: () -> void

  # === GET /manifest/list_all
  #
  # List all bulk operation manifests.
  #
  # @see ManifestController#list_items
  #
  def list_all: () -> void

  # === GET /manifest/list_org
  #
  # List all bulk operation manifests associated with users in the same
  # organization as the current user.
  #
  # @see ManifestController#list_items
  #
  def list_org: () -> void

  # === GET /manifest/list_own
  #
  # List all bulk operation manifests associated with the current user.
  #
  # @see ManifestController#list_items
  #
  def list_own: () -> void

  # Setup pagination for lists of manifests.
  #
  # @param [Hash, nil] prm            Default: from `paginator`.
  # @param [Boolean]   for_org
  # @param [Boolean]   for_user
  #
  # @return [Hash]
  #
  def list_items: (?(symHash|nil) prm, for_org: bool) -> symHash

  # === GET /manifest/show_select
  #
  # Show a menu to select a manifest to show.
  #
  # @see #show_select_manifest_path   Route helper
  #
  def show_select: () -> void

  # === GET /manifest/edit_select
  #
  # Show a menu to select a manifest to edit.
  #
  # @see #edit_select_manifest_path   Route helper
  #
  def edit_select: () -> void

  # === GET /manifest/delete_select
  #
  # Show a menu to select a manifest to delete.
  #
  # @see #delete_select_manifest_path   Route helper
  #
  def delete_select: () -> void

  # === GET /manifest/remit_select
  #
  # Show a menu to select a manifest to submit.
  #
  # @see #remit_select_manifest_path  Route helper
  #
  def remit_select: () -> void

  # The minimal set of ManifestItem values returned upon save.
  #
  # Any columns referenced in `manifest.field_error` will also be included.
  #
  # @type [Array<Symbol>]
  #
  # @see file:javascripts/controllers/manifest-edit.js *updateRowValues()*
  #
  ITEM_SAVE_COLS: symArray

  # === POST  /manifest/save/:id
  # === PUT   /manifest/save/:id
  # === PATCH /manifest/save/:id
  #
  # @see #save_manifest_path                                  Route helper
  # @see file:assets/javascripts/controllers/manifest-edit.js *updateDataRow()*
  # @see ManifestConcern#save_changes
  #
  def save: () -> void

  # === POST  /manifest/cancel/:id
  # === PUT   /manifest/cancel/:id
  # === PATCH /manifest/cancel/:id
  #
  # @see #cancel_manifest_path        Route helper
  #
  def cancel: () -> void

  # === GET /manifest/remit/(:id)
  #
  # Redirects to #remit_select if :id is not given.
  #
  # @see #remit_manifest_path         Route helper
  #
  def remit: () -> void

  # === GET /manifest/get_job_result/:job_id[?column=(output|diagnostic|error)]
  # === GET /manifest/get_job_result/:job_id/*path[?column=(output|diagnostic|error)]
  #
  # Return a value from the 'job_results' table, where :job_id is the value for
  # the matching :active_job_id.
  #
  # @see ApplicationJob::Methods#job_result
  #
  def get_job_result: () -> void

  # === POST /manifest/start/:id
  #
  # @see #start_manifest_path         Route helper
  #
  #def start: () -> void

  # === POST /manifest/stop/:id
  #
  # @see #stop_manifest_path          Route helper
  #
  #def stop: () -> void

  # === POST /manifest/pause/:id
  #
  # @see #pause_manifest_path         Route helper
  #
  #def pause: () -> void

  # === POST /manifest/resume/:id
  #
  # @see #resume_manifest_path        Route helper
  #
  #def resume: () -> void
end
