# Handle "/manifest_item" requests.
#
# @see ManifestItemDecorator
# @see ManifestItemsDecorator
# @see file:app/views/manifest_item/**
#
class ManifestItemController < ApplicationController
  include UserConcern

  include ParamsConcern

  include OptionsConcern

  include SessionConcern

  include RunStateConcern

  include PaginationConcern

  include ManifestItemConcern

  # :nocov:
  #include AbstractController::Callbacks

  #include ActionController::RespondWith

  #extend CanCan::ControllerAdditions::ClassMethods

  MENUS: symArray

  UNIT_OPS: symArray

  BULK_OPS: symArray

  OPS: symArray

  @list: Array[ManifestItem] | Array[Integer] | Array[String] | nil

  # API results for :show.
  #
  # @return [ManifestItem, nil]
  #
  attr_reader item: ManifestItem | nil

  @group_counts: symHash

  # === GET /manifest_item/:manifest[?id=(:id|RANGE_LIST)]
  #
  # Display the items for the given Manifest.
  #
  # @see #manifest_item_index_path                 Route helper
  #
  def index: () -> nil

  # === GET /manifest_item/show/:manifest/:id
  #
  # Display the values of a single manifest item.
  #
  # @see #show_manifest_item_path                  Route helper
  #
  def show: () -> void

  # === GET /manifest_item/new/:manifest
  #
  # Initiate creation of a new ManifestItem by displaying the form which
  # prompts to upload a file and collects metadata for the new item.
  #
  # @see #new_manifest_item_path                   Route helper
  # @see ManifestItemController#create
  # @see file:app/assets/javascripts/feature/model-form.js
  #
  def new: () -> void

  # === POST  /manifest_item/create/:manifest
  # === PUT   /manifest_item/create/:manifest
  # === PATCH /manifest_item/create/:manifest
  #
  # Invoked from the handler for the Uppy 'upload-success' event to finalize
  # the creation of a new row.
  #
  # @see #create_manifest_item_path                Route helper
  # @see ManifestItemController#new
  #
  def create: () -> void

  # === GET /manifest_item/edit/:manifest/:id
  #
  # Initiate modification of an existing item by prompting for metadata
  # changes and/or upload of a replacement file.
  #
  # @see #edit_manifest_item_path                  Route helper
  # @see ManifestItemController#update
  # @see file:app/assets/javascripts/feature/model-form.js
  #
  def edit: () -> void

  # === PUT   /manifest_item/update/:manifest/:id
  # === PATCH /manifest_item/update/:manifest/:id
  #
  # Finalize modification of an existing item.
  #
  # @see #update_manifest_item_path                Route helper
  # @see ManifestItemController#edit
  #
  def update: () -> void

  # === GET /manifest_item/delete/:manifest/:id
  # === GET /manifest_item/delete/:manifest/RANGE_LIST[?...]
  #
  # Initiate removal of an existing item along with its associated file.
  #
  # @see #delete_manifest_item_path                Route helper
  # @see ManifestItemController#destroy
  #
  def delete: () -> void

  # === DELETE /manifest_item/destroy/:manifest/:id
  # === DELETE /manifest_item/destroy/:manifest/RANGE_LIST[?...]
  #
  # Finalize removal of an existing item.
  #
  # @see #destroy_manifest_item_path               Route helper
  # @see ManifestItemController#delete
  #
  def destroy: () -> void

  # === POST /manifest_item/start_edit/:id
  #
  # Set :editing state and backup fields.
  #
  # @see #start_editing_manifest_item_path               Route helper
  #
  def start_edit: () -> void

  # === POST /manifest_item/finish_edit/:id
  #
  # Clear :editing state and respond with item and validity information.
  #
  def finish_edit: () -> void

  # === POST /manifest_item/row_update/:id
  #
  # Clear :editing state and respond with item and validity information.
  #
  def row_update: () -> void

  # === POST /manifest_item/upload
  #
  # Invoked from 'Uppy.XHRUpload'.  If the 'X-Update-FileData-Only' header is
  # *true* then the record's :file_data column is updated without modifying
  # :update_time or other columns.
  #
  # @see file:javascripts/shared/uploader.js *BulkUploader._xhrOptions*
  #
  def upload: () -> void

  # === GET /manifest_item/bulk_new[?source=FILE&batch=true|SIZE&prefix=STRING]
  #
  # Display a form prompting for a bulk operation manifest (either CSV or JSON)
  # containing a row/element for each item to add.
  #
  # @see #bulk_new_manifest_item_path              Route helper
  # @see ManifestItemController#bulk_create
  #
  def bulk_new: () -> void

  # === POST /manifest_item/bulk[?source=FILE&batch=true|SIZE&prefix=STRING]
  #
  # Create the specified ManifestItem records, download and store the
  # associated files.
  #
  # @see #bulk_create_manifest_item_path           Route helper
  # @see ManifestItemController#bulk_new
  # @see file:javascripts/controllers/manifest-edit.js *sendUpsertRecords*
  #
  def bulk_create: () -> void

  # === GET /manifest_item/bulk_edit[?source=FILE&batch=true|SIZE&prefix=STRING]
  #
  # Display a form prompting for a bulk operation manifest (either CSV or JSON)
  # containing a row/element for each item to change.
  #
  # @see #bulk_edit_manifest_item_path             Route helper
  # @see ManifestItemController#bulk_update
  #
  def bulk_edit: () -> void

  # === PUT   /manifest_item/bulk[?source=FILE&batch=true|SIZE&prefix=STRING]
  # === PATCH /manifest_item/bulk[?source=FILE&batch=true|SIZE&prefix=STRING]
  #
  # Modify or create the specified ManifestItem records, download and store the
  # associated files (if changed).
  #
  # @see #bulk_update_manifest_item_path           Route helper
  # @see ManifestItemController#bulk_edit
  # @see file:javascripts/controllers/manifest-edit.js *sendUpsertRecords*
  #
  def bulk_update: () -> void

  # === GET /manifest_item/bulk_delete[?force=false]
  #
  # Specify items to delete by :id or RANGE_LIST.
  #
  # @see #bulk_delete_manifest_item_path           Route helper
  # @see ManifestItemController#bulk_destroy
  #
  def bulk_delete: () -> void

  # === DELETE /manifest_item/bulk[?force=true]
  #
  # @see #bulk_destroy_manifest_item_path          Route helper
  # @see ManifestItemController#bulk_delete
  #
  def bulk_destroy: () -> void

  # === PUT   /manifest_item/bulk/fields/:manifest
  # === PATCH /manifest_item/bulk/fields/:manifest
  #
  # Modify selected ManifestItem fields of one or more items.
  #
  # @see #bulk_update_manifest_item_path           Route helper
  # @see file:javascripts/controllers/manifest-edit.js *sendFieldUpdates*
  #
  def bulk_fields: () -> void

  # A list of ManifestItems plus validity information.
  #
  # @param [any, nil] list
  # @param [Hash]    opt              Passed to #index_values.
  #
  # @return [Hash{Symbol=>Hash}]
  #
  # @see file:javascripts/controllers/manifest-edit.js *processReceivedItems*
  #
  def bulk_update_response: (?untyped list, **untyped opt) -> Hash[Symbol,symHash]

  # A list of ManifestItem IDs.
  #
  # @param [any, nil] list
  #
  # @return [Hash{Symbol=>Hash}]
  #
  def bulk_id_response: (?untyped list, **untyped _ignored) -> Hash[Symbol,symHash]

  # This is a kludge until I can figure out the right way to express this with
  # CanCan -- or replace CanCan with a more expressive authorization gem.
  #
  # @param [ManifestItem, Array<ManifestItem>, nil] subject
  # @param [Symbol, String, nil]                    action
  # @param [any, nil]                               args
  #
  def manifest_item_authorize!: (?(ManifestItem|Array[ManifestItem]|nil) subject, ?(Symbol|String|nil) action, *untyped args) -> void
end
