# Access search call instances.
#
# @see SearchCallHelper
# @see file:app/views/search_call/**
#
class SearchCallController < ApplicationController
  include UserConcern

  include ParamsConcern

  include SessionConcern

  include RunStateConcern

  include PaginationConcern

  include SerializationConcern

  include SearchCallConcern

  # :nocov:
  #include AbstractController::Callbacks

  # Initially extend table with a column for each JSON sub-field.
  #
  # @type [Boolean]
  #
  EXPAND_JSON: bool

  # == GET /search_call?[expand=TRUE&like=PATTERN&field=MATCH&...]
  #
  # List searches.
  #
  # @see SearchCallConcern#get_search_calls
  # @see SearchCall#extended_table
  #
  def index: () -> void

  # == GET /search_call/:id
  #
  # Display details of a search.
  #
  # @see SearchCall#find
  #
  def show: () -> void

  # Response values for de-serializing the index page to JSON or XML.
  #
  # @param [Search::Message::SearchRecordList] list
  # @param [Hash]                              opt
  #
  # @return [Hash{Symbol=>Hash}]
  #
  def index_values: (?Search::Message::SearchRecordList list, **untyped opt) -> symHash

  # Response values for de-serializing the show page to JSON or XML.
  #
  # @param [SearchCall, Hash] item
  # @param [Hash]             opt
  #
  # @return [Hash{Symbol=>Hash}]
  #
  def show_values: (?(SearchCall|anyHash) item, **untyped opt) -> symHash
end
