# Access search call instances.
#
# @see SearchCallDecorator
# @see SearchCallsDecorator
# @see file:app/views/search_call/**
#
class SearchCallController < ApplicationController
  include UserConcern

  include ParamsConcern

  include SessionConcern

  include RunStateConcern

  include PaginationConcern

  include SearchCallConcern

  # :nocov:
  #include AbstractController::Callbacks
  # :nocov:

  # Initially extend table with a column for each JSON sub-field.
  #
  # @type [Boolean]
  #
  EXPAND_JSON: bool

  # Results for :index.
  #
  # @return [Array<SearchCall>, nil]
  #
  attr_reader list: Array[SearchCall] | nil

  # Single item.
  #
  # @return [SearchCall, nil]
  #
  attr_reader item: SearchCall | nil

  @extended: bool

  # === GET /search_call?[expand=TRUE&like=PATTERN&field=MATCH&...]
  #
  # List searches.
  #
  # @see #search_call_index_path      Route helper
  #
  def index: () -> void

  # === GET /search_call/:id
  #
  # Display details of a search.
  #
  # @see #search_call_path            Route helper
  #
  def show: () -> void
end
