class SysController < ApplicationController
  include UserConcern

  include ParamsConcern

  include SessionConcern

  include RunStateConcern

  include SysConcern

  # === GET /sys
  #
  # System information main page.
  #
  # @see #sys_index_path              Route helper
  #
  def index: () -> void

  # === POST  /sys
  # === PUT   /sys
  # === PATCH /sys
  #
  # Set application control values.
  #
  # @see #update_sys_path             Route helper
  #
  def update: () -> void

  # === GET /sys/database
  #
  # Redirects to /data.
  #
  def database: () -> void

  # === GET /sys/jobs
  #
  # Redirects to GoodJob dashboard.
  #
  def jobs: () -> void

  # === GET /sys/mailers
  #
  # Redirects to "/rails/mailers".
  #
  def mailers: () -> void

  # An endpoint is defined for each configured page that hasn't already been
  # defined here.  Pages that are not just redirects should have a template in
  # "/app/views/sys".
  #
  # @type [Array<Symbol>]
  #
  # @see file:config/locales/controllers/sys.en.yml *en.emma.sys*
  #
  PAGES: symArray

  def disk_space:   () -> void
  def environment:  () -> void
  def headers:      () -> void
  def internals:    () -> void
  def loggers:      () -> void
  def processes:    () -> void
  def settings:     () -> void

  # Get the path for a redirection from configuration.
  #
  # @param [Symbol] meth
  #
  # @return [String]
  #
  def sys_path_for: (Symbol meth) -> String
end
