# Support create/update forms.
#
module TestHelper::SystemTests::Form
  include TestHelper::SystemTests::Common

  include TestHelper::SystemTests::Flash

  # Click on the form submit button after setting up a screenshot to show
  # invalid field(s) if the submit fails.
  #
  # @param [String, nil] label
  # @param [Hash]        opt          Passed to #click_on.
  #
  # @return [Capybara::Node::Element] The element clicked.
  #
  def form_submit: (untyped? label, **untyped opt) -> Capybara::Node::Element
end
