# Support for working directly with the EMMA Unified Index.
#
module TestHelper::SystemTests::Ingest
  include TestHelper::SystemTests::Common

  include IngestConcern

  # Cause the identified items to be updated in the EMMA Unified Index.
  #
  # @param [Array<Upload,String>] entries
  #
  # @return [Boolean]
  #
  def reindex: (*(Upload|String) entries) -> bool
end
