class AccountMailer < ApplicationMailer
  include Emma::Project

  include EmmaHelper

  include ActionView::Helpers::UrlHelper

  @item: User

  @elem: symHash

  # URL/form parameters associated with account emails.
  #
  # @type [Array<Symbol>]
  #
  URL_PARAMETERS: symArray

  # Send a welcome email to a new EMMA user.
  #
  # @param [Hash] opt
  #
  def new_user_email: (**untyped opt) -> void

  # Send a welcome email to a new manager.
  #
  # @param [Hash] opt
  #
  def new_man_email: (**untyped opt) -> void

  # Send a welcome email to the manager of a new organization.
  #
  # @param [Hash] opt
  #
  def new_org_email: (**untyped opt) -> void

  # Send a welcome email based on configuration from "en.emma.mail".
  #
  # If this is not the production deployment, the email subject will be
  # annotated to indicate that this is not a real message.
  #
  # @param [Symbol] key               Entry under "en.emma.mail".
  # @param [Hash]   opt               Passed to ActionMailer::Base#mail.
  #
  def new_welcome_email: (key: Symbol, **untyped opt) -> void

  # Supply interpolation values for the current email.
  #
  # @param [Hash, nil] vals
  # @param [Hash]      opt
  #
  # @return [Hash]
  #
  def interpolation_values: (?(symHash|nil) vals, **untyped opt) -> symHash
end
