class AccountMailer < ApplicationMailer
  include Emma::Config

  include Emma::Project

  include EmmaHelper

  include ActionView::Helpers::UrlHelper

  @item: User

  @elem: symHash

  # URL/form parameters associated with account emails.
  #
  # @type [Array<Symbol>]
  #
  URL_PARAMETERS: symArray

  # Send a welcome email to a new EMMA user.
  #
  # If this is not the production deployment, the email subject will be
  # annotated to indicate that this is not a real enrollment request.
  #
  # @param [Hash] opt
  #
  def welcome_email: (**untyped opt) -> void

  # Generate mailer message content for #welcome_email.
  #
  # If this is not the production deployment, the heading and body will be
  # annotated to indicate that this is not a real enrollment request.
  #
  # @param [Hash] opt
  #
  # @option opt [Symbol]  :format
  # @option opt [Boolean] :test
  #
  # @return [Hash]
  #
  def welcome_email_elements: (**untyped opt) -> symHash
end
