class EnrollmentMailer < ApplicationMailer
  include Emma::Config

  include Emma::Project

  include ActionView::Helpers::UrlHelper

  @item: Enrollment

  @elem: symHash

  # URL/form parameters associated with enrollment request emails.
  #
  # @type [Array<Symbol>]
  #
  URL_PARAMETERS: symArray

  # Send to produce a JIRA help ticket for a new enrollment request.
  #
  # If this is not the production deployment, the email subject will be
  # annotated to indicate that this is not a real enrollment request.
  #
  # @param [Hash] opt
  #
  def request_email: (**untyped opt) -> void

  # Generate mailer message content for #request_email.
  #
  # If this is not the production deployment, the heading and body will be
  # annotated to indicate that this is not a real enrollment request.
  #
  # @param [Hash] opt
  #
  # @option opt [Enrollment] :item    Default: @item.
  # @option opt [Symbol]     :format
  # @option opt [Boolean]    :test
  #
  # @return [Hash]
  #
  def request_email_elements: (**untyped opt) -> symHash

  # Extract organization name.
  #
  # @param [Enrollment, nil] item
  #
  # @return [String, nil]
  #
  def org_from: (Enrollment|nil item) -> (String | nil)

  # Extract name/email.
  #
  # @param [Enrollment, nil] item
  #
  # @return [String, nil]
  #
  def name_from: (Enrollment|nil item) -> (String | nil)
end
