class EnrollmentMailer < ApplicationMailer
  include Emma::Project

  include ActionView::Helpers::UrlHelper

  @item: Enrollment

  @elem: symHash

  # URL/form parameters associated with enrollment request emails.
  #
  # @type [Array<Symbol>]
  #
  URL_PARAMETERS: symArray

  # Send to produce a JIRA help ticket for a new enrollment request.
  #
  # If this is not the production deployment, the email subject will be
  # annotated to indicate that this is not a real enrollment request.
  #
  # @param [Hash] opt
  #
  def request_email: (**untyped opt) -> void

  # Supply interpolation values for the current email.
  #
  # @param [Hash, nil] vals
  # @param [Hash]      opt
  #
  # @return [Hash]
  #
  def interpolation_values: (?(symHash|nil) vals, **untyped opt) -> symHash

  # Extract organization name.
  #
  # @param [Enrollment, nil] item
  #
  # @return [String, nil]
  #
  def org_from: (Enrollment|nil item) -> (String | nil)

  # Extract name/email.
  #
  # @param [Enrollment, nil] item
  #
  # @return [String, nil]
  #
  def name_from: (Enrollment|nil item) -> (String | nil)

  # Extract request comments.
  #
  # @param [Enrollment, nil] item
  #
  # @return [String, nil]
  #
  def comments_from: (Enrollment|nil item) -> (String | nil)
end
