# Definitions used within the #schema block when it is executed in the context
# of a serializer class definition.
#
# @see Api::Serializer::Associations
#
module IaDownload::Api::Serializer::Associations
  extend ActiveSupport::Concern

  include Api::Serializer::Associations

  module ClassMethods
    include IaDownload::Api::Serializer::Schema

    include Api::Serializer::Associations::ClassMethods
  end
end
