# Remove a file.
#
# @note Currently unused
#
class Attachment::DestroyJob < ApplicationJob
  include ApplicationJob::Logging

  # perform
  #
  # @param [Any] data
  #
  # @note Currently unused
  #
  def perform: (untyped data) -> void
end
