# Promote a file from :cache to :store.
#
# @note Currently unused.
#
class Attachment::PromoteJob < ApplicationJob
  include ApplicationJob::Logging

  # perform
  #
  # @param [Model]    record
  # @param [Symbol]   name            Should be :file.
  # @param [any, nil] data            :file_data
  #
  # @return [void]
  #
  def perform: (Model record, Symbol name, untyped data) -> void
end
