module Puma
  # Overrides adding extra debugging around method calls.
  #
  module RequestDebug
    include Puma::ExtensionDebugging

    def handle_request: (Puma::Client client, Integer requests) -> (bool | :async)

    def str_headers: (anyHash env, Integer status, anyHash headers, untyped res_body, Puma::IOBuffer io_buffer, bool force_keep_alive) -> anyHash
  end
end
