module Puma
  # Overrides adding extra debugging around method calls.
  #
  module ServerDebug
    include Puma::ExtensionDebugging

    def initialize: (untyped app, ?(Puma::Events|nil) events, ?anyHash options) -> void

    def process_client: (Puma::Client client) -> bool

    def with_force_shutdown: (Puma::Client client) { () -> untyped } -> untyped

    def client_error: (Exception e, Puma::Client client, Integer requests) -> untyped

    def graceful_shutdown: () -> untyped
  end
end
