# Values related to the details of serialization/de-serialization.
#
# @see Lookup::RemoteService::Api::Schema
#
module Lookup::WorldCat::Api::Schema
  include Lookup::WorldCat::Api::Common

  include Lookup::RemoteService::Api::Schema

  # service_name
  #
  # @return [String]
  #
  def service_name: () -> String

  # default_serializer_type
  #
  # @return [Symbol]
  #
  def default_serializer_type: () -> Symbol
end
