# config/database.yml

# =============================================================================
# MySQL adapter settings
# =============================================================================

_db_mysql:                                                            &DB_MYSQL
  adapter:     mysql2
  encoding:    utf8
  host:        <%= ENV['DBHOST'] %>
  port:        <%= ENV['DBPORT'] %>
  database:    <%= ENV['DBNAME'] %>
  username:    <%= ENV['DBUSER'] %>
  password:    <%= ENV['DBPASSWD'] %>

_db_mysql_prod:                                                  &DB_MYSQL_PROD
  <<: *DB_MYSQL

_db_mysql_dev:                                                    &DB_MYSQL_DEV
  <<: *DB_MYSQL

_db_mysql_test:                                                  &DB_MYSQL_TEST
  <<: *DB_MYSQL

# =============================================================================
# Rails environments
# =============================================================================

production:
  <<: *DB_MYSQL_PROD

development:
  <<: *DB_MYSQL_DEV

test:
  <<: *DB_MYSQL_TEST

# WARNING: The test database will be erased every time "rake test" is run.
# NOTE: Do not set use the same database for either development or production.
