# The base class for serialization/de-serialization of objects derived from
# Bs::Api::Record.
#
class Bs::Api::Serializer < Api::Serializer
  include Bs::Api::Serializer::Schema

  include Bs::Api::Serializer::Associations
end
