class EnrollmentsTest < ApplicationSystemTestCase
  MODEL: Class

  CTRLR: Symbol

  PRM: symHash

  TITLE: String

  @admin: User

  @manager: User

  @member: User

  @generate: OrgSampleGenerator

  # Perform a test to list enrollments visible to *user*.
  #
  # @param [User, nil]    user
  # @param [Integer, nil] total       Expected total number of items.
  # @param [String, nil]  title       Default based on *user* and opt[:action].
  # @param [Symbol]       meth        Calling test method.
  # @param [Hash]         opt         URL parameters.
  #
  # @return [void]
  #
  def list_test: ((User|nil) user, ?total: Integer|nil, ?title: String|nil, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to show an enrollment visible to *user*.
  #
  # @param [User, nil]       user
  # @param [Enrollment, nil] target
  # @param [String, nil]     title
  # @param [Symbol]          meth     Calling test method.
  # @param [Hash]            opt      URL parameters.
  #
  # @return [void]
  #
  def show_test: ((User|nil) user, ?target: Enrollment|nil, ?title: String|nil, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to invoke the menu for selecting an enrollment to display.
  #
  # @param [User, nil] user
  # @param [Hash]      opt            Passed to #page_select_test.
  #
  # @return [void]
  #
  def show_select_test: ((User|nil) user, **untyped opt) -> void

  # Perform a test to invoke the menu for selecting an enrollment to modify.
  #
  # @param [User, nil] user
  # @param [Hash]      opt            Passed to #page_select_test.
  #
  # @return [void]
  #
  def edit_select_test: ((User|nil) user, **untyped opt) -> void

  # Perform a test to invoke the menu for selecting an enrollment to remove.
  #
  # @param [User, nil] user
  # @param [Hash]      opt            Passed to #page_select_test.
  #
  # @return [void]
  #
  def delete_select_test: ((User|nil) user, **untyped opt) -> void

  # Perform a test to invoke the menu for selecting an enrollment.
  #
  # @param [User, nil]   user
  # @param [Symbol]      action
  # @param [String, nil] title
  # @param [Symbol]      meth         Calling test method.
  # @param [Hash]        opt          URL parameters.
  #
  # @return [void]
  #
  def page_select_test: ((User|nil) user, action: Symbol, ?title: String|nil, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to create a new enrollment.
  #
  # @param [User, nil]   user
  # @param [Symbol, nil] meth         Calling test method.
  # @param [Hash]        opt          Added to URL parameters.
  #
  # @return [void]
  #
  def new_test: ((User|nil) user, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to select then modify an enrollment.
  #
  # @param [User, nil]   user
  # @param [Symbol, nil] meth         Calling test method.
  # @param [Hash]        opt          Added to URL parameters.
  #
  # @return [void]
  #
  def edit_test: ((User|nil) user, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to select then remove an enrollment.
  #
  # @param [User, nil]   user
  # @param [Symbol, nil] meth         Calling test method.
  # @param [Hash]        opt          Added to URL parameters.
  #
  # @return [void]
  #
  def delete_test: ((User|nil) user, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to finalize an enrollment to create an organization.
  #
  # @param [User, nil]   user
  # @param [Symbol, nil] meth         Calling test method.
  # @param [Hash]        opt          Added to URL parameters.
  #
  # @return [void]
  #
  def finalize_test: ((User|nil) user, ?meth: Symbol|nil, **untyped opt) -> void
end
