class OrgsTest < ApplicationSystemTestCase
  MODEL: Class

  CTRLR: Symbol

  PRM: symHash

  TITLE: String

  @admin: User

  @manager: User

  @member: User

  @generate: OrgSampleGenerator

  # Perform a test to list organizations visible to *user*.
  #
  # @param [User, nil]    user
  # @param [Integer, nil] total       Expected total number of items.
  # @param [String, nil]  title       Default based on *user* and opt[:action].
  # @param [Symbol]       meth        Calling test method.
  # @param [Hash]         opt         URL parameters.
  #
  # @return [void]
  #
  def list_test: ((User|nil) user, ?total: Integer|nil, ?title: String|nil, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to show an organization visible to *user*.
  #
  # If showing the user's own organization, activity takes place on the
  # :show_current page; otherwise, activity takes place on the :show page;
  # otherwise if *target* is not given it is assigned an example organization.
  #
  # @param [User, nil]   user
  # @param [Org, nil]    target       Default: `user.org` (i.e. :show_current).
  # @param [String, nil] title        Default based on *user* and opt[:action].
  # @param [Symbol]      meth         Calling test method.
  # @param [Hash]        opt          URL parameters.
  #
  # @return [void]
  #
  def show_test: ((User|nil) user, ?target: Org|nil, ?title: String|nil, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to create a new organization.
  #
  # @param [User, nil]   user
  # @param [Symbol, nil] meth         Calling test method.
  # @param [Hash]        opt          Added to URL parameters.
  #
  # @return [void]
  #
  def new_test: ((User|nil) user, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to select then modify an organization.
  #
  # @param [User, nil]   user
  # @param [Symbol, nil] meth         Calling test method.
  # @param [Hash]        opt          Added to URL parameters.
  #
  # @return [void]
  #
  def edit_test: ((User|nil) user, ?meth: Symbol|nil, **untyped opt) -> void

  # Perform a test to select then remove an organization.
  #
  # @param [User, nil]   user
  # @param [Symbol, nil] meth         Calling test method.
  # @param [Hash]        opt          Added to URL parameters.
  #
  # @return [void]
  #
  def delete_test: ((User|nil) user, ?meth: Symbol|nil, **untyped opt) -> void

  # The default :index action redirects to :list_all for Administrator and
  # :show_current for everyone else.
  #
  # @param [Hash] opt
  #
  # @return [String]
  #
  def index_redirect: (**untyped opt) ?{ () -> (Symbol|String|Proc|nil) } -> String
end
