class PeriodicalsTest < ApplicationSystemTestCase
  PAGE_COUNT: Integer

  # There were 29 results for this search as the anonymous user as of
  # 2019-09-02.
  PERIODICAL_TITLE_SEARCH_TERM: String

  # There were 0 results for this search as the anonymous user as of
  # 2019-09-02 (but there should have been 2).
  # noinspection RubyConstantNamingConvention
  PERIODICAL_EXACT_TITLE_SEARCH_TERM: String
end
