# Utility methods for reporting on records.
#
# @note From UploadWorkflow::Errors::RenderMethods
#
module Record::Rendering
  include Emma::Common

  extend ::Record::Rendering

  # Default label. TODO: I18n
  #
  # @type [String]
  #
  DEFAULT_LABEL: String

  # Show the submission ID if it can be determined for the given item(s).
  #
  # @param [Model, Hash, String, Any, nil] item
  # @param [String]                        default
  #
  # @return [String]
  #
  # @note From Upload::RenderMethods#make_label
  # @note From Upload::Errors::RenderMethods#make_label
  #
  def make_label: (untyped item, ?default: String) -> String

  private

  # SID or ID of *item*
  #
  # @param [Model, Hash, String, Any, nil] item
  #
  # @return [String, nil]
  #
  # === Implementation Notes
  # This exists solely to avoid a 'require' cycle by not making the module
  # dependent on Record::EmmaIdentification.
  #
  def item_identity: (untyped item) -> (String | nil)

  def self.included: (Module base) -> void
end
