ALL_METHODS: symArray

class Object
  # :nocov:
  def account_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def account_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def admin_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def admin_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def advanced_search_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def advanced_search_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def api_migrate_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def api_migrate_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_create_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_create_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_create_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_create_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_delete_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_delete_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_delete_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_delete_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_destroy_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_destroy_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_destroy_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_destroy_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_edit_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_edit_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_edit_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_edit_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_fields_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_fields_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_new_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_new_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_new_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_new_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_reindex_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_reindex_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_update_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_update_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_update_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_update_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_upload_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def bulk_upload_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def cancel_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def cancel_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def cancel_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def cancel_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def cancel_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def cancel_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def check_health_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def check_health_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def check_subsystem_health_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def check_subsystem_health_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def check_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def check_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def confirmation_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def confirmation_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_user_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def create_user_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def dashboard_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def dashboard_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_counts_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_counts_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_submissions_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_submissions_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def data_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_select_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def delete_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_user_session_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def destroy_user_session_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_password_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_password_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_user_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_select_user_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_user_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def edit_user_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def file_download_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def file_download_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def healthcheck_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def healthcheck_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def help_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def help_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def help_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def help_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def home_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def home_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def manifest_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def manifest_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def manifest_item_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def manifest_item_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def manifest_item_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def manifest_item_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def md_proxy_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def md_proxy_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def md_trial_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def md_trial_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def metrics_test_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def metrics_test_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_user_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_user_session_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_user_session_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def new_user_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def password_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def password_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def reedit_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def reedit_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def renew_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def renew_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def retrieval_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def retrieval_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def root_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def root_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def run_state_health_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def run_state_health_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def save_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def save_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_api_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_api_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_call_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_call_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_call_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_call_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_direct_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_direct_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_validate_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def search_validate_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def session_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def session_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def set_run_state_health_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def set_run_state_health_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def show_user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def sign_in_local_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def sign_in_local_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def system_unavailable_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def system_unavailable_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def tool_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def tool_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def unlock_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def unlock_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_account_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_account_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_admin_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_admin_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_manifest_item_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_manifest_item_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_manifest_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_manifest_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_user_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def update_user_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def upload_index_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def upload_index_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def upload_upload_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def upload_upload_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_registration_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_registration_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def version_health_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def version_health_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def version_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def version_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def welcome_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def welcome_url: (*untyped _ignored) ?{ () -> untyped } -> String
end

# SIGN_IN_AS

class Object
  def sign_in_as_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def sign_in_as_url: (*untyped _ignored) ?{ () -> untyped } -> String
end

# BS_AUTH

class Object
  def user_bookshare_omniauth_authorize_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_bookshare_omniauth_authorize_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_bookshare_omniauth_callback_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_bookshare_omniauth_callback_url: (*untyped _ignored) ?{ () -> untyped } -> String
end

# SHIBBOLETH

class Object
  def user_shibboleth_omniauth_authorize_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_shibboleth_omniauth_authorize_url: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_shibboleth_omniauth_callback_path: (*untyped _ignored) ?{ () -> untyped } -> String

  def user_shibboleth_omniauth_callback_url: (*untyped _ignored) ?{ () -> untyped } -> String
end
