# Base class for object-specific serializers that process data passed in as a
# Ruby (hash) object representation.
#
class Search::Api::Serializer::Obj < Api::Serializer::Obj
  include Search::Api::Serializer::Obj::Schema

  include Search::Api::Serializer::Obj::Associations
end
