# IaDownloadService::Properties
#
module IaDownloadService::Properties
  include ApiService::Properties

  # Configuration values from "config/locales/service.en.yml".
  #
  # @type [Hash]
  #
  CONFIGURATION: symHash

  # Maximum length of redirection chain.
  #
  # In the case of IA downloads, this includes both redirections driven by the
  # HTTP redirects and variations attempted within #transmit in order to find
  # a suitable fall-back download format.
  #
  # @type [Integer]
  #
  MAX_REDIRECTS: Integer

  # Authorization header for IA download requests.
  #
  # @type [String]
  #
  # @see https://archive.org/services/docs/api/ias3.html#skip-request-signing
  # @see https://archive.org/account/s3.php
  #
  IA_AUTH: String

  # Cookies to be sent to the IA server.
  #
  # === Implementation Notes
  # These values were obtained from a desktop development VM after installing
  # the "ia" Python script and running "ia configure" with the Email address
  # "emmadso@bookshare.org".  This generates a configuration file ~/.ia which
  # contains an "[s3]" section with the S3 access key and secret, and a
  # "[cookies]" section which contains these values.
  #
  # @see https://archive.org/services/docs/api/internetarchive/quickstart.html#configuring
  #
  IA_COOKIES: String

  # Headers needed to authenticate with the IA server.
  #
  # @type [Hash{String=>String}]
  #
  IA_HEADERS: Hash[String,String]

  # Configuration for the API service.
  #
  # @return [Hash]
  #
  def configuration: () -> symHash

  # Maximum length of redirection chain.
  #
  # @type [Integer]
  #
  def max_redirects: () -> Integer

  private

  def self.included: (Module base) -> void
end
