# Partial record schema for WorldCat API results.
#
# @attr [String] recordSchema   'info:srw/schema/1/dc'
# @attr [String] recordPacking  'xml'
#
# @see https://developer.api.oclc.org/wcv1#operations-SRU-search-sru
#
class Lookup::WorldCat::Record::Response < Lookup::WorldCat::Api::Record
  include Lookup::WorldCat::Shared::CollectionMethods

  include Lookup::WorldCat::Shared::IdentifierMethods

  LIST_ELEMENT: Class

  # Overall total number of matching items.
  #
  # @return [Integer]
  #
  def total_results: () -> Integer
end
