# Base item presenter for "/search" pages.
#
# @!attribute [r] object
#   Set in Draper#initialize
#   @return [Search::Record::MetadataRecord, Search::Record::TitleRecord]
#
class SearchDecorator < BaseDecorator

  @model_type: Symbol

  module Paths
    include BaseDecorator::Paths
  end

  # Definitions available to both classes and instances of either this
  # decorator or its related collection decorator.
  #
  module Methods
    include CssHelper

    include BaseDecorator::Methods

    # Bridge the gap between "emma.search.record" (which defines the order of
    # display of data fields) and "emma.entry.record.emma_data" (which holds
    # the details about each data field).
    #
    # @param [Symbol]    field
    # @param [Hash, nil] config
    #
    # @return [Hash]
    #
    def field_properties: (Symbol field, ?(symHash|nil) config) -> symHash

    # The defined levels for rendering an item hierarchically.
    #
    # @param [Hash] opt
    #
    # @return [Hash{Symbol=>Array<Symbol,Integer>}]
    #
    def field_levels: (**untyped opt) -> Hash[Symbol,Array[Symbol|Integer]]

    # Get the display mode for search results.
    #
    # @return [Symbol]
    #
    def results_type: () -> Symbol

    # Get the display style variant for search results.
    #
    # @return [Symbol]
    #
    def search_style: () -> Symbol

    # CSS class for the colorization button tray.
    #
    # @type [String]
    #
    STYLE_CONTAINER: String

    # Colorization button configuration template.
    #
    # @type [Hash{Symbol=>String,Symbol}]
    #
    STYLE_BUTTON_TEMPLATE: Hash[Symbol,Array[String|Symbol]]

    # Colorization buttons.
    #
    # @type [Hash{Symbol=>Hash}]
    #
    STYLE_BUTTONS: symHash

    # Search result types.
    #
    # @type [Hash{Symbol=>Hash}]
    #
    RESULT_TYPES: symHash

    # Parameters not included in the base path in #search_list_results.
    #
    # @type [Array<Symbol>]
    #
    RESULT_IGNORED_PARAMS: symArray

    # In debug mode, add date and volume information to the title line.
    #
    # @type [Boolean]
    #
    SHOW_EXTENDED_TITLE: bool

    # Indicate whether items should get extended titles.
    #
    def extended_title?: () -> bool

    # In debug mode, add a display of the (supposed) relevancy score.
    #
    # @note This is probably not very helpful for `results_type == :title`.
    #
    # @type [Boolean]
    #
    SHOW_RELEVANCY_SCORE: bool

    # Indicate whether items should show relevancy scores.
    #
    def relevancy_scores?: () -> bool

    # CSS classes for the current search style.
    #
    # @param [String] suffix
    #
    # @return [Array<String>]
    #
    # @see SearchModesHelper#search_style
    #
    def style_classes: (?suffix: String) -> strArray

    # CSS classes for the current results mode.
    #
    # @param [String] suffix
    #
    # @return [Array<String>]
    #
    # @see SearchModesHelper#results_type
    #
    def result_classes: (?suffix: String) -> strArray
  end

  # Definitions available to instances of either this decorator or its related
  # collection decorator.
  #
  # (Definitions that are only applicable to instances of this decorator but
  # *not* to collection decorator instances are not included here.)
  #
  module InstanceMethods
    include BaseDecorator::InstanceMethods

    include Paths

    include Methods
  end

  # Definitions available to both this decorator class and the related
  # collector decorator class.
  #
  # (Definitions that are only applicable to this class but *not* to the
  # collection class are not included here.)
  #
  module ClassMethods
    include BaseDecorator::ClassMethods

    include Paths

    include Methods
  end

  # Cause definitions to be included here and in the associated collection
  # decorator via BaseCollectionDecorator#collection_of.
  #
  module Common
    def self.included: (Module base) -> void
  end

  include Common

  # Create a link to the details show page for the given item.
  #
  # @param [Hash] opt
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def link: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Render a single label/value pair.
  #
  # @param [String, Symbol, nil] label
  # @param [Any, nil]            value
  # @param [Hash]                opt        Passed to super.
  #
  # @return [ActiveSupport::SafeBuffer, nil]
  #
  def render_pair: ((String|Symbol|nil) label, untyped value, **untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Transform a field value for HTML rendering.
  #
  # @param [*]         value
  # @param [Symbol, *] field
  # @param [Hash]      opt            Passed to the render method or super.
  #
  # @return [Field::Type]
  # @return [String]
  # @return [nil]
  #
  def render_value: (untyped value, field: Symbol|String|Array[Symbol|String]|nil, **untyped opt) -> (Field::Type | String | nil)

  # Add date and volume information to the title line.
  #
  # @return [ActiveSupport::SafeBuffer, nil]
  #
  def extended_title: () -> (ActiveSupport::SafeBuffer | nil)

  # Display title of the associated work along with the logo of the source
  # repository.
  #
  # @param [String] css               Characteristic CSS class/selector.
  # @param [Hash]   opt               Passed to #html_div for title and to
  #                                     #prev_next_controls.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see LogoHelper#repository_source_logo
  #
  def title_and_source_logo: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Display title of the associated work along with the source repository.
  #
  # @param [String] css               Characteristic CSS class/selector.
  # @param [Hash]   opt               Passed to #html_div for title and to
  #                                     #prev_next_controls.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see LogoHelper#repository_source
  #
  def title_and_source: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # An element containing controls for moving up and down through the list.
  #
  # @param [String] css       Characteristic CSS class/selector.
  # @param [Hash]   opt       Passed to #prev_record_link and #next_record_link
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def prev_next_controls: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Create a control for jumping to the previous record in the list.
  #
  # @param [Integer, #to_i]      index      Current index.
  # @param [Integer, #to_i, nil] min_index  Default: 0.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see LinkHelper#icon_button
  # @see file:app/assets/javascripts/feature/scroll.js *scrollToPrev()*
  #
  def prev_record_link: (?index: Integer|nil, ?min_index: Integer|nil) -> ActiveSupport::SafeBuffer

  # Create a control for jumping to the next record in the list.
  #
  # @param [Integer, #to_i]      index      Current index.
  # @param [Integer, #to_i, nil] max_index  Default: 1<<32.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see LinkHelper#icon_button
  # @see file:app/assets/javascripts/feature/scroll.js *scrollToNext()*
  #
  def next_record_link: (?index: Integer|nil, ?max_index: Integer|nil) -> ActiveSupport::SafeBuffer

  # Make a clickable link to the display page for the title on the originating
  # repository's web site.
  #
  # @param [Hash] opt     Passed to #record_popup or LinkHelper#external_link.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def source_record_link: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Make a clickable link to retrieve a remediated file.
  #
  # @param [Hash] opt                   Passed to link method except for:
  #
  # @option opt [String] :label         Link text (default: the URL).
  # @option opt [String] :url           Overrides `item.record_download_url`.
  #
  # @return [ActiveSupport::SafeBuffer] HTML link element.
  # @return [nil]                       If no *url* was provided or found.
  #
  # @see RepositoryHelper#emma_retrieval_link
  # @see RepositoryHelper#bs_retrieval_link
  # @see RepositoryHelper#ht_retrieval_link
  # @see RepositoryHelper#ia_retrieval_link
  #
  def source_retrieval_link: (**untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Render a metadata listing of a search result item.
  #
  # @param [Hash, nil] pairs          Additional field mappings.
  # @param [Hash]      opt            Passed to super.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def details: (?pairs: symHash|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Create a container with the repository ID displayed as a link but acting as
  # a popup toggle button and a popup panel which is initially hidden.
  #
  # @param [String] css               Characteristic CSS class/selector.
  # @param [Hash]   opt               To PopupHelper#inline_popup except:
  #
  # @option opt [Hash] :attr          Options for deferred content.
  # @option opt [Hash] :placeholder   Options for transient placeholder.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see file:javascripts/shared/modal-base.js *ModalBase.toggleModal()*
  #
  def record_popup: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Render a single entry for use within a list of items.
  #
  # @param [Hash, nil] pairs          Additional field mappings.
  # @param [Hash]      opt            Passed to super.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def list_item: (?pairs: symHash|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Include control icons below the entry number.
  #
  # @param [Boolean] toggle           If *true* add item toggle.
  # @param [Boolean] controls         If *true* add edit controls.
  # @param [Hash]    opt              Passed to super.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def list_item_number: (?toggle: bool, ?controls: bool, **untyped opt) -> ActiveSupport::SafeBuffer

  # Generate inline edit controls for the search entry.
  #
  # @param [Symbol] type
  #
  # @return [ActiveSupport::SafeBuffer, nil]
  #
  def edit_controls: (?type: Symbol) -> (ActiveSupport::SafeBuffer | nil)

  # Generate an element to display a score for the item.
  #
  # @return [ActiveSupport::SafeBuffer, nil]
  #
  def relevancy_scores: () -> (ActiveSupport::SafeBuffer | nil)

  # Values supporting search result analysis of relevancy scoring.
  #
  # @return [Hash{Symbol=>*}]
  #
  def score_values: () -> symHash

  # Generate a summary of the number of files per each format associated with
  # this item.
  #
  # @param [String] css               Characteristic CSS class/selector.
  # @param [Hash]   opt               Passed to outer :ul.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def format_counts: (?css: String|nil, **untyped opt) -> ActiveSupport::SafeBuffer
end
