# Collection presenter for "/search" pages.
#
# @!attribute [r] object
#   Set in Draper#initialize
#   @return [Array<Search::Record::MetadataRecord>,Array<Search::Record::TitleRecord>]
#
class SearchesDecorator < BaseCollectionDecorator
  # This causes automated testing to slow down too much, so related server-side
  # and client-side code is neutralized in the test environment.
  #
  # @type [Boolean]
  #
  SEARCH_ANALYSIS: bool

  # Controls for applying one or more search style variants.
  #
  # @param [Hash] opt                 Passed to outer #html_div.
  #
  # @return [ActiveSupport::SafeBuffer]
  # @return [nil]
  #
  # @see #STYLE_BUTTONS
  # @see SearchModesHelper#permitted_by?
  # @see file:javascripts/feature/search-analysis.js *AdvancedFeature*
  #
  def list_styles: (**untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Control for selecting the type of search results to display.
  #
  # @param [String,Symbol,nil] selected  Selected menu item.
  # @param [Hash]              opt       Passed to outer #html_div.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  # @see #RESULT_TYPES
  # @see SearchModesHelper#results_type
  # @see SearchModesHelper#permitted_by?
  # @see file:app/assets/javascripts/controllers/search.js *$mode_menu*
  #
  def list_results: (?selected: String|Symbol|nil, **untyped opt) -> ActiveSupport::SafeBuffer
end
