# Item presenter for hierarchical result "/search" pages.
#
# @!attribute [r] object
#   Set in Draper#initialize
#   @return [Search::Record::TitleRecord]
#
class SearchTitleDecorator < SearchDecorator
  # Render a single entry for use within a list of items.
  #
  # @param [Hash, nil] pairs          Additional field mappings.
  # @param [Hash]      opt            Passed to super.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def list_item: (?pairs: symHash|nil, **untyped opt) -> ActiveSupport::SafeBuffer

  # Include control icons below the entry number.
  #
  # @param [Boolean] edit             If *false* do not add edit controls.
  # @param [Hash]    opt              Passed to super.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def list_item_number: (?edit: bool, **untyped opt) -> ActiveSupport::SafeBuffer
end
