module ActiveSupport
  module LogSubscriberExt
    # Also check whether log output is globally suppressed.
    #
    # @param [any, nil] event
    #
    def silenced?: (untyped event) -> bool
  end
end
