# Base class for object-specific serializers that process XML data.
#
class Ingest::Api::Serializer::Xml < Api::Serializer::Xml
  include Ingest::Api::Serializer::Xml::Schema

  include Ingest::Api::Serializer::Xml::Associations
end
