# XML-specific definition overrides for serialization.
#
# @see Api::Serializer::Xml::Schema
#
module Lookup::RemoteService::Api::Serializer::Xml::Schema
  include Lookup::RemoteService::Api::Serializer::Schema

  include Api::Serializer::Xml::Schema
end
