# Acquire file content for downloading via the Internet Archive
# "Printdisabled Unencrypted Ebook API".
#
# Currently there are no data fields associated with the received message; the
# body of the response is the content of the file being downloaded.
#
class IaDownload::Message::FetchResponse < IaDownload::Api::Message
  include IaDownload::Shared::ResponseMethods

  # @type [Faraday::Response]
  attr_reader response: Faraday::Response

  # Initialize a new instance.
  #
  # @param [Faraday::Response] src
  # @param [Hash, nil]         opt
  #
  def initialize: (Faraday::Response src, ?(symHash|nil) opt) -> void

  # The response body.
  #
  # @return [String, nil]
  #
  def content: () -> (String | nil)

  # The 'Content-Type' header.
  #
  # @return [String]
  #
  def type: () -> String

  # The 'Content-Disposition' header.
  #
  # @return [String]
  #
  def disposition: () -> String

  # File name from 'Content-Disposition' if present.
  #
  # @return [String, nil]
  #
  def filename: () -> (String | nil)

  def to_h: () -> symHash
end
