# Entry modification workflow tracking record.
#
# @see file:config/locales/state_table.en.yml *en.emma.state_table.phase.edit*
#
# @!method started?
# @!method uploading?
# @!method replacing?
# @!method indexing?
# @!method indexed?
# @!method submitting?
# @!method submitted?
# @!method canceling?
# @!method canceled?
# @!method aborted?
#
# @!method started!
# @!method uploading!
# @!method replacing!
# @!method indexing!
# @!method indexed!
# @!method submitting!
# @!method submitted!
# @!method canceling!
# @!method canceled!
# @!method aborted!
#
class Phase::Edit < Phase::BulkPart
  include Record::Sti::Leaf

  include Record::EmmaData

  include Record::Steppable

  include Record::Uploadable

  # Upload file to AWS S3 Shrine :cache.
  #
  # @param [ActionDispatch::Request, Hash, nil] request
  # @param [Hash] opt                 Passed to Action::Store#update! except:
  #
  # @option opt [Boolean] :async      Always ignored.
  #
  # @raise [ActiveRecord::RecordInvalid]    Action record creation failed.
  # @raise [ActiveRecord::RecordNotSaved]   Action record creation halted.
  #
  # @return [Array<(Integer, Hash{String=>Any}, Array<String>)>]
  #
  # @see Action::Store#upload!
  #
  # == Usage Notes
  # Always performed synchronously.
  #
  def upload!: (symHash|ActionDispatch::Request|nil request, **untyped opt) -> httpResult

  # Method called from the action launched by #upload!.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [Boolean]   *false* if the callback's callback failed to process.
  #
  # == Usage Notes
  # Will be performed synchronously by Action::Store#upload!.
  #
  def upload_cb: (?Action? action, **untyped opt) -> bool

  # Move uploaded file from Shrine :cache to Shrine :store.
  #
  # @param [Hash] opt                 Passed to Action::Store#promote!
  #
  # @return [nil]       Failed to transition record to the new state.
  # @return [Boolean]   *false* if the action could not be processed.
  #
  def promote!: (**untyped opt) -> (bool | nil)

  # Method called from the action launched by #promote!.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [Boolean]   *false* if the callback's callback failed to process.
  #
  def promote_cb: (?Action? action, **untyped opt) -> bool

  # Create an index entry for this item.
  #
  # @param [Hash] opt                 Passed to Action::Index#index!
  #
  # @raise [ActiveRecord::RecordInvalid]    Action record creation failed.
  # @raise [ActiveRecord::RecordNotSaved]   Action record creation halted.
  #
  # @return [nil]       Failed to transition record to the new state.
  # @return [Boolean]   *false* if the action could not be processed.
  #
  def index!: (**untyped opt) -> (bool | nil)

  # Method called from the action launched by #index!.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [Boolean]   *false* if the callback's callback failed to process.
  #
  def index_cb: (?Action? action, **untyped opt) -> bool

  # Send a submission package to a member repository.
  #
  # @param [Hash] opt                 Passed to Action::Queue#submit!
  #
  # @raise [ActiveRecord::RecordInvalid]    Action record creation failed.
  # @raise [ActiveRecord::RecordNotSaved]   Action record creation halted.
  #
  # @return [nil]       Failed to transition record to the new state.
  # @return [Boolean]   *false* if the action could not be processed.
  #
  def submit!: (**untyped opt) -> (bool | nil)

  # Method called from the action launched by #submit!.
  #
  # @param [Action] action
  # @param [Hash]   opt
  #
  # @return [Boolean]   *false* if the callback's callback failed to process.
  #
  def submit_cb: (?Action? action, **untyped opt) -> bool

  # A textual description of the type of the Model instance.
  #
  # @param [Phase] phase
  # @param [Hash]  opt
  #
  # @return [String]
  #
  def self.describe_type: (Phase phase, **untyped opt) -> String

  # A textual description of the status of the given Phase instance.
  #
  # @param [Phase] phase
  # @param [Hash]  opt
  #
  # @return [String]
  #
  def self.describe_status: (Phase phase, **untyped opt) -> String
end
