# General shared methods.
#
module Lookup::Crossref::Shared::CommonMethods
  include Lookup::RemoteService::Shared::CommonMethods

  extend ::Lookup::Crossref::Shared::CommonMethods

  EXTENDED_FIELDS: bool

  COMPLETE_FIELDS: bool

  EXT: bool

  ALL: bool

  # A traversal through the hierarchy rooted at the class instance which
  # holds all of the metadata for a single lookup result item.
  #
  # @type [Array<Symbol>]
  #
  ITEM_PATH: symArray

  # A traversal through the hierarchy rooted at the class instance which
  # holds all of the metadata for a single lookup result item.
  #
  # @return [Array<Symbol>]
  #
  def item_record_path: () -> symArray
end
