# This is included in record classes that define :BASE_ELEMENT to confirm that
# they are intended to function as aggregates.
#
# @see Model::ClassMethods#validate_relations
#
module Lookup::Crossref::Shared::AggregateMethods
  include Lookup::RemoteService::Shared::AggregateMethods
  include Lookup::Crossref::Shared::CommonMethods
end
