# Base class for object-specific serializers that process JSON data.
#
class Lookup::WorldCat::Api::Serializer::Json < Lookup::RemoteService::Api::Serializer::Json
  include Lookup::WorldCat::Api::Serializer::Json::Schema

  include Lookup::WorldCat::Api::Serializer::Json::Associations
end
