# Base class for object-specific serializers that process data passed in as a
# Ruby (hash) object representation.
#
class Lookup::WorldCat::Api::Serializer::Obj < Lookup::RemoteService::Api::Serializer::Obj
  include Lookup::WorldCat::Api::Serializer::Obj::Schema

  include Lookup::WorldCat::Api::Serializer::Obj::Associations
end
