# Shared view helper methods supporting document '<head>' entries.
#
module HeadHelper::Common
  include Emma::Common

  # Configuration for '<head>' properties.
  #
  # @type [Hash{Symbol=>*}]
  #
  HEAD_CONFIG: symHash
end
