# JSON-specific definition overrides for serialization.
#
# @see Api::Serializer::Json::Schema
#
module Ingest::Api::Serializer::Json::Schema
  include Ingest::Api::Serializer::Schema

  include Api::Serializer::Json::Schema
end
