# Base class for SubmissionService responses.
#
# @see SubmitChannel::Response
#
class SubmissionService::Response < ApplicationJob::Response
  include SubmissionService::Common

  TEMPLATE: symHash

  # Create a new instance.
  #
  # @param [SubmissionService::Response, Hash, Array, *] values
  # @param [Hash]                                        opt
  #
  def initialize: (?untyped? values, **untyped opt) -> void

  # Indicate whether this response is part of a simulation.
  #
  def simulation?: () -> bool

  def self.template: () -> symHash

  def self.batch?: () -> bool

  def batch?: () -> bool
end

# Response object for a submission request.
#
# @see SubmitChannel::SubmitResponse
# @see file:javascripts/shared/submit-response.js *SubmitResponse*
#
class SubmissionService::SubmitResponse < SubmissionService::Response
  TEMPLATE: symHash

  def self.template: () -> symHash
end

# Initial response object for a submission request.
#
# @see SubmitChannel::InitialResponse
#
class SubmissionService::InitialResponse < SubmissionService::SubmitResponse
  def self.default_status: () -> String
end

# Response object for a submission request.
#
# @see SubmitChannel::StepResponse
# @see file:javascripts/shared/submit-response.js *SubmitStepResponse*
#
class SubmissionService::StepResponse < SubmissionService::SubmitResponse
  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.default_status: () -> String
end

# Response object for a submission request.
#
# @see SubmitChannel::StepResponse
# @see file:javascripts/shared/submit-response.js *SubmitStepResponse*
#
class SubmissionService::BatchSubmitResponse < SubmissionService::SubmitResponse
  def self.default_status: () -> String

  def self.batch?: () -> bool
end

# Final response object for a submission request.
#
# @see SubmitChannel::FinalResponse
#
class SubmissionService::FinalResponse < SubmissionService::StepResponse
  def self.default_status: () -> String
end

# Response object for a control request.
#
# @see SubmitChannel::ControlResponse
# @see file:javascripts/shared/submit-response.js *SubmitControlResponse*
#
class SubmissionService::ControlResponse < SubmissionService::Response
  TEMPLATE: symHash

  def self.template: () -> symHash

  def self.default_status: () -> String
end
