# Common logic for all channels.
#
class ApplicationCable::Channel < ActionCable::Channel::Base
  include ApplicationCable::Common

  include ApplicationCable::Payload

  # stream_id
  #
  # @return [String, nil]
  #
  # @see file:javascripts/shared/cable-channel.js *streamId()*
  #
  def stream_id: () -> (String | nil)

  # stream_name
  #
  # @param [String, Symbol, nil] base
  #
  # @return [String]
  #
  # @see file:javascripts/shared/cable-channel.js *streamName()*
  #
  def stream_name: (?(String|Symbol|nil) base) -> String

  # Setup for a subscription called when the consumer has successfully become a
  # subscriber to this channel.
  #
  # @return [void]
  #
  # @see file:javascripts/shared/cable-consumer.js *createChannel()*
  #
  def subscribed: () -> void

  # Any cleanup needed when the channel is unsubscribed.
  #
  # @return [void]
  #
  # @see file:javascripts/shared/cable-channel.js  *disconnect()*
  # @see file:javascripts/shared/cable-consumer.js *closeChannel()*
  #
  def unsubscribed: () -> void

  # Receive data from the client.
  #
  # @param [any, nil] payload
  # @param [Hash]     opt
  #
  # @return [Hash]
  #
  def stream_recv: (untyped payload, **untyped opt) -> symHash

  # Push data to the client.
  #
  # @param [ApplicationCable::Response] payload
  # @param [Hash]                       opt
  #
  # @option opt [Boolean] :fatal      Passed to #stream_send.
  #
  # @return [void]
  #
  def stream_send: (ApplicationCable::Response payload, **untyped opt) -> void

  # Push data to the client.
  #
  # @param [ApplicationCable::Response] payload
  # @param [Boolean]                    fatal
  # @param [Hash]                       opt
  #
  # @return [void]
  #
  def self.stream_send: (ApplicationCable::Response payload, ?fatal: bool, **untyped opt) -> void

  def deliver_error_message: (Exception e) -> void
end
