# ApplicationCable::Connection
#
# @!attribute [rw] current_user
#   The authenticated user defined in #identified_by and set in #connect.
#   @return [User, nil]
#
class ApplicationCable::Connection < ActionCable::Connection::Base
  include ApplicationCable::Common

  # The method called before the WebSocket connection is opened.
  #
  # @return [void]
  #
  def connect: () -> void

  # The method called after the WebSocket connection is closed.
  #
  # @return [void]
  #
  def disconnect: () -> void

  # Return the Devise-authenticated user.
  #
  # @raise [ActionCable::Connection::Authorization::UnauthorizedError]
  #
  # @return [User]
  #
  def get_verified_user: () -> User

  # report_error
  #
  # @param [Exception] e
  #
  # @return [void]
  #
  def report_error: (Exception e) -> void
end
