# A request to change to a prior submission to a partner repository.
#
# @note This capability is not currently supported by any partner repository.
#
class AwsS3::Record::ModificationRequest < AwsS3::Record::SubmissionRequest
end
