# A request to delete a prior submission to a member repository.
#
# @note This capability is not currently supported by any member repository.
#
class AwsS3::Record::RemovalRequest < AwsS3::Record::SubmissionRequest
end
