# IngestService::Properties
#
module IngestService::Properties
  include ApiService::Properties

  # Configuration values from config/locales/service.en.yml
  #
  # @type [Hash{Symbol=>Any}]
  #
  CONFIGURATION: symHash

  # Default engine selection.
  #
  # @type [Symbol]
  #
  DEFAULT_ENGINE: Symbol

  # Configuration for the EMMA Unified Ingest service.
  #
  # @type [Hash{Symbol=>Any}]
  #
  def configuration: () -> symHash

  # EMMA Unified Ingest API key.
  #
  # @return [String, nil]
  #
  # @see #INGEST_API_KEY
  #
  def api_key: () -> (String | nil)

  # Default ingest engine for this deployment.
  #
  # @return [String]
  #
  def default_engine_url: () -> String

  # The default ingest engine API key.
  #
  # @return [Symbol]
  #
  def default_engine_key: () -> Symbol

  private

  def self.included: (Module base) -> void
end
