# Interface to the shared data structure which holds the definition of the EMMA
# Unified Ingest API requests and parameters.
#
module IngestService::Definition
  private

  def self.included: (Module base) -> void
end
