# Bs::Message::ActiveBookList
#
# @attr [Array<Bs::Record::ActiveBook>] activeTitles
# @attr [Array<BsAllowsType>]           allows
# @attr [Integer]                       limit
# @attr [Array<Bs::Record::Link>]       links
# @attr [Bs::Record::StatusModel]       message
# @attr [String]                        next
# @attr [Integer]                       totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_active_book_list
#
# @see Bs::Message::ActivePeriodicalList (similar schema)
#
class Bs::Message::ActiveBookList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
