# Bs::Message::AssignedTitleMetadataSummaryList
#
# @attr [Array<BsAllowsType>]                             allows
# @attr [Integer]                                         limit
# @attr [Array<Bs::Record::Link>]                         links
# @attr [Bs::Record::StatusModel]                         message
# @attr [String]                                          next
# @attr [Array<Bs::Record::AssignedTitleMetadataSummary>] titles
# @attr [Integer]                                         totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_assigned_title_metadata_summary_list
#
# @see Bs::Message::TitleMetadataSummaryList (similar schema)
#
class Bs::Message::AssignedTitleMetadataSummaryList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
