# Bs::Message::BisacCodeList
#
# @attr [Array<Bs::Record::BisacCode>] bisacCodes
# @attr [Integer]                      limit
# @attr [String]                       next
# @attr [Integer]                      totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_bisac_code_list
#
class Bs::Message::BisacCodeList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
