# Bs::Message::ErrorModel
#
# @see Bs::Record::StatusModel
# @see https://apidocs.bookshare.org/reference/index.html#_error_model
#
class Bs::Message::ErrorModel < Bs::Api::Message
  # Convert object to string.
  #
  # @return [String]
  #
  def to_s: () -> String

  # A label for the item.
  #
  # @return [String]
  #
  def label: () -> String
end
