# Bs::Message::OauthTokenError
#
# @attr [BsTokenErrorType] error
# @attr [String]           error_description
#
# @see ApiService::Error#oauth2_error_header
# @see https://apidocs.bookshare.org/auth/index.html#_token_error
#
class Bs::Message::OauthTokenError < Bs::Api::Message
end
