# Bs::Message::PeriodicalEditionList
#
# @attr [Array<BsAllowsType>]                  allows
# @attr [Integer]                              limit
# @attr [Array<Bs::Record::Link>]              links
# @attr [Bs::Record::StatusModel]              message
# @attr [String]                               next
# @attr [Array<Bs::Record::PeriodicalEdition>] periodicalEditions
# @attr [Integer]                              totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_periodical_edition_list
#
class Bs::Message::PeriodicalEditionList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
