# Bs::Message::OrganizationTypeList
#
# @attr [Array<Bs::Record::Link>]                   links
# @attr [Array<Bs::Record::PeriodicalSubscription>] titles
#
# @see https://apidocs.bookshare.org/reference/index.html#_periodical_subscription_list
#
class Bs::Message::PeriodicalSubscriptionList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
