# Bs::Message::PeriodicalSeriesMetadataSummaryList
#
# @attr [Array<BsAllowsType>]                                allows
# @attr [Integer]                                            limit
# @attr [Array<Bs::Record::Link>]                            links
# @attr [Bs::Record::StatusModel]                            message
# @attr [String]                                             next
# @attr [Array<Bs::Record::PeriodicalSeriesMetadataSummary>] periodicals
# @attr [Integer]                                            totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_periodical_series_metadata_summary_list
#
class Bs::Message::PeriodicalSeriesMetadataSummaryList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
