# Bs::Message::PopularList
#
# @attr [String]                                  description
# @attr [String]                                  id
# @attr [Integer]                                 limit
# @attr [Array<Bs::Record::Link>]                 links
# @attr [String]                                  next
# @attr [Array<Bs::Record::TitleMetadataSummary>] popularTitles
# @attr [Integer]                                 totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_popular_list
#
class Bs::Message::PopularList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: Class
end
