# Bs::Message::ReadingListTitlesList
#
# @attr [Array<BsAllowsType>]                 allows
# @attr [Integer]                             limit
# @attr [Array<Bs::Record::Link>]             links
# @attr [String]                              next
# @attr [String]                              readingListId
# @attr [Array<Bs::Record::ReadingListTitle>] titles
# @attr [Integer]                             totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_reading_list_titles_list
#
class Bs::Message::ReadingListTitlesList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  include Bs::Shared::ReadingListMethods

  LIST_ELEMENT: untyped
end
