# Bs::Message::TitleMetadataSummary
#
# @see Bs::Record::TitleMetadataSummary
#
class Bs::Message::TitleMetadataSummary < Bs::Api::Message
  include Bs::Shared::ArtifactMethods

  include Bs::Shared::CreatorMethods

  include Bs::Shared::IdentifierMethods

  include Bs::Shared::LinkMethods

  include Bs::Shared::TitleMethods
end
