# Bs::Message::TitleMetadataCompleteList
#
# @attr [Array<BsAllowsType>]                      allows
# @attr [Integer]                                  limit
# @attr [Array<Bs::Record::Link>]                  links
# @attr [String]                                   next
# @attr [Array<Bs::Record::TitleMetadataComplete>] titles
# @attr [Integer]                                  totalResults
#
# @see https://apidocs.bookshare.org/catalog/index.html#_title_metadata_complete_list
#
class Bs::Message::TitleMetadataCompleteList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
