# Bs::Message::TitleHistoryEventResourceList
#
# @attr [Array<Bs::Record::Link>]              links
# @attr [String]                               next
# @attr [Array<Bs::Record::TitleFileResource>] titleFileResources
#
# @see https://apidocs.bookshare.org/catalog/index.html#_title_history_event_resource_list
#
class Bs::Message::TitleHistoryEventResourceList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  LIST_ELEMENT: untyped
end
