# Bs::Message::TitleDownloadList
#
# @attr [Array<BsAllowsType>]              allows
# @attr [Array<Bs::Record::Link>]          links
# @attr [String]                           next
# @attr [Array<Bs::Record::TitleDownload>] titleDownloads
# @attr [Integer]                          totalResults
#
# @see https://apidocs.bookshare.org/reference/index.html#_title_download_list
#
class Bs::Message::TitleDownloadList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
