# Bs::Message::UserSignedAgreementList
#
# @attr [Array<BsAllowsType>]                    allows
# @attr [Array<Bs::Record::Link>]                links
# @attr [Array<Bs::Record::UserSignedAgreement>] signedAgreements
#
# @see https://apidocs.bookshare.org/membership/index.html#_user_signed_agreement_list
#
class Bs::Message::UserSignedAgreementList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
