# Bs::Message::UserSubscriptionList
#
# @attr [Array<BsAllowsType>]                 allows
# @attr [Integer]                             limit
# @attr [Array<Bs::Record::Link>]             links
# @attr [String]                              next
# @attr [Integer]                             totalResults
# @attr [Array<Bs::Record::UserSubscription>] userSubscriptions
#
# @see https://apidocs.bookshare.org/membership/index.html#_user_subscription_list
#
class Bs::Message::UserSubscriptionList < Bs::Api::Message
  include Bs::Shared::CollectionMethods

  include Bs::Shared::LinkMethods

  LIST_ELEMENT: untyped
end
