# Methods supporting manipulation of Model instance fields for collections.
#
module BaseCollectionDecorator::Fields
  include BaseDecorator::Fields

  private

  def self.included: (Module base) -> void
end
