# Common methods supporting display of Model instances (both database items and
# API messages).
#
module BaseCollectionDecorator::Links
  include BaseDecorator::Links

  include BaseCollectionDecorator::Common

  private

  def self.included: (Module base) -> void
end
