# View helper methods supporting display of Model instances (both database
# items and API messages).
#
module BaseCollectionDecorator::List
  include BaseDecorator::List

  # Render list items.
  #
  # @param [Integer]       index      Starting index number.
  # @param [Integer]       row        Starting row number.
  # @param [Array<Symbol>] skip       Passed to #list_row.
  # @param [String, nil]   separator  If *nil*, return an array of lines.
  # @param [Hash]          opt        Passed to #list_row.
  #
  # @return [Array<ActiveSupport::SafeBuffer>]  If *separator* set to *nil*.
  # @return [ActiveSupport::SafeBuffer]
  #
  def render: (?index: Integer, ?row: Integer, ?skip: symArray?, ?separator: String, **untyped opt) -> ActiveSupport::SafeBuffer
            | (?index: Integer, ?row: Integer, ?skip: symArray?, separator: nil,     **untyped opt) -> Array[ActiveSupport::SafeBuffer]

  # Text for #no_records_row. # TODO: I18n
  #
  # @type [String]
  #
  NO_RECORDS: String

  # Hidden row that is shown only when no field rows are being displayed.
  #
  # @param [Hash] opt                 Passed to created elements.
  #
  # @return [ActiveSupport::SafeBuffer]
  #
  def no_records_row: (**untyped opt) -> ActiveSupport::SafeBuffer

  # Options used with template :locals.
  #
  # @type [Array<Symbol>]
  #
  VIEW_TEMPLATE_OPT: symArray

  # Generate applied search terms and top/bottom pagination controls.
  #
  # @param [Integer, #to_i, nil] count    Default: *list* size.
  # @param [Integer, #to_i, nil] total    Default: count.
  # @param [Integer, #to_i, nil] records  Number of API records for this page.
  # @param [Integer, #to_i, nil] page     Default: 1.
  # @param [Integer, #to_i, nil] size     Default: TODO: default page size
  # @param [Integer, #to_i, nil] row      Default: 1.
  # @param [Hash]    opt                  Passed to #list_controls.
  #
  # @return [Array<(ActiveSupport::SafeBuffer,ActiveSupport::SafeBuffer)>]
  #
  def index_controls: (?count: Integer?, ?total: Integer?, ?records: Integer?, ?page: Integer?, ?size: Integer?, ?row: Integer?, **untyped opt) -> [ActiveSupport::SafeBuffer, ActiveSupport::SafeBuffer]

  # Optional controls to modify the display or generation of the item list in
  # the order of display.
  #
  # @type [Array<Symbol>]
  #
  LIST_CONTROL_METHODS: symArray

  # Optional controls to modify the display or generation of the item list in
  # the order of display.
  #
  # @return [Array<Symbol>]
  #
  def list_control_methods: () -> symArray

  # Optional controls to modify the display or generation of the item list.
  #
  # @param [Hash] opt
  #
  # @return [Array<ActiveSupport::SafeBuffer>]
  #
  def list_controls: (**untyped opt) -> Array[ActiveSupport::SafeBuffer]

  # Optional list style controls in line with the top pagination control.
  #
  # @param [Hash] opt
  #
  # @return [ActiveSupport::SafeBuffer, nil]
  #
  def list_styles: (**untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # Optional list result type controls in line with the top pagination control.
  #
  # @param [Hash] opt
  #
  # @return [ActiveSupport::SafeBuffer, nil]
  #
  def list_results: (**untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  # An optional list filter control in line with the top pagination control.
  #
  # @param [Hash] opt
  #
  # @return [ActiveSupport::SafeBuffer, nil]
  #
  def list_filter:         (**untyped opt) -> (ActiveSupport::SafeBuffer | nil)

  def list_filter_options: (**untyped opt) -> (ActiveSupport::SafeBuffer | nil)
end
