# Methods supporting selectable lists of Model instances.
#
module BaseCollectionDecorator::Menu
  include BaseDecorator::Menu

  include BaseCollectionDecorator::Common

  private

  def self.included: (Module base) -> void
end
