# Methods supporting managed downloads.
#
module BaseCollectionDecorator::Retrievals
  include BaseDecorator::Retrieval

  include BaseCollectionDecorator::Common

  private

  def self.included: (Module base) -> void
end
