# XML-specific definition overrides for serialization.
#
# @see Api::Serializer::Xml::Schema
#
module AwsS3::Api::Serializer::Xml::Schema
  include AwsS3::Api::Serializer::Schema

  include Api::Serializer::Xml::Schema

  # If this value is *false* then #attribute schema values are serialized
  # (rendered) as XML attributes; if *true* then they are serialized as XML
  # elements (removing the distinction between #attribute and #has_one).
  #
  # This method overrides:
  # @see Api::Serializer::Xml::Schema#attributes_as_elements?
  #
  def attributes_as_elements?: () -> bool
end
