module Download::Config
  # Used by methods defined in modules to allow the primary argument to be
  # missing/nil when used as a record instance method.
  #
  # @param [*, nil] item
  # @param [Symbol] from
  #
  # @return [*, Download]
  #
  def default_to_self
    :     (nil item, ?from: Symbol|nil) -> Download
    | [T] (T   item, ?from: Symbol|nil) -> T
end
