# Upload record methods to support management of EMMA metadata fields.
#
module Upload::EmmaDataMethods
  include Record::EmmaData

  include Record::EmmaData::StringEmmaData

  include Upload::WorkflowMethods

  # Core table columns.
  #
  # @type [Array<Symbol>]
  #
  DATA_COLUMNS: symArray

  # Edit process table columns.
  #
  # @type [Array<Symbol>]
  #
  EDIT_COLUMNS: symArray

  # Review process table columns.
  #
  # @type [Array<Symbol>]
  #
  REVIEW_COLUMNS: symArray

  # The database column currently associated with EMMA metadata presented by
  # the record.
  #
  # @return [Symbol]
  #
  def emma_data_column: () -> Symbol

  # The EMMA metadata currently associated with the record.
  #
  # @return [String, nil]
  #
  def active_emma_data: () -> (String | nil)

  # init_emma_data_value
  #
  # @param [any, nil] _data
  #
  # @return [String, nil]
  #
  def init_emma_data_value: (untyped _data) -> (String | nil)

  # Present :edit_emma_data as a structured object (if it is present).
  #
  # @return [Search::Record::MetadataRecord]
  #
  def edit_emma_record: () -> Search::Record::MetadataRecord

  @edit_emma_record: Search::Record::MetadataRecord | nil

  # Present :edit_emma_data as a hash (if it is present).
  #
  # @return [Hash]
  #
  def edit_emma_metadata: () -> symHash

  @edit_emma_metadata: symHash | nil

  # Set the :edit_emma_data field value.
  #
  # @param [Search::Record::MetadataRecord, Hash, String, nil] data
  # @param [Boolean]                                           blanks
  #
  # @return [String]
  # @return [nil]                     If *data* is *nil*.
  #
  def set_edit_emma_data: ((symHash|String|Search::Record::MetadataRecord|nil) data, ?blanks: bool) -> (String | nil)

  # Selectively modify the :edit_emma_data field value.
  #
  # @param [Hash]    data
  # @param [Boolean] blanks
  #
  # @return [String, nil]
  #
  def modify_edit_emma_data: (symHash data, ?blanks: bool) -> (String | nil)

  # init_edit_emma_data_value
  #
  # @param [any, nil] _data
  #
  # @return [String, nil]
  #
  def init_edit_emma_data_value: (untyped _data) -> (String | nil)

  # curr_edit_emma_data_value
  #
  # @return [String, nil]
  #
  def curr_edit_emma_data_value: () -> (String | nil)

  # Present the EMMA data currently associated with the record as a
  # structured object.
  #
  # @return [Search::Record::MetadataRecord]
  #
  def active_emma_record: () -> Search::Record::MetadataRecord

  # Present the EMMA data currently associated with the record as a hash.
  #
  # @return [Hash]
  #
  def active_emma_metadata: () -> symHash

  # Set the EMMA data currently associated with the record.
  #
  # @param [Search::Record::MetadataRecord, Hash, String, nil] data
  # @param [Boolean]                                           blanks
  #
  # @return [String]
  # @return [nil]                     If *data* is *nil*.
  #
  def set_active_emma_data: ((symHash|String|Search::Record::MetadataRecord|nil) data, ?blanks: bool) -> (String | nil)

  # Selectively modify the EMMA data currently associated with the record.
  #
  # @param [Hash]    data
  # @param [Boolean] allow_blank
  #
  # @return [String, nil]
  #
  def modify_active_emma_data: (symHash data, ?blanks: bool) -> (String | nil)

  private

  def self.included: (Module base) -> void
end
