# URL parameter options related to Upload records.
#
class Upload::Options < Options
  # include UploadWorkflow::Properties # NOTE: This ends up being problematic.
  include Record::Properties

  def self.model_id_key: () -> Symbol

  def option_keys: () -> symArray

  def option_method: ((Symbol|String) key) -> (Symbol | nil)

  # MODEL_DATA_PARAMS
  #
  # @type [Hash{Symbol=>Symbol}]
  #
  # === Implementation Notes
  # The value `params[:upload][:emma_data]` is ignored because it reports the
  # original metadata values that were supplied to the edit form.  The value
  # `params[:upload][:file]` is ignored if it is blank or is the JSON
  # representation of an empty object ("{}") -- this indicates an editing
  # submission where metadata is being changed but the uploaded file is not
  # being replaced.
  #
  MODEL_DATA_PARAMS: Hash[Symbol, Symbol]

  def model_data_params: () -> Hash[Symbol, Symbol]
end
