# Methods for applying a sort order to sets of records.
#
module Upload::SortMethods
  include Record::Sortable

  extend ::Upload::SortMethods

  # Sort order applied by default in #get_relation.
  #
  # @return [Symbol, String, Hash]
  #
  def default_sort: () -> (Symbol | String | anyHash)

  private

  def self.included: (untyped base) -> untyped
end
