# ApiService::Identity
#
module ApiService::Identity
  # The user that caused the #api method to be invoked.
  #
  # @return [User, nil]
  #
  attr_reader user: User | nil

  # Extract the user name to be used for API parameters.
  #
  # @param [User, String] user
  #
  # @return [String]
  #
  def name_of: ((User|String|nil) user) -> String

  # Set the user for the current session.
  #
  # @param [User, nil] u
  #
  # @raise [RuntimeError]             If *u* is invalid.
  #
  # @return [void]
  #
  def set_user: ((User|nil) u) -> void

  # The current OAuth2 access bearer token (if applicable).
  #
  # @return [String, nil]
  #
  def access_token: () -> (String | nil)

  # The current OAuth2 refresher token (if applicable).
  #
  # @return [String, nil]
  #
  def refresh_token: () -> (String | nil)
end
