module Manifest::Searchable
  # :nocov:
  #include Record::Searchable

  # Because UUIDs are not ordered, Manifests can't support pagination as it is
  # currently implemented.
  #
  # @return [nil]
  #
  def pagination_column: () -> nil

  # Sort order applied by default in #get_relation.
  #
  # @return [Symbol, String, Hash]
  #
  def default_sort: () -> (Symbol | String | anyHash)

  private

  def self.included: (Module base) -> void
end
