# BookshareService::Action::Organization
#
# == Usage Notes
#
# === From API section 2.7 (Organization):
# An organization represents a collection of users, either sponsors or members.
# These might be schools, libraries or other organizations that work on behalf
# of qualified individuals.  Members of an organization are sometimes
# restricted in what actions they can perform, with sponsors acting on their
# behalf to do things like download titles.  Sponsors have some limited
# administrative abilities in their organizations, to add, update and remove
# individual members.
#
module BookshareService::Action::Organization
  include BookshareService::Common

  include BookshareService::Testing

  # == GET /v2/myOrganization/members
  #
  # == 2.7.1. Get a list of members of my organization
  # Get a list of members of the current (sponsor) user's organization.
  #
  # @param [Hash]   opt               Passed to #api.
  #
  # @option opt [String]            :start
  # @option opt [Integer]           :limit      Default: 10
  # @option opt [BsMemberSortOrder] :sortOrder  Default: 'lastName'
  # @option opt [BsSortDirection]   :direction  Default: 'asc'
  #
  # @return [Bs::Message::UserAccountList]
  #
  # @see https://apidocs.bookshare.org/reference/index.html#_get-myorganization-members
  #
  def get_my_organization_members: (**untyped opt) -> Bs::Message::UserAccountList

  # == GET /v2/myOrganization/members/(userIdentifier)
  #
  # Get a member of the current (sponsor) user's organization.
  #
  # @param [User, String, nil] user
  # @param [Hash]              opt    Passed to #api.
  #
  # @return [Bs::Message::UserAccount]
  #
  # @note This is not a real Bookshare API call.
  #
  def get_my_organization_member: (user: User|String|nil, **untyped opt) -> Bs::Message::UserAccount

  # == POST /v2/myOrganization/members
  #
  # == 2.7.2. Create a user for my organization
  # Create a new user account for the current user's organization.
  #
  # @param [Hash] opt                 Passed to #api.
  #
  # @option opt [String]                    :firstName              *REQUIRED*
  # @option opt [String]                    :lastName               *REQUIRED*
  # @option opt [String]                    :dateOfBirth            *REQUIRED*
  # @option opt [String]                    :grade                  *REQUIRED*
  # @option opt [String]                    :username
  # @option opt [String]                    :password
  # @option opt [BsDisabilityType]          :disabilityType         *REQUIRED*
  # @option opt [BsProofOfDisabilitySource] :proofSource            *REQUIRED*
  # @option opt [Array<BsDisabilityPlan>]   :disabilityPlan
  #
  # @return [Bs::Message::UserAccount]
  #
  # @see https://apidocs.bookshare.org/reference/index.html#_create-my-organizationmember
  #
  def add_my_organization_member: (**untyped opt) -> Bs::Message::UserAccount
end
