# BookshareService::Action::Recommendations
#
# == Usage Notes
#
# === From API section 2.12 (Recommendations):
# Recommendations represent titles that Bookshare recommends to a user based on
# their reading history.
#
module BookshareService::Action::Recommendations
  include BookshareService::Common

  include BookshareService::Testing

  # == GET /v2/myRecommendations
  #
  # == 2.12.1. Get my recommended titles
  # Get recommended titles for the requesting user.
  #
  # @param [Hash] opt                       Passed to #api.
  #
  # @option opt [String]  :start
  # @option opt [Integer] :limit
  #
  # @return [Bs::Message::RecommendedTitles]
  #
  # @see https://apidocs.bookshare.org/reference/index.html#_get-my-recommended-titles
  #
  def get_recommendations: (**untyped opt) -> Bs::Message::RecommendedTitles
end
