# This is a replacement for ActionMailer::MailDeliveryJob which persists the
# job results to the "good_jobs" table, allowing it to show up in the GoodJob
# dashboard.
#
class MailerJob < ApplicationJob
  # Generate mail via *mail_method* and deliver it.
  #
  # @param [String, Class] mailer
  # @param [any]           mail_method
  # @param [any]           delivery_method
  # @param [any]           args             ruby2_keywords :args, :params
  # @param [Hash]          opt
  #
  # @return [void]
  #
  def perform: (untyped mailer, untyped mail_method, untyped delivery_method, *untyped args, **untyped opt) -> untyped

  private

  # "Deserialize" the mailer class name by hand in case another argument
  # (like a Global ID reference) raised DeserializationError.
  #
  # @return [Class, nil]
  #
  def mailer_class: () -> (Class | nil)

  # Invoke ActionMailer rescue handler if possible.
  #
  # @param [Exception] exception
  #
  # @return [void]
  #
  def handle_exception_with_mailer_class: (Exception exception) -> void
end
