# The base class for serialization/de-serialization of objects derived from
# IaDownload::Api::Record.
#
class IaDownload::Api::Serializer < Api::Serializer
  include IaDownload::Api::Serializer::Schema

  include IaDownload::Api::Serializer::Associations
end
