# JSON-specific definition overrides for serialization.
#
# @see Api::Serializer::Json::Schema
#
module AwsS3::Api::Serializer::Json::Schema
  include AwsS3::Api::Serializer::Schema

  include Api::Serializer::Json::Schema
end
